### ISSUE TITLE
server crash problem

### ISSUE THREAD

**Issue by sairmali** [salman0ansari/whatsapp-api-nodejs#100]
{"level":30,"time":1652609412000,"pid":112539,"hostname":"280222-cloud02","msg":                                                                                        "Listening to port 3344"}
{"level":50,"time":1652609839222,"pid":112539,"hostname":"280222-cloud02","err":                                                                                        {"type":"Error","message":"Timed Out","stack":"Error: Timed Out\n    at /home/33                                                                                        44/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:178:32","data":{"stac                                                                                        k":"Error\n    at Object.promiseTimeout (/home/3344/node_modules/@adiwajshing/ba                                                                                        ileys/lib/Utils/generics.js:173:19)\n    at waitForMessage (/home/3344/node_modu                                                                                        les/@adiwajshing/baileys/lib/Socket/socket.js:114:42)\n    at query (/home/3344/                                                                                        node_modules/@adiwajshing/baileys/lib/Socket/socket.js:137:22)\n    at sendPassi                                                                                        veIq (/home/3344/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:332:37)\                                                                                        n    at WebSocket.<anonymous> (/home/3344/node_modules/@adiwajshing/baileys/lib/                                                                                        Socket/socket.js:447:15)\n    at WebSocket.emit (events.js:400:28)\n    at /home                                                                                        /3344/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:246:35\n    at Obje                                                                                        ct.decodeFrame (/home/3344/node_modules/@adiwajshing/baileys/lib/Utils/noise-han                                                                                        dler.js:143:17)\n    at WebSocket.onMessageRecieved (/home/3344/node_modules/@ad                                                                                        iwajshing/baileys/lib/Socket/socket.js:222:15)\n    at WebSocket.emit (events.js                                                                                        :400:28)"},"isBoom":true,"isServer":false,"output":{"statusCode":408,"payload":{                                                                                        "statusCode":408,"error":"Request Time-out","message":"Timed Out"},"headers":{}}                                                                                        },"msg":"Timed Out"}
{"level":30,"time":1652609839223,"pid":112539,"hostname":"280222-cloud02","msg":                                                                                        "Server closed"}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! whatsapp-api-nodejs@3.0.0 start: `node src/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the whatsapp-api-nodejs@3.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                                                        ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-05-15T10_17_19_288Z-debug.log
root@280222-cloud02:/home/3344#

**Comment by salman0ansari** [comment]
you're the only one facing this issue

**Comment by sairmali** [comment]
you have any solution  . i don't know why i am facing this issue
