### ISSUE TITLE
Sending media show response status "PENDING"

### ISSUE THREAD

**Issue by AshSoftTech** [salman0ansari/whatsapp-api-nodejs#102]
Every Time I call "Send File Url" API the response Status show "PENDING".

**Comment by salman0ansari** [comment]
so?

**Comment by salman0ansari** [comment]
What is the problem here?

**Comment by AshSoftTech** [comment]
when I send media how can I confirm throw the backend whether the image is sent or not?

**Comment by elp4nsho** [comment]
thats is the problem, it says pending but files never is sended

**Comment by salman0ansari** [comment]
> thats is the problem, it says pending but files never are sended

That's because you're using invalid mimetype
