### ISSUE TITLE
Getting error when scaning qrcode - on heroku server

### ISSUE THREAD

**Issue by amanchoudhary2014** [salman0ansari/whatsapp-api-nodejs#105]
{"level":50,"time":1653020475799,"pid":22,"hostname":"84be0be5-0677-4ba6-be4c-084733b78698","err":{"type":"Error","message":"ENOENT: no such file or directory, open '/app/src/api/sessiondata/9304815125.json'","stack":"Error: ENOENT: no such file or directory, open '/app/src/api/sessiondata/9304815125.json'\n    at Object.openSync (node:fs:585:3)\n    at writeFileSync (node:fs:2170:35)\n    at saveState (/app/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:120:9)\n    at Object.set (/app/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:157:21)\n    at Object.transaction (/app/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:81:37)\n    at async assertingPreKeys (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:191:9)\n    at async uploadPreKeys (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:200:9)\n    at async WebSocket.<anonymous> (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:445:13)","errno":-2,"syscall":"open","code":"ENOENT","path":"/app/src/api/sessiondata/9304815125.json"},"msg":"ENOENT: no such file or directory, open '/app/src/api/sessiondata/9304815125.json'"}

**Comment by salman0ansari** [comment]
read error(slowly)
