### ISSUE TITLE
send images, videos and audio with php curl

### ISSUE THREAD

**Issue by linkon1040z** [salman0ansari/whatsapp-api-nodejs#106]
I'm not able to send audios, images and videos with the curl php request from the documentation, it only sends it to my whatsApp web view, but it doesn't send it to the recipient, can anyone help me?

**Comment by sairmali** [comment]
========audio========


$base_url = '127.0.0.1:3333';
 $number = '91999999999';
 $url_key = '54f4ds6fhfhggfhjd54f65ds4fsfj';
 $url = $base_url.'/message/audio?key='.$url_key.'&id='.$number;
 $curl = curl_init();
 curl_setopt_array($curl, array(
 CURLOPT_URL => $url,
 CURLOPT_RETURNTRANSFER => true,
 CURLOPT_ENCODING => '',
 CURLOPT_MAXREDIRS => 10,
 CURLOPT_TIMEOUT => 0,
 CURLOPT_FOLLOWLOCATION => true,
 CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
 CURLOPT_CUSTOMREQUEST => 'POST',
 CURLOPT_POSTFIELDS => array('file'=> new CURLFILE('http://localhost/laravel/storage/app/'.$path, 'audio/mpeg'), 'id' => $number),
CURLOPT_HTTPHEADER => array(
'accept: application/json',
'Content-Type: multipart/form-data'
),
));

$response = curl_exec($curl);
curl_close($curl);
$response = json_decode($response);

**Comment by sairmali** [comment]
======video========
 $base_url = '127.0.0.1:3333';
 $number = '91999999999';
 $url_key = '54f4ds6fhfhggfhjd54f65ds4fsfj';
 $url = $base_url.'/message/video?key='.$url_key.'&id='.$number;
 $curl = curl_init();
 curl_setopt_array($curl, array(
 CURLOPT_URL => $url,
 CURLOPT_RETURNTRANSFER => true,
 CURLOPT_ENCODING => '',
 CURLOPT_MAXREDIRS => 10,
 CURLOPT_TIMEOUT => 0,
 CURLOPT_FOLLOWLOCATION => true,
 CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
 CURLOPT_CUSTOMREQUEST => 'POST',
 CURLOPT_POSTFIELDS => array('file'=> new CURLFILE('http://localhost/laravel/storage/app/'.$path, 'video/mp4'), 'id' => $number),
CURLOPT_HTTPHEADER => array(
'accept: application/json',
'Content-Type: multipart/form-data'
),
));

$response = curl_exec($curl);
curl_close($curl);
$response = json_decode($response);

**Comment by linkon1040z** [comment]
> ========audio========
> 
> $base_url = '127.0.0.1:3333'; $number = '91999999999'; $url_key = '54f4ds6fhfhggfhjd54f65ds4fsfj'; $url = $base_url.'/message/audio?key='.$url_key.'&id='.$number; $curl = curl_init(); curl_setopt_array($curl, array( CURLOPT_URL => $url, CURLOPT_RETURNTRANSFER => true, CURLOPT_ENCODING => '', CURLOPT_MAXREDIRS => 10, CURLOPT_TIMEOUT => 0, CURLOPT_FOLLOWLOCATION => true, CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1, CURLOPT_CUSTOMREQUEST => 'POST', CURLOPT_POSTFIELDS => array('file'=> new CURLFILE('[http://localhost/laravel/storage/app/'.$path](http://localhost/laravel/storage/app/'.%24path), 'audio/mpeg'), 'id' => $number), CURLOPT_HTTPHEADER => array( 'accept: application/json', 'Content-Type: multipart/form-data' ), ));
> 
> $response = curl_exec($curl); curl_close($curl); $response = json_decode($response);

thank you very much, it works perfectly now
