### ISSUE TITLE
Instance end point throw Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by manojsitapara** [salman0ansari/whatsapp-api-nodejs#11]
First time when instance end point gets call, it work as expected but when I call instance end point again to check user's login status, it throw following error

> (node:18) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
> 
> at ServerResponse.setHeader (_http_outgoing.js:561:11)
> 
> at ServerResponse.header (/app/node_modules/express/lib/response.js:771:10)
> 
> at ServerResponse.send (/app/node_modules/express/lib/response.js:170:12)
> 
> at ServerResponse.json (/app/node_modules/express/lib/response.js:267:15)
> 
> at /app/Routes/Instance.js:63:9
> 
> at processTicksAndRejections (internal/process/task_queues.js:95:5)
> 
> (node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)

I think this error throw because loginverify.js file return response if phone isn't connected and instance end point also return response.

we need to specify the return keyword like this in loginverify.js file to fix the issue

`return res.status(401).send(({ error: true, message: "phone isn't connected" }))`
`return res.status(403).send(({ error: true, message: 'no key query was present' }))`

Please correct me, if I am wrong.

**Comment by salman0ansari** [comment]
Intresting
