### ISSUE TITLE
Shouldn't we use useMultiFileAuthState?

### ISSUE THREAD

**Issue by empresarrollo** [salman0ansari/whatsapp-api-nodejs#110]
Per [the documentation](https://adiwajshing.github.io/Baileys/#saving-amp-restoring-sessions), they give that function `useMultiFileAuthState` to use, instead of `useSingleFileAuthState` that is used now in this api, in the file instance.js.

also it says:

> Note: When a message is received/sent, due to signal sessions needing updating, the auth keys (authState.keys) will update. Whenever that happens, you must save the updated keys (authState.keys.set() is called). Not doing so will prevent your messages from reaching the recipient & other unexpected consequences. The useMultiFileAuthState function automatically takes care of that, but for any other serious implementation -- you will need to be very careful with the key state management.

so using useMultiFileAuthState I think is important?

**Comment by empresarrollo** [comment]
Sorry, I see its not even on the published baileys package yet. (But they put it in the documentation)

**Comment by salman0ansari** [comment]
wait till the release stable version.

**Comment by salman0ansari** [comment]
we will be using MongoDb to save state.
