### ISSUE TITLE
can't scan qrcode

### ISSUE THREAD

**Issue by candra1098** [salman0ansari/whatsapp-api-nodejs#113]
after scan pops up warning "unable to link device'

**Comment by salman0ansari** [comment]
join multi device and scan qr ASAP after you get a key

**Comment by candra1098** [comment]
How to join multi device?

**Comment by salman0ansari** [comment]
google

**Comment by salman0ansari** [comment]
https://www.techadvisor.com/how-to/social-networks/whatsapp-multi-device-3806627/

**Comment by salman0ansari** [comment]
irrelevant
