### ISSUE TITLE
send PDF document received in base64

### ISSUE THREAD

**Issue by cevv13** [salman0ansari/whatsapp-api-nodejs#114]
Greetings.
I recently started testing this project, and I really like the way it is done.
But I have a concern about how to send PDF document which received in base64.

I have a process that receives the PDF in base64, but I've been trying to use this API to send and it doesn't work for me.
Is there any way to process the PDF in base64 to send it as a document?

thanks

**Comment by salman0ansari** [comment]
you cant send raw base64 you first have to convert base64 to PDF [base64topdf](https://www.npmjs.com/package/base64topdf)
after converting simply send pdf as document [/message/doc](https://documenter.getpostman.com/view/12514774/UVsPQkBq#267fde06-a130-4f42-99f8-a8bb7242fdf1)

**Comment by cevv13** [comment]
they banned my number after 1 day of test sending the notifications... are there any guidelines or recommendations so that this does not happen?

**Comment by cevv13** [comment]
it is a physical phone line that I had on a smartphone
