### ISSUE TITLE
Is webhook already working?

### ISSUE THREAD

**Issue by davis7912** [salman0ansari/whatsapp-api-nodejs#115]
In the .env file I marked WEBHOOK_ENABLED=true and added url webhook.site but I don't get any response in webhook.site.

I ran test localhost:3333 and with ngrok.

Would you help me?

**Comment by pra021** [comment]
add webhook when you initialize connection
 localhost:3333/instance/init?key=ADD-YOUR-KEY&webhook=true&webhookUrl=https://ADD-YOUR-WEBHOOK-URL
