### ISSUE TITLE
Any webhook examples?

### ISSUE THREAD

**Issue by ramonck** [salman0ansari/whatsapp-api-nodejs#117]
Hi,

Any example code for a webhook? Do we have to use the send or can we respond to the webhook with the message? How does it work?

**Comment by salman0ansari** [comment]
wdym ?? you want to respond to webhook response?

**Comment by ramonck** [comment]
yes, like in other apis you respond to webhook.

**Comment by salman0ansari** [comment]
https://www.geeksforgeeks.org/what-is-a-webhook-and-how-to-use-it/
