### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by sairmali** [salman0ansari/whatsapp-api-nodejs#118]
![image](https://user-images.githubusercontent.com/54973008/170982920-3941c4bf-af6d-4013-b9ef-5fadd8ed736d.png)

**Comment by salman0ansari** [comment]
*a bug in dependency* what can i do?

**Comment by sairmali** [comment]
how can i resolve this  problem . when i install so, i found this notice ?

please give any solution

**Comment by sairmali** [comment]
@salman0ansari please tell how can i do it

**Comment by salman0ansari** [comment]
> ![image](https://user-images.githubusercontent.com/54973008/170982920-3941c4bf-af6d-4013-b9ef-5fadd8ed736d.png)

You blind or something?
Clearly written here
`No fix available`

**Comment by salman0ansari** [comment]
you want me to fix vulnerability in multer/busybox? 🤡

**Comment by sairmali** [comment]
> you want me to fix vulnerability in multer/busybox? 🤡

yes i am not able to fix this issue on my vps server

**Comment by drdaga** [comment]
so this cannot be installed due to this issue right ??
actually i tried to install in new server.....
i got same error 
so may b we hv to w8 till we get fix from the busybox :(

**Comment by sairmali** [comment]
> so this cannot be installed due to this issue right ?? actually i tried to install in new server..... i got same error so may b we hv to w8 till we get fix from the busybox :(

yes same error i am also face this

**Comment by sairmali** [comment]
this problem not fix ?

**Comment by drdaga** [comment]
> this problem not fix ?

is this problem fixed ??

**Comment by salman0ansari** [comment]
> > this problem not fix ?
> 
> is this problem fixed ??

Use yarn s
