### ISSUE TITLE
Error on delete endpoint

### ISSUE THREAD

**Issue by manojsitapara** [salman0ansari/whatsapp-api-nodejs#12]
When delete endpoint called, it throw following error when 

> /app/node_modules/@adiwajshing/baileys/lib/WAConnection/3.Connect.js:79
> const rejectAllOnWSClose = ({ reason }) => rejectAll(new Error(reason)); 
> Error: intentional
> at WAConnection.rejectAllOnWSClose (/app/node_modules/@adiwajshing/baileys/lib/WAConnection/3.Connect.js:79:62)
> at WAConnection.emit (node:events:402:35)
> at WAConnection.emit (/app/node_modules/@adiwajshing/baileys/lib/WAConnection/4.Events.js:664:41)
> at WAConnection.endConnection (/app/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:417:14)
> at WAConnection.closeInternal (/app/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:400:14)
> at WAConnection.close (/app/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:392:14)
> at WAConnection.logout (/app/node_modules/@adiwajshing/baileys/lib/WAConnection/0.Base.js:388:14)
> at WhatsAppInstance.logout (/app/Objects/instanceClass.js:286:35)
> at /app/Routes/Instance.js:105:20
> at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> Node.js v17.2.0

Delete endpoint try to logout even whatsapp instance is not logged in

we can fix this issue by following code in delete end point, similar fix need to add in logout endpoint 

`    await instance.conn?.logout();`

**Comment by salman0ansari** [comment]
Thank you for reporting
