### ISSUE TITLE
Error Scan QR, Server Close

### ISSUE THREAD

**Issue by rodrigoaballay** [salman0ansari/whatsapp-api-nodejs#121]
Hi, my problem is the following, when trying to scan the QR code, it does it correctly but then it throws me the following error MongooseError and the server closes me.

{"level":50,"time":1654172366699,"pid":22016,"hostname":"DESKTOP-D9N93PJ","err":{"type":"MongooseError","message":"Operation `chats.findOne()` buffering timed out after 10000ms","stack":"MongooseError: Operation `chats.findOne()` buffering timed out after 10000ms\n    at Timeout.<anonymous> (C:\\Users\\PC\\Documents\\whatsapp\\whatsapp-api-nodejs\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:151:23)\n    at listOnTimeout (internal/timers.js:557:17)\n    at processTimers (internal/timers.js:500:7)"},"msg":"Operation `chats.findOne()` buffering timed out after 10000ms"}
{"level":30,"time":1654172366700,"pid":22016,"hostname":"DESKTOP-D9N93PJ","msg":"Server closed"}

**Comment by salman0ansari** [comment]
add mongo url

**Comment by salman0ansari** [comment]
in .env file

**Comment by rodrigoaballay** [comment]
> add mongo url in .env file

In te .env i need change this:
'mongodb://127.0.0.1:27019/whatsapp_api'
for this: ?
'mongodb+srv://tesapi:<password>@cluster0.mxxxxx.mongodb.net/?retryWrites=true&w=majority'

I am right?

**Comment by salman0ansari** [comment]
yes

**Comment by thiagomagamoc** [comment]
> yes

Even though I set the MONGODB_ENABLED=false the service gives an error and closes, as mentioned in the main topic. Is there any solution?

**Comment by salman0ansari** [comment]
> > yes
> 
> Even though I set the MONGODB_ENABLED=false the service gives an error and closes, as mentioned in the main topic. Is there any solution?

You cant use this lib without mongodb set mongo_enabled as true
