### ISSUE TITLE
getting error when send images

### ISSUE THREAD

**Issue by Denver1997** [salman0ansari/whatsapp-api-nodejs#13]
(node:7660) [DEP0128] DeprecationWarning: Invalid 'main' field in 'C:\Users\sbra
n\OneDrive\Desktop\whatsapp-api-nodejs-main\whatsapp-api-nodejs-main\node_module
s\swagger-ui-express\package.json' of './lib/index.js'. Please either fix that o
r report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
�: Listening on PORT => http://localhost:3333
C:\Users\sbran\OneDrive\Desktop\whatsapp-api-nodejs-main\whatsapp-api-nodejs-mai
n\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:190
                onErr = ({ reason, status }) => reject(new Constants_1.BaileysEr
ror(reason, { status }));
                                                       ^

BaileysError: Not expecting a response
    at onErr (C:\Users\sbran\OneDrive\Desktop\whatsapp-api-nodejs-main\whatsapp-
api-nodejs-main\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:190
:56)
    at C:\Users\sbran\OneDrive\Desktop\whatsapp-api-nodejs-main\whatsapp-api-nod
ejs-main\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:185:82
    at Timeout.<anonymous> (C:\Users\sbran\OneDrive\Desktop\whatsapp-api-nodejs-
main\whatsapp-api-nodejs-main\node_modules\@adiwajshing\baileys\lib\WAConnection
\0.Base.js:272:21)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  status: 422,
  context: { status: 422 }
}

**Comment by salman0ansari** [comment]
did u send image using swagger?

**Comment by salman0ansari** [comment]
run this cmd in the project directory 
```
npm install swagger-ui-express@4.3.0
```
