### ISSUE TITLE
new install error

### ISSUE THREAD

**Issue by drdaga** [salman0ansari/whatsapp-api-nodejs#133]
while installing i am getting following error

ubuntu@instance-20220609-1321:~/whatsapp-api-nodejs$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @adiwajshing/baileys@4.1.0
npm ERR! Found: sharp@0.30.5
npm ERR! node_modules/sharp
npm ERR!   sharp@"^0.30.5" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional sharp@"^0.29.3" from @adiwajshing/baileys@4.1.0
npm ERR! node_modules/@adiwajshing/baileys
npm ERR!   @adiwajshing/baileys@"^4.1.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: sharp@0.29.3
npm ERR! node_modules/sharp
npm ERR!   peerOptional sharp@"^0.29.3" from @adiwajshing/baileys@4.1.0
npm ERR!   node_modules/@adiwajshing/baileys
npm ERR!     @adiwajshing/baileys@"^4.1.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/ubuntu/.npm/eresolve-report.txt for a full report.

**Comment by sairmali** [comment]
Try to install with "yarn install"
