### ISSUE TITLE
button send error

### ISSUE THREAD

**Issue by Denver1997** [salman0ansari/whatsapp-api-nodejs#14]
C:\Users\sbran\OneDrive\Desktop\whatsapp-api-nodejs-main\whatsapp-api-nodejs-main\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:190
                onErr = ({ reason, status }) => reject(new Constants_1.BaileysError(reason, { status }));
                                                       ^

BaileysError: Not expecting a response
    at onErr (C:\Users\sbran\OneDrive\Desktop\whatsapp-api-nodejs-main\whatsapp-api-nodejs-main\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:190:56)
    at C:\Users\sbran\OneDrive\Desktop\whatsapp-api-nodejs-main\whatsapp-api-nodejs-main\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:185:82
    at Timeout.<anonymous> (C:\Users\sbran\OneDrive\Desktop\whatsapp-api-nodejs-main\whatsapp-api-nodejs-main\node_modules\@adiwajshing\baileys\lib\WAConnection\0.Base.js:272:21)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  status: 422,
  context: { status: 422 }
}

**Comment by salman0ansari** [comment]
how many buttons you're sending ??
and make sure the button schema is valid.
check button schema here: 
[Button Msg](http://api.mdsalman.tech/api-docs/#/SendMessagesController/sendMessagesControllerSendButton)

**Comment by Denver1997** [comment]
Me also Sending from docs

**Comment by salman0ansari** [comment]
> Me also Sending from docs

How many buttons you are sending?

**Comment by Denver1997** [comment]
1 only

**Comment by Denver1997** [comment]
{
  "msg_data": {
    "id": "string",
    "contentText": "string",
    "footerText": "string",
    "buttons": [
      {
        "buttonId": "string",
        "buttonText": {
          "displayText": "string"
        },
        "type": 0
      }
    ],
    "headerType": 0
  }
}
using same

**Comment by salman0ansari** [comment]
value of **type** and **headerType** should be 1.
```
{
  "msg_data": {
    "id": "1463465600",
    "contentText": "Hello world",
    "footerText": "Footer",
    "buttons": [
      {
        "buttonId": "Hello",
        "buttonText": {
          "displayText": "Hello"
        },
        "type": 1
      }
    ],
    "headerType": 1
  }
}
```

**Comment by Denver1997** [comment]
Thanks Works Now
