### ISSUE TITLE
Is possible new installation ??

### ISSUE THREAD

**Issue by drdaga** [salman0ansari/whatsapp-api-nodejs#140]
# npm audit report

dicer  *
Severity: high
Crash in HeaderParser in dicer - https://github.com/advisories/GHSA-wm7h-9275-46v2
No fix available
node_modules/dicer
  busboy  <=0.3.1
  Depends on vulnerable versions of dicer
  node_modules/busboy
    multer  <=2.0.0-rc.3
    Depends on vulnerable versions of busboy
    node_modules/multer

3 high severity vulnerabilities

is this fixed ??

any another way to skip and force install ??

**Comment by salman0ansari** [comment]
dublicate #118
