### ISSUE TITLE
Bug Restore

### ISSUE THREAD

**Issue by bmbraga** [salman0ansari/whatsapp-api-nodejs#149]
Whenever the entire endpoint to restore is giving this error.
And whenever an error is restarting the server, causing problems.

0|Whatsapp  | Failed to decrypt message with any known session...
0|Whatsapp  | Session error:MessageCounterError: Key used already or never filled MessageCounterError: Key used already or never filled
0|Whatsapp  |     at SessionCipher.doDecryptWhisperMessage (/home/ec2-user/whatsapp-api-nodejs/node_modules/libsignal/src/session_cipher.js:236:19)
0|Whatsapp  |     at SessionCipher.decryptWithSessions (/home/ec2-user/whatsapp-api-nodejs/node_modules/libsignal/src/session_cipher.js:147:40)
0|Whatsapp  |     at Object.5516991490332.0 [as awaitable] (/home/ec2-user/whatsapp-api-nodejs/node_modules/libsignal/src/session_cipher.js:171:39)
0|Whatsapp  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|Whatsapp  |     at async _asyncQueueExecutor (/home/ec2-user/whatsapp-api-nodejs/node_modules/libsignal/src/queue_job.js:20:29)
0|Whatsapp  | Failed to decrypt message with any known session...
0|Whatsapp  | Session error:MessageCounterError: Key used already or never filled MessageCounterError: Key used already or never filled
0|Whatsapp  |     at SessionCipher.doDecryptWhisperMessage (/home/ec2-user/whatsapp-api-nodejs/node_modules/libsignal/src/session_cipher.js:236:19)
0|Whatsapp  |     at SessionCipher.decryptWithSessions (/home/ec2-user/whatsapp-api-nodejs/node_modules/libsignal/src/session_cipher.js:147:40)
0|Whatsapp  |     at Object.5521967529733.0 [as awaitable] (/home/ec2-user/whatsapp-api-nodejs/node_modules/libsignal/src/session_cipher.js:171:39)
0|Whatsapp  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|Whatsapp  |     at async _asyncQueueExecutor (/home/ec2-user/whatsapp-api-nodejs/node_modules/libsignal/src/queue_job.js:20:29)
0|Whatsapp  | Failed to decrypt message with any known session...
0|Whatsapp  | Session error:MessageCounterError: Key used already or never filled MessageCounterError: Key used already or never filled
0|Whatsapp  |     at SessionCipher.doDecryptWhisperMessage (/home/ec2-user/whatsapp-api-nodejs/node_modules/libsignal/src/session_cipher.js:236:19)
0|Whatsapp  |     at SessionCipher.decryptWithSessions (/home/ec2-user/whatsapp-api-nodejs/node_modules/libsignal/src/session_cipher.js:147:40)
0|Whatsapp  |     at Object.5514996676216.0 [as awaitable] (/home/ec2-user/whatsapp-api-nodejs/node_modules/libsignal/src/session_cipher.js:171:39)
0|Whatsapp  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|Whatsapp  |     at async _asyncQueueExecutor (/home/ec2-user/whatsapp-api-nodejs/node_modules/libsignal/src/queue_job.js:20:29)
0|Whatsapp  | Failed to decrypt message with any known session...
0|Whatsapp  | Session error:MessageCounterError: Key used already or never filled MessageCounterError: Key used already or never filled
0|Whatsapp  |     at SessionCipher.doDecryptWhisperMessage (/home/ec2-user/whatsapp-api-nodejs/node_modules/libsignal/src/session_cipher.js:236:19)
0|Whatsapp  |     at SessionCipher.decryptWithSessions (/home/ec2-user/whatsapp-api-nodejs/node_modules/libsignal/src/session_cipher.js:147:40)
0|Whatsapp  |     at Object.554791615632.0 [as awaitable] (/home/ec2-user/whatsapp-api-nodejs/node_modules/libsignal/src/session_cipher.js:171:39)
0|Whatsapp  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by salman0ansari** [comment]
Its not a bug don't use this project in production
until we implement key storage

**Comment by anandsork** [comment]
If I invoke
setTimeout(async() => {
      try {
         await this.instance.sock.resyncMainAppState();
       } catch (e) {
           console.log(e)
       }
}, 2000);

After socket Creation.. it seems to resolve the issue.. 
Now sure this is a right approach.
