### ISSUE TITLE
Delivery confirmation

### ISSUE THREAD

**Issue by bmbraga** [salman0ansari/whatsapp-api-nodejs#150]
How can I confirm that a message was actually delivered? This week has increased the number of messages that are not delivered, with status = PENDING.
How can I see the real status and how is the send queue?

**Comment by salman0ansari** [comment]
duplicate of #77

**Comment by Zarinia** [comment]
You can check 
```
ev.on('messages.update', async (messages) => {
console.dir(messages);
for (const message of messages) {
is_delivered = message?.update?.status === 3;
is_seen = message?.update?.status === 4
}
})
```

with this socket, every time that message status changes this socket fires and notifies you

**Comment by pauloanalista** [comment]
Can you raise a PR with this solution?

Do you receive via webhook?

**Comment by sairmali** [comment]
@bmbraga how can i implement this for message status
