### ISSUE TITLE
Env

### ISSUE THREAD

**Issue by bmbraga** [salman0ansari/whatsapp-api-nodejs#153]
Hi,

How are you?
Which model of configuration of these variables to be correct as it was before, showing Windows and Chrome?

CLIENT_PLATFORM='Whatsapp MD'
CLIENT_BROWSER=''
`CLIENT_VERSION='3.0'`

![WhatsApp-Image-2022-06-21-at-11-20-00](https://user-images.githubusercontent.com/23003286/174825130-9d1eae5f-d27f-4b70-901b-239ccfbd5c59.jpg)

**Comment by salman0ansari** [comment]
CLIENT_PLATFORM='Whatsapp MD'
CLIENT_BROWSER='Chrome'
CLIENT_VERSION='4.0.0'
