### ISSUE TITLE
Error requesting  " GETBlock/Unblock User "

### ISSUE THREAD

**Issue by Raf1401** [salman0ansari/whatsapp-api-nodejs#158]
Hello.

Making a GET request from a GET Block/Unblock User, after about 10 seconds comes this return:

{"error":true,"code":500,"message":"Error: Timed Out"}

All other requests are functional.

Can you tell me if I have to change something in the request or even inform the token?

The request used:

http://localhost:3333/misc/blockUser?key=(mykey)&id=(number)

And I also tried as follows:

http://localhost:3333/misc/blockUser?key=(mykey)&id=(number)&token=(RND)

None have been successful.

How can I order?

**Comment by salman0ansari** [comment]
you're missing `block_status` 
https://github.com/salman0ansari/whatsapp-api-nodejs/blob/9437cdd729208c28d9beffc0ca386e72d4f6ba42/src/api/controllers/misc.controller.js#L23

**Comment by Raf1401** [comment]
Working perfectly. Thank you and congratulations for the excellent tool created.
