### ISSUE TITLE
Restore or Rescan

### ISSUE THREAD

**Issue by baagas0** [salman0ansari/whatsapp-api-nodejs#160]
how does my system know that whatsapp instance needs to be restored or barcode re-scan?

**Comment by salman0ansari** [comment]
Restore instances when the server is closed.
rescan QRcode? what do you mean?

**Comment by baagas0** [comment]
like a case study like this one my client accidentally deleted a session via his device which caused the saved session to be invalid and required a qr code re-scan to get a valid token

**Comment by baagas0** [comment]
so we will delete saved json file session on folder src/api/sessiondata automatically if there delete a session by device? can we get a webhook for this action?

**Comment by salman0ansari** [comment]
> so we will delete saved json file session on folder src/api/sessiondata automatically if there delete a session by device? can we get a webhook for this action?

no

**Comment by salman0ansari** [comment]
you can add it yourself

**Comment by baagas0** [comment]
Thanks for your answer
