### ISSUE TITLE
error connecting to MongoDB

### ISSUE THREAD

**Issue by fabionoa** [salman0ansari/whatsapp-api-nodejs#162]
Hi, congratulations and thanks for the project!! 
After yesterday's update, I can't run the application anymore, when I run npm start it returns me:
could you please help me?

node src/server.js

{"level":30,"time":1656523978393,"pid":63586,"hostname":"graham","msg":"Listening on port 3331"}
{"level":30,"time":1656523978395,"pid":63586,"hostname":"graham","msg":"STATE: Connecting to MongoDB"}
{"level":50,"time":1656524008394,"pid":63586,"hostname":"graham","err":{"type":"NodeError","message":"Invalid URL: 127.0.0.1:27017","stack":"TypeError [ERR_INVALID_URL]: Invalid URL: 127.0.0.1:27017\n    at new NodeError (internal/errors.js:322:7)\n    at onParseError (internal/url.js:270:9)\n    at new URL (internal/url.js:346:5)\n    at isAtlas (/home/lifeseller/whatsapp-api-nodejs/node_modules/mongoose/lib/helpers/topology/isAtlas.js:17:17)\n    at MongooseServerSelectionError.assimilateError (/home/lifeseller/whatsapp-api-nodejs/node_modules/mongoose/lib/error/serverSelection.js:35:35)\n    at /home/lifeseller/whatsapp-api-nodejs/node_modules/mongoose/lib/connection.js:825:36","input":"127.0.0.1:27017","code":"ERR_INVALID_URL"},"msg":"Invalid URL: 127.0.0.1:27017"}
{"level":30,"time":1656524008394,"pid":63586,"hostname":"graham","msg":"Server closed"}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! whatsapp-api-nodejs@3.0.5 start: `node src/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the whatsapp-api-nodejs@3.0.5 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lifeseller/.npm/_logs/2022-06-29T17_33_28_409Z-debug.log

**Comment by davidagostini** [comment]
Even i set MONGODB_ENABLED=false i have the same error

**Comment by salman0ansari** [comment]
> Even i set MONGODB_ENABLED=false i have the same error

Project will not work without mongo.
