### ISSUE TITLE
MONGODB_ENABLED=false requires mongo connection

### ISSUE THREAD

**Issue by pauloanalista** [salman0ansari/whatsapp-api-nodejs#166]
When downloading the latest API version, even in the .env file
MONGODB_ENABLED=false

API tries to connect to mongo

![image](https://user-images.githubusercontent.com/6010161/176894419-7a225b78-e5ab-47b2-8413-19f8b92756a2.png)

**Comment by salman0ansari** [comment]
Project will not work without mongo.

**Comment by pauloanalista** [comment]
I have used without Mongo

So it would be interesting to remove the MONGODB_ENABLED flag

**Comment by jasmanX** [comment]
> I have used without Mongo
> 
> So it would be interesting to remove the MONGODB_ENABLED flag

how to use without Mongo ? please share thanks
