### ISSUE TITLE
Can't Able to start the server

### ISSUE THREAD

**Issue by azartheen** [salman0ansari/whatsapp-api-nodejs#17]
Can't Able to start the server 

I 've using node js version 12 
![git](https://user-images.githubusercontent.com/31647728/149766873-63a742b0-3518-4f0a-8066-8e62844ccf5f.PNG)

can anyone help me to fix

**Comment by salman0ansari** [comment]
update node

**Comment by azartheen** [comment]
except updating node js 14 is there any other ways to do it.. like flag --harmony or --exec ECMA script something like these

**Comment by salman0ansari** [comment]
optional chaining is not supported in Node.js version 13 and below.

**Comment by salman0ansari** [comment]
if problem is fixed please close issue.

**Comment by azartheen** [comment]
i have some project in node version 12... so now using NVM to switch over version
