### ISSUE TITLE
update groups or info in whatsapp application not reflect on api

### ISSUE THREAD

**Issue by luispimenta** [salman0ansari/whatsapp-api-nodejs#172]
Everything working perfectly with mongodb, only updates on whatsapp application are not being reflected, having to start the instance again, like:

I changed my name in the whatsapp application and the route {{baseUrl}}/instance/info?key=123 does not return with the updated name
the same thing for groups, creating a new group through the API, or manually through the application the route {{baseUrl}}/group/listall?key=123 does not return the updated groups

And it would be nice to have a list of the participants of a group!

**Comment by salman0ansari** [comment]
fixed #175
