### ISSUE TITLE
Webhook receive contact card

### ISSUE THREAD

**Issue by eduardofiorini** [salman0ansari/whatsapp-api-nodejs#18]
Hi,
1. I did the tests and the webhook cannot capture the return when a contact card is sent.
2. I did a payment request test by whatsapp also did not receive it on the webhook.
3. Does Baileys allow checking as seen whenever he uploads to the webhook?
Thanks!

**Comment by salman0ansari** [comment]
1. You can capture any msg type you can play with function and add you msgtype you want in webhook.
https://github.com/salman0ansari/whatsapp-api-nodejs/blob/7cd7fe2d8ca114033fcceb6f0084625f7c15f61a/Objects/instanceClass.js#L30

2. wdym by "payment request" ? are you referring to whatsapp payments?

3. can you elaborate more on this?

**Comment by eduardofiorini** [comment]
1. Thank you.
2. Yes, in Brazil it is possible to send or request payments by whatsapp eg: https://prnt/26ltzbe
3. Whenever the API receives the information, it marks it as seen and removes the notification from the device and shows to another device that the message has been viewed eg: https://prnt.sc/26lu11l

**Comment by salman0ansari** [comment]
2. Currently Whatsapp web doesn't allow sending/reciving payments so we can't do anything about it.

**Comment by eduardofiorini** [comment]
2. I was able to get his return through the webhook, this already helps a lot in validating the payment https://prnt.sc/26lugpf Thank you :)

Option 3 would it be possible to have this option to show that the message has been viewed?

**Comment by eduardofiorini** [comment]
Taking advantage of the contact, you can guide me how I can get the full size image, sticker, audio, pdf and other files.

**Comment by salman0ansari** [comment]
> Taking advantage of the contact, you can guide me how I can get the full size image, sticker, audio, pdf and other files.

you want all of this in webhook response?

**Comment by salman0ansari** [comment]
> Taking advantage of the contact, you can guide me how I can get the full size image, sticker, audio, pdf and other files.

because of a typo mistake response was broken, It's fixed now.

**Comment by eduardofiorini** [comment]
Thanks :)
