### ISSUE TITLE
Request Time-out

### ISSUE THREAD

**Issue by luispimenta** [salman0ansari/whatsapp-api-nodejs#184]
Guys, I'm doing several tests and I'm having this error both locally, with docker and also on heroku! I've done it several times I disconnected the instance, deleted the instance, and started it normally, and whenever I send messages this happens, the first messages sent work normally, but then I just get this error and nothing else works :( , anyone experiencing this?
I have the latest version of main here

`{"level":30,"time":1657299178268,"pid":10592,"hostname":"pimenta","msg":"STATE: Connecting to MongoDB"}
{"level":30,"time":1657299180770,"pid":10592,"hostname":"pimenta","msg":"STATE: Successfully connected to MongoDB"}
{"level":30,"time":1657299180770,"pid":10592,"hostname":"pimenta","msg":"Restoring Sessions"}
{"level":30,"time":1657299180784,"pid":10592,"hostname":"pimenta","msg":"Connected to MongoDB"}
{"level":30,"time":1657299181028,"pid":10592,"hostname":"pimenta","msg":"2 Session(s) Restored"}
{"level":30,"time":1657299194194,"pid":10592,"hostname":"pimenta","msg":"STATE: Droped collection"}
Closing stale open session for new outgoing prekey bundle
Closing session: SessionEntry {
  _chains: {
    'Bch9urXF0l8MZQy+jCmQ2f3Pq+Ket0Rayhp6ledDUhN7': { chainKey: [Object], chainType: 1, messageKeys: {} }
  },
  registrationId: 208,
  currentRatchet: {
    ephemeralKeyPair: {
      pubKey: <Buffer 05 c8 7d ba b5 c5 d2 5f 0c 65 0c be 8c 29 90 d9 fd cf ab e2 9e b7 44 5a ca 1a 7a 95 e7 43 52 13 7b>,
      privKey: <Buffer 70 0f 67 2b 75 b0 46 c6 55 ea bd 94 77 96 c9 46 98 53 05 39 7a c0 94 23 b2 21 5c 67 b5 ef b4 64>
    },
    lastRemoteEphemeralKey: <Buffer 05 35 57 3a fb fd 28 4e c4 41 0d b0 dc d4 c3 9a a9 d3 a6 c7 b0 15 2f 4d 17 02 9f 05 7e 99 3c 37 12>,
    previousCounter: 0,
    rootKey: <Buffer 47 58 c4 dd 50 10 29 9c 22 16 2e 2b 87 49 fb b4 2a bc a2 0f e9 16 20 f4 b4 5a 3e 6f 8f bb cb 2a>
  },
  indexInfo: {
    baseKey: <Buffer 05 aa 0a 68 e1 87 3b 91 10 e2 ed 39 b7 ee 56 f3 94 fb a3 d9 0c 0e cb 3c 43 ca d1 62 dd 57 27 eb 3b>,
    baseKeyType: 1,
    closed: -1,
    used: 1657299233661,
    created: 1657299233661,
    remoteIdentityKey: <Buffer 05 e5 4a 25 3d c0 67 5a 3c a3 32 45 3c 9a f8 23 37 05 1f ca c1 e5 66 95 62 e6 a9 30 b3 bf 0a 9c 07>
  },
  pendingPreKey: {
    signedKeyId: 1,
    baseKey: <Buffer 05 aa 0a 68 e1 87 3b 91 10 e2 ed 39 b7 ee 56 f3 94 fb a3 d9 0c 0e cb 3c 43 ca d1 62 dd 57 27 eb 3b>,
    preKeyId: 108
  }
}
{"level":50,"time":1657299235404,"pid":10592,"hostname":"pimenta","err":{"type":"Error","message":"Connection Closed","stack":"Error: Connection Closed\n    at sendRawMessage (/Users/pimenta/projetos/whatsapp-api-nodejs/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:48:19)\n    at sendNode (/Users/pimenta/projetos/whatsapp-api-nodejs/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:59:16)\n    at query (/Users/pimenta/projetos/whatsapp-api-nodejs/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:123:15)\n    at /Users/pimenta/projetos/whatsapp-api-nodejs/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:182:19\n    at async Object.transaction (/Users/pimenta/projetos/whatsapp-api-nodejs/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:82:21)\n    at async uploadPreKeys (/Users/pimenta/projetos/whatsapp-api-nodejs/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:179:9)\n    at async handleEncryptNotification (/Users/pimenta/projetos/whatsapp-api-nodejs/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:176:17)","data":null,"isBoom":true,"isServer":false,"output":{"statusCode":428,"payload":{"statusCode":428,"error":"Precondition Required","message":"Connection Closed"},"headers":{}}},"msg":"Connection Closed"}
{"level":30,"time":1657299235405,"pid":10592,"hostname":"pimenta","msg":"Server closed"}
[nodemon] app crashed - waiting for file changes before starting...`

**Comment by pedroherpeto** [comment]
hiii, same error here! how can i solve it?

**Comment by Sulivan1999** [comment]
Hello!

Adding `defaultQueryTimeoutMs: undefined,` in the socket settings, in the file instance.js in api/class it worked for me.

Stays like this:

```
socketConfig = {
    defaultQueryTimeoutMs: undefined,
    printQRInTerminal: false,
    logger: pino({
        level: config.log.level,
    }),
}
```
