### ISSUE TITLE
{"level":50,"time":1657345041709,"pid":12520,"hostname":"Web-Server","msg":"STATE: Connection to MongoDB failed!"}

### ISSUE THREAD

**Issue by Natarajar87** [salman0ansari/whatsapp-api-nodejs#186]
> whatsapp-api-nodejs@3.0.5 start
> node src/server.js

{"level":30,"time":1657345011674,"pid":12520,"hostname":"Web-Server","msg":"Listening on port 6666"}
{"level":30,"time":1657345011692,"pid":12520,"hostname":"Web-Server","msg":"STATE: Connecting to MongoDB"}
{"level":50,"time":1657345041709,"pid":12520,"hostname":"Web-Server","msg":"STATE: Connection to MongoDB failed!"}
PS C:\Users\Administrator\Desktop\new_whatsapp_server>

# DATABASE CONFIGURATION
# ==================================
MONGODB_ENABLED=false
MONGODB_URL=mongodb://127.0.0.1:27017/whatsapp_api

**Comment by salman0ansari** [comment]
project will not work without mongo.
