### ISSUE TITLE
Unstable API

### ISSUE THREAD

**Issue by robsonppxp** [salman0ansari/whatsapp-api-nodejs#188]
When we start to consume the api for sending messages with image attachments, it starts to show instability and then disconnects. See the attached ### `log..`
[LogApi.txt](https://github.com/salman0ansari/whatsapp-api-nodejs/files/9106138/LogApi.txt)
``

**Comment by salman0ansari** [comment]
anyone else facing same error?

**Comment by Natarajar87** [comment]
Yes I also facing same error

**Comment by salman0ansari** [comment]
https://github.com/adiwajshing/Baileys/issues/1449

**Comment by salman0ansari** [comment]
a lot of users are facing this issue still no fix from Baileys maintainers as soon they find a fix for that I will fix it in this API too.
