### ISSUE TITLE
Random Time-out errors

### ISSUE THREAD

**Issue by sreekanthmr** [salman0ansari/whatsapp-api-nodejs#189]
I deployed this on a local Linux-Nginx environment.  Things work well for some time but I consistently get a time-out error after 10 to 15 minutes.  Here is the error I'm getting

"err": {
	"type": "Error",
	"message": "Timed Out",
	"stack": "Error: Timed Out\n    at /home/ubuntu/whatsapp-api/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:174:32",
	"data": {
		"stack": "Error\n    at promiseTimeout (/home/ubuntu/whatsapp-api/node_modules/@adiwajshing/baileys/lib/Utils/generics.js:169:19)\n    at waitForMessage (/home/ubuntu/whatsapp-api/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:99:61)\n    at query (/home/ubuntu/whatsapp-api/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:122:22)\n    at /home/ubuntu/whatsapp-api/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:250:38\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Object.transaction (/home/ubuntu/whatsapp-api/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:82:21)\n    at async resyncAppState (/home/ubuntu/whatsapp-api/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:216:9)"
	},
	"isBoom": true,
	"isServer": false,
	"output": {
		"statusCode": 408,
		"payload": {
			"statusCode": 408,
			"error": "Request Time-out",
			"message": "Timed Out"
		},
		"headers": {}
	}
}, "msg": "Timed Out"
}

Pls help me find the cause

Thanks
Sreek

**Comment by Sulivan1999** [comment]
Hello, see this possible solution:

https://github.com/salman0ansari/whatsapp-api-nodejs/issues/184#issuecomment-1185989485

**Comment by sreekanthmr** [comment]
> Hello, see this possible solution:
> 
> [#184 (comment)](https://github.com/salman0ansari/whatsapp-api-nodejs/issues/184#issuecomment-1185989485)

Thanks @Sulivan1999 .  I'll try this out.

**Comment by sreekanthmr** [comment]
@Sulivan1999
Looks like it is working.  No errors so far.
Thanks
