### ISSUE TITLE
how to handle Too Many Requests(429) error?

### ISSUE THREAD

**Issue by manojsitapara** [salman0ansari/whatsapp-api-nodejs#19]
User gets QR code by following API

http://localhost:3333/qrcode?key=f7ecc0cf-38e1-4138-a90c-d5ee2d97d809

But when user does not scan qr code for 2 minutes somewhere, it throw following error

`Error: Unexpected status in 'admin': Too Many Requests(429)`

```
WARN [2022-02-08 15:03:06.239 +0000] (51536): error in QR gen
    class: "Baileys"
    error: {
      "name": "BaileysError",
      "status": 429,
      "context": {
        "query": [
          "admin",
          "Conn",
          "reref"
        ],
        "message": "Too Many Requests",
        "status": 429
      }
    }
```

is it possible to handle this error?

**Comment by salman0ansari** [comment]
init a new instance

**Comment by salman0ansari** [comment]
scan qr as fast as possible after init a new instance

**Comment by salman0ansari** [comment]
Init a new instance and
scan qr as fast as possible
