### ISSUE TITLE
Baileys new version

### ISSUE THREAD

**Issue by 100n0m3** [salman0ansari/whatsapp-api-nodejs#190]
there is any way to use new Baileys version?

**Comment by salman0ansari** [comment]
why would you want to use edge(unstable) version?

**Comment by 100n0m3** [comment]
in this new version the problem of sending has already been solved, besides the response time is much faster, in this current version that we use it is taking about 30 seconds just to send it and when it sends it is not delivered

**Comment by salman0ansari** [comment]
wait for npm release

**Comment by 100n0m3** [comment]
@salman0ansari Ok!, thanks

**Comment by salman0ansari** [comment]
if you want to use the edge version you can install it using 
`yarn add github:adiwajshing/baileys`
