### ISSUE TITLE
List all sessions (list instances) returns empty array

### ISSUE THREAD

**Issue by sreekanthmr** [salman0ansari/whatsapp-api-nodejs#192]
Response to list instances is an empty array

{
    "error": false,
    "message": "All instance listed",
    "data": []
}

Thanks

**Comment by salman0ansari** [comment]
working on my side
![image](https://user-images.githubusercontent.com/30106022/179353273-1dbf86aa-a6c0-4aed-af91-1bd1a50b7d9e.png)

**Comment by salman0ansari** [comment]
??
![image](https://user-images.githubusercontent.com/30106022/179353342-99ae84d1-4abb-4651-8a8c-9a8c6f91db43.png)
