### ISSUE TITLE
Sending button templates to groups doesn't work

### ISSUE THREAD

**Issue by tinyCoder32** [salman0ansari/whatsapp-api-nodejs#193]
It returns a timeout error when trying to send buttons to groups, however, it works fine when using Baileys directly out of the REST API.

I guess it is related to the missing `msgRetryCounterMap`, tried implementing it but it didn't work.

Thanks.

**Comment by salman0ansari** [comment]
maybe you are using invalid group jid

**Comment by tinyCoder32** [comment]
Of course not, normal text messages work in the same groups.

I am trying to send buttons with media to a group with more than 200 users, it crashes with 500 error, while groups with 2 or 3 users receive the message with no issues.

**Comment by salman0ansari** [comment]
its a bug of baileys
