### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'includes')

### ISSUE THREAD

**Issue by stonestecnologia** [salman0ansari/whatsapp-api-nodejs#196]
Hi, I'm still using the version of your api that doesn't need MongoDB,
Whatsapp\src\api\sessiondata
but returns the error:
```
{
	"error": true,
	"code": 500,
	"message": "TypeError: Cannot read properties of undefined (reading 'includes')"
}
```

**Comment by salman0ansari** [comment]
update to latest release

**Comment by stonestecnologia** [comment]
I'm sorry, but I cloned the project just yesterday, it was indicated by a colleague that it is the best and most stable.
I believe I have the clone of the most recent, "release"
