### ISSUE TITLE
Webhook

### ISSUE THREAD

**Issue by eduardohr-muniz** [salman0ansari/whatsapp-api-nodejs#197]
Is there a possibility to return the instance or number of the wpp connected to the instance in the webhook?

If there is any way and someone can help me I would appreciate it.

I have multiple instances connected and receiving a webhook in a URL, I just need to identify which instance that webhook is from to respond with a bot

**Comment by salman0ansari** [comment]
you can find instance key inside webhook response.

**Comment by eduardohr-muniz** [comment]
Helo

**Comment by eduardohr-muniz** [comment]
![image](https://user-images.githubusercontent.com/90477293/179394446-3946588d-98f3-4e2e-8a57-bd2b4e12f611.png)

In my call init instance it is returning like this but I am getting the wehook look at the example below.

Look at my webhook the key in this case is =eduardo12 is not showing up for me
{
   "type": "message",
   "body": {
     "key": {
       "remoteJid": "553591705812@s.whatsapp.net",
       "fromMe": true,
       "id": "8974C5D7A42BC6FD59813D37E6BC3BF6"
     },
     "messageTimestamp": 1658053915,
     "pushName": "Eduardo Muniz",
     "status": 2,
     "message": {
       "extendedTextMessage": {
         "text": "Hello",
         "previewType": "NONE",
         "contextInfo": {
           "expiration": 0,
           "ephemeralSettingTimestamp": "1638761518",
           "disappearingMode": {
             "initiator": "CHANGED_IN_CHAT"
           }
         },
         "inviteLinkGroupTypeV2": "DEFAULT"
       }
     },
     "msgContent": ""
   }
}

**Comment by eduardohr-muniz** [comment]
Sorry if I sound rude, I'm Brazilian and I put it in the translator, Does the init call have to return the webhook as true?
Because I'm getting the webhook but it returns false.

**Comment by JoaoNetoDev** [comment]
Have you tried starting an instance passing the webhook in the parameters?! (I'm also Brazilian using Google Translate, "Laughter")

Eg: https://server_api.url:3000/instance/init?token={{token}}&key={{key}}&webhook=true&webhookUrl=https://server_webhook.url/wh_wpp.php

**Comment by eduardohr-muniz** [comment]
@JoaoNetoDev Então coloquei desse jeito resolveu a parte no int ta indo com o webhook porem quando chega não vem o numero que esta conectado a instancia nem a instancia, você sabe um jeito de eu identificar a instancia no webhook?

{
  "type": "message",
  "body": {
    "key": {
      "remoteJid": "553584091567@s.whatsapp.net",
      "fromMe": false,
      "id": "3A893A1E18FD72751A14"
    },
    "messageTimestamp": 1658061741,
    "pushName": "Eduardo Muniz",
    "message": {
      "extendedTextMessage": {
        "text": "Viu",
        "contextInfo": {
          "ephemeralSettingTimestamp": "1638761518",
          "disappearingMode": {
            "initiator": "CHANGED_IN_CHAT"
          }
        }
      },
      "messageContextInfo": {
        "deviceListMetadata": {
          "senderTimestamp": "1658016599",
          "recipientKeyHash": "v/4hSBXPWgjbkg==",
          "recipientTimestamp": "1658060889"
        },
        "deviceListMetadataVersion": 2
      }
    }
  }
}

**Comment by JoaoNetoDev** [comment]
In this case, it might be the case that you passed the webhook url parameter...

wh_wpp.php?number_con=551199999999

Once this is done, on receipt you capture via $_GET...

I continue to use translate because I think owners usually don't like comments in other languages

**Comment by JoaoNetoDev** [comment]
> In this case, it might be the case that you passed the webhook url parameter...
> 
> wh_wpp.php?number_con=551199999999
> 
> Once this is done, on receipt you capture via $_GET...
> 
> I continue to use translate because I think owners usually don't like comments in other languages



> In this case, it might be the case that you passed the webhook url parameter...
> 
> wh_wpp.php?number_con=551199999999
> 
> Once this is done, on receipt you capture via $_GET...
> 
> I continue to use translate because I think owners usually don't like comments in other languages

Never tried it, not sure if it works...

**Comment by eduardohr-muniz** [comment]
@JoaoNetoDev I will test thanks for the force

**Comment by eduardohr-muniz** [comment]
src/api/class)/instance.js
![image](https://user-images.githubusercontent.com/90477293/179402811-2e7875de-e7a1-4030-b178-847a2b113f9d.png)

Solved just change that file. Thank you all!!
