### ISSUE TITLE
Ubuntu VPS Installation

### ISSUE THREAD

**Issue by lpinheirojunior** [salman0ansari/whatsapp-api-nodejs#200]
Hi, congratulations for the excellent work on the api., Is it possible to install it on an Ubuntu VPS?

**Comment by salman0ansari** [comment]
you can install anywhere you want.

**Comment by JoaoNetoDev** [comment]
The API requires MongoDB equal to or greater than 3.6 if I'm not mistaken... Because of this I couldn't install it on a VPS Linux Lite based on Ubuntu 16... But maybe in version 18 of Ubuntu it's already easier
