### ISSUE TITLE
QR Code does not generate via GET request

### ISSUE THREAD

**Issue by higormachado3** [salman0ansari/whatsapp-api-nodejs#204]
I'm passing the request as suggested and my QRcode reading is not working

////////////////////////// Javascript //////////////////////////////////

var requestOptions = {
  method: 'GET',
  redirect: 'follow'
};

fetch("localhost:3333/instance/qrbase64?key=4", requestOptions)
  .then(response => response.text())
  .then(result => console.log(result))
  .catch(error => console.log('error', error));

////////////////// CONSOLE /////////////////////////////

Access to fetch at 'http://localhost:3333/instance/qrbase64?key=4' from origin  has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

javascript.js:18 GET http://localhost:3333/instance/qrbase64?key=4 net::ERR_FAILED 200

**Comment by salman0ansari** [comment]
```js
let requestOptions = {
method: 'GET',
redirect: 'follow',
mode: 'no-cors'
};
```

**Comment by salman0ansari** [comment]
> I couldn't because that way there's no response and then I can't capture the QRcode url

init instance again then call QR endpoint
