### ISSUE TITLE
Status composing 

### ISSUE THREAD

**Issue by linkon1040z** [salman0ansari/whatsapp-api-nodejs#211]
how to enter a delay time and composition status, before sending text?

my code:

 async sendTextMessage(to, message) {
        await this.verifyId(this.getWhatsAppId(to))
        await this.instance.sock?.sendPresenceUpdate('composing', to);
        await delay(1000);
        const data = await this.instance.sock?.sendMessage(
            this.getWhatsAppId(to),
            { text: message }
        )
        return data
    }

**Comment by salman0ansari** [comment]
```javascript
await this.instance.sock?.presenceSubscribe(jid);
await delay(500);
await this.setStatus('composing', jid);
await delay(2000);
await this.setStatus('paused', jid);
await this instance.sock?.sendMessage(jid, msg);
```

**Comment by linkon1040z** [comment]
> ```js
> await this.instance.sock?.presenceSubscribe(jid);
> await delay(500);
> await this.setStatus('composing', jid);
> await delay(2000);
> await this.setStatus('paused', jid);
> await this.instance.sock?.sendMessage(jid, msg);
> ```

Thanks bro

**Comment by leandrodesign** [comment]
> ```js
> await this.instance.sock?.sendMessage(jid, msg);
> ```

Still works? where do i put it
