### ISSUE TITLE
Tutorial to use webhook

### ISSUE THREAD

**Issue by lpinheirojunior** [salman0ansari/whatsapp-api-nodejs#219]
Could you provide a tutorial showing the implementation of the webhook? I've already tried to do this with the information in your repository, but after several attempts I still can't receive messages through the api.

**Comment by linkon1040z** [comment]
# ==================================
# WEBHOOK CONFIGURATION
# ==================================
WEBHOOK_ENABLED = true
WEBHOOK_URL = https://HERE YOUR URL TO RECEIVE WEBHOOK
WEBHOOK_BASE64 = false

**Comment by lpinheirojunior** [comment]
Thank you my friend. Until then I know how to use the webhook. Actually I need a script to receive the messages, I need a webhook script, preferably me php. I am currently receiving messages using the pipedream website, but I would like to receive them directly on my vps, without the need for a third-party service.

**Comment by linkon1040z** [comment]
Create a PHP file
//To be able to receive POST JSON without Blocking
header("Access-Control-Allow-Origin: *");

//Capture and decode whatever comes from JSON
$data = json_decode(file_get_contents("php://input"), true);

//So you can loop through all JSON arrays, example:

$sender = $data['key']['remoteJid'];

Remembering that the webhook submission may have been changed, see the name of the variables and modify as needed

**Comment by lpinheirojunior** [comment]
Thanks a lot my friend.
