### ISSUE TITLE
iphone/ios only supports 2 buttons

### ISSUE THREAD

**Issue by AdrianoF0nseca** [salman0ansari/whatsapp-api-nodejs#225]
![ERRO](https://user-images.githubusercontent.com/94296617/181364290-a846a620-f59a-4d7d-a4a1-a1f59f55f550.png)
Doing some tests, I verified that putting 3 buttons and sending a message to iphone appear blank buttons, on android it arrives just right

**Comment by salman0ansari** [comment]
duplicate of #69
