### ISSUE TITLE
Taking too much time for response

### ISSUE THREAD

**Issue by drdaga** [salman0ansari/whatsapp-api-nodejs#226]
Hello recently i updated to latest version which use mongodb docker file 
updated the changes accordingly but now i have new issue whatsapp msgs are send but its taking too much of time to recieve resonse 
as in my app i have made if response not recieved in 15 secs plus 10 secs it will be marked as false due to which i get following error

"response": false,
    "message": "Response not received in 15 seconds.

**Comment by salman0ansari** [comment]
provide more information
os version
node version
docker version
device specs

**Comment by drdaga** [comment]
> provide more information os version node version docker version device specs


provide more information
os version - ubuntu 20.04
node version v18.6.0
docker version 20.10.17, build 100c701

**Comment by drdaga** [comment]
any help ??
@salman0ansari

**Comment by salman0ansari** [comment]
`can't reproduce`
sorry, it's probably an issue with docker you have to fix it yourself.
