### ISSUE TITLE
Mongoose and MongoClient

### ISSUE THREAD

**Issue by Fabrizz** [salman0ansari/whatsapp-api-nodejs#228]
First of all thanks for this great implementation!. I was looking thought the source code and noticed the different mongoose/mongodb connections to the same MongoDB instance. Is there any reason for this? Thanks

**Comment by salman0ansari** [comment]
i am dumb i was testing which package is best
Mongoose or mongodb but end up adding them both
Don't worry soon i will remove one of them.

**Comment by Fabrizz** [comment]
Thanks!
