### ISSUE TITLE
Docker container with VPN in the application

### ISSUE THREAD

**Issue by Raf1401** [salman0ansari/whatsapp-api-nodejs#229]
Raising a thread to see if anyone has already managed to do this kind of setup.

The idea is:

1 - Use the salman lib, which is the best it has.
2 - Create a container in docker with VPN running the application.
3 - Multiply these applications.

Does anyone know if this is possible to configure?

**Comment by manojsitapara** [comment]
Yes it is possible

**Comment by mariocarvalhope25** [comment]
Could you provide a Dockerfile to install an api?

**Comment by salman0ansari** [comment]
> Could you provide a Dockerfile to install an api?

its already there
