### ISSUE TITLE
Webhook Send media button problem

### ISSUE THREAD

**Issue by augusthofalqueto** [salman0ansari/whatsapp-api-nodejs#231]
I can't capture a response in the webhook. Buttons have no text or ID.

Request send media button:

{
    "id": "<id>",
    "btndata": {
        "text": "<boas-vindas>",
        "buttons": [
            {
                "type": "replyButton",
                "title": "<nossos-eventos>"
            },
            {
                "type": "replyButton",
                "title": "<reserva-lounges>"
            },
            {
                "type": "replyButton",
                "title": "<outras-duvidas>"
            }
        ],
        "footerText": "Selecione uma opção:",
        "image": "<logotipo>",
        "mediaType": "image",
        "mimeType": "image/jpeg"
    }
}

RESPONDE WEBHOOK

Response send media button:

{
  "error": false,
  "data": {
    "key": {
      "remoteJid": "[########@s.whatsapp.net](mailto:########@s.whatsapp.net)",
      "fromMe": true,
      "id": "BAE563E64940E82E"
    },
    "message": {
      "templateMessage": {
        "hydratedTemplate": {
          "imageMessage": {
            "url": "https://mmg.whatsapp.net/d/f/AmO0ufXyp-_MUQ3htAl9FUZ8zGfHwF40MXlc4mOpXZ4R.enc",
            "mimetype": "image/jpeg",
            "caption": "bv",
            "fileSha256": "m1y3dYhiiZ9OYLuPl7UD9QtNDBCbpqxTFIQULwjXLeE=",
            "fileLength": "559445",
            "mediaKey": "gDwzzL69JGTYJz915oF/A+/L4oPK0moaYgo1muInJv8=",
            "fileEncSha256": "egtjvYTBwG7ckDOp0U2KlU0ByZr20ixe6tPL0rup4CA=",
            "directPath": "/v/t62.7118-24/[23766465](tel:23766465)_164512806128754_4483977550111957716_n.enc?ccb=11-4&oh=01_AVxfNemm2P2DMkVPWDX6-U3_GYkzvqfRkmLBFsEg32bbNg&oe=[63091547](tel:63091547)",
            "mediaKeyTimestamp": "[1659058792](tel:1659058792)",
            "jpegThumbnail": "/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAWACADASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAUGBAP/xAAnEAABAwMEAQMFAAAAAAAAAAABAgMRAAQSBRMhQTEUUmEyUYGh4f/EABcBAAMBAAAAAAAAAAAAAAAAAAECBAP/xAAfEQACAgEEAwAAAAAAAAAAAAABAgARIRIiMUFCUWH/2gAMAwEAAhEDEQA/AEDe6++C2yyhWCQQk/VPYHmT8U00doyhTx2UqkQfM8mBFYmHUemtnAhpDgcAU4UZeD/RVPDC2AHG7YObO8XkggJX7SPceOPirFVUXAgBzEF/bu3LZetAt1Ly8Qds8jvn8Vgt9NcuQtpTrKMQSoKMRB7ApgdWuF2TdolwwFiCkkcdpPQ8fuhxdop1Dywy2UuKSpsCYSOZkRMkxFI9kV37jMmkgmKtLuCm4bzGTYUCEdfaqHVGDbodcYc2mXRuKaSkGSO5PdFFaIdtx0RSL+yeCSpuMylMzAFcirC3MnLJfGQ8ECiigeLknnU//9k="
          },
          "hydratedContentText": "bv",
          "hydratedFooterText": "Selecione uma opção:",
          "hydratedButtons": [
            {
              "quickReplyButton": {
                "displayText": "ne"
              }
            }
          ]
        }
      }
    },
    "messageTimestamp": "1659058792",
    "status": "PENDING"
  }
}

**Comment by linkon1040z** [comment]
This is not the capture of the webhook, for you to capture the response of the button in the webhook, first you create a file in php where it will point in your .env in WEBHOOK_URL... after that you decode the received JSON and finally get the answer of the example button:

//Decoding the JSON post
$data = json_decode(file_get_contents("php://input"), true);

//Getting the message type
$type = array_keys($data['body']['message'])[0]; 

//Getting the message from the button type response
if($type == 'templateButtonReplyMessage'){
	$msg = $dados['body']['message']['templateButtonReplyMessage']['selectedDisplayText'];

}

**Comment by augusthofalqueto** [comment]
Solved!

Thanks
