### ISSUE TITLE
Bug in Buttons and Whatsapp close automatically

### ISSUE THREAD

**Issue by augusthofalqueto** [salman0ansari/whatsapp-api-nodejs#232]
Whatsapp Sender Phone ( Cliente )

![WhatsApp Image 2022-07-29 at 23 11 33](https://user-images.githubusercontent.com/110256271/181866373-3f61be3c-2f74-425f-b70b-2e7672d7bd21.jpeg)

Whatsapp Receiver phone ( Connected in API )
![WhatsApp Image 2022-07-29 at 23 12 44](https://user-images.githubusercontent.com/110256271/181866374-41d01887-f3e7-4a2c-8a0d-012bd0423c65.jpeg)

every time I open a conversation with buttons on the receiving cell, whatsapp closes automatically

Bug in Ios and Android

**Comment by augusthofalqueto** [comment]
Video

https://drive.google.com/file/d/1z5OsFBUfPgi4vbOi_1XJAJuZZxertzLc/view?usp=sharing

**Comment by salman0ansari** [comment]
baileys bug maybe i cant do anything raise issue on Baileys repo
