### ISSUE TITLE
Nine-digit numbers in Brazil

### ISSUE THREAD

**Issue by JoaoNetoDev** [salman0ansari/whatsapp-api-nodejs#233]
Here in Brazil a few years ago a ninth digit was implemented, adding a nine to the left of the mobile lines...

I'm having problems sending API messages such that some numbers require the ninth digit and others require it to not have it...

I was trying to get around the situation by first sending a request to the /misc/getStatus route with 8 digits and seeing if error returned true or false in order to decide. But yesterday I came across one that returned false for 8 digits but requires it not to have the ninth.

When it requires it not to have the ninth digit and I send it with nine digits, a ghost chat opens (an apparently non-existent account) and that message goes nowhere

**Comment by salman0ansari** [comment]
This project is API wrapper of Baileys if you face some error or need some additional features you have raise an issue on Baileys repository. Not here

**Comment by stactus** [comment]
> Here in Brazil a few years ago a ninth digit was implemented, adding a nine to the left of the mobile lines...
> 
> I'm having problems sending API messages such that some numbers require the ninth digit and others require it to not have it...
> 
> I was trying to get around the situation by first sending a request to the /misc/getStatus route with 8 digits and seeing if error returned true or false in order to decide. But yesterday I came across one that returned false for 8 digits but requires it not to have the ninth.
> 
> When it requires it not to have the ninth digit and I send it with nine digits, a ghost chat opens (an apparently non-existent account) and that message goes nowhere

Hi João Neto,

Edit the instance.js file as below:

`
Replacing this:

    getWhatsAppId(id) {
        if (id.includes('@g.us') || id.includes('@s.whatsapp.net')) return id
        return id.includes('-') ? `${id}@g.us` : `${id}@s.whatsapp.net`
    }

Therefore:

    getWhatsAppId(id) {

        const numberDDI = id.substr(0, 2);
        const numberDDD = id.substr(2, 2);
        const numberUser = id.substr(-8, 8);

        if (numberDDI !== '55') {
            if (id.includes('@g.us') || id.includes('@s.whatsapp.net')) return id
            return id.includes('-') ? `${id}@g.us` : `${id}@s.whatsapp.net`
        }

        if (numberDDD <= 30) {
            const id = numberDDI + numberDDD + "9" + numberUser;
            if (id.includes('@g.us') || id.includes('@s.whatsapp.net')) return id
            return id.includes('-') ? `${id}@g.us` : `${id}@s.whatsapp.net`

        }

        if (numberDDD > 30) {
            const id = numberDDI + numberDDD + numberUser;
            if (id.includes('@g.us') || id.includes('@s.whatsapp.net')) return id
            return id.includes('-') ? `${id}@g.us` : `${id}@s.whatsapp.net`
        }

    }
`

It's been working fine so far, okay?

Hugs...

**Comment by wammachado** [comment]
Isso foi resolvido?? porque eu apliquei as alterações que @adrianokelvio mensionou porem não funcionou, se eu uso 6299xxxxxxx para alguns numeros ele envia mensagem para um numero q nao existte, porem se eu envio usando o mesmo numero e tirando um 9 no inicio ele vai. Isso ocorrer para alguns numeros.
