### ISSUE TITLE
NPM INSTALL ERROR "Link-preview-js"

### ISSUE THREAD

**Issue by eduardohr-muniz** [salman0ansari/whatsapp-api-nodejs#242]
![image](https://user-images.githubusercontent.com/90477293/182722478-5667cf66-e81f-4314-9f1c-676a3c1c0152.png)

Guys, I gave the git clone when I went to give the npm install this bunch of errors, does anyone know how to solve it?

**Comment by salman0ansari** [comment]
use yarn
