### ISSUE TITLE
Whatsapp Update (doesn't work anymore)

### ISSUE THREAD

**Issue by thiagomagamoc** [salman0ansari/whatsapp-api-nodejs#25]
After official whatsapp update, when reading QRCode does not work

**Comment by salman0ansari** [comment]
Legacy or MultiDevice?

**Comment by thiagomagamoc** [comment]
The latest WhatsApp update made it Official.
That is, there is no longer the "Multi Device (Beta)" button
Now officially everyone is MD

**Comment by salman0ansari** [comment]
> The latest WhatsApp update made it Official. That is, there is no longer the "Multi Device (Beta)" button Now officially everyone is MD

Switch to [MultiDevice](https://github.com/salman0ansari/whatsapp-api-nodejs/tree/MultiDevice) branch

**Comment by thiagomagamoc** [comment]
I didn't understand how I can download and merge the MD branch with Main branch

**Comment by manojsitapara** [comment]
Both branches are different because main branch uses Baileys v3.0 & MD branch uses Baileys v4.0 
(NOTE: MD Branch is still in WIP by @salman0ansari )

**Comment by thiagomagamoc** [comment]
Okay, but could you tell me if it's already working for testing?
I start the server (node serve.js)
I go in the browser and try to access: http://127.0.0.1:3333/init
And I get the following error: Cannot GET /init

**Comment by manojsitapara** [comment]
Please try following
[http://localhost:3333/instance/init](http://localhost:3333/instance/init)

**Comment by thiagomagamoc** [comment]
> Please try following http://localhost:3333/instance/init

Excelent! Work fine

When sending a POST to (http://127.0.0.1:3333/message/text?key=6a5e09fa-52e7-454c-8e65-d5e90449e5d4)
With the parameters: id and message
I'm getting the following error:
{
     "error": true,
     "code": 500,
     "message": "Error: no account exists"
}

**Comment by manojsitapara** [comment]
Please make sure you are passing the correct Id. This error indicates that your id is either not registered on WhatsApp or an invalid Id.

For the phone number, you need to pass 911234567890 

You can easily find the root case of the issue if you read the code.

**Comment by thiagomagamoc** [comment]
> 

Yes Bro, is correct, look

![image](https://user-images.githubusercontent.com/64119713/155829824-e2c090bd-3eac-4101-89b4-0e4833c63a5c.png)

**Comment by salman0ansari** [comment]
> > 
> 
> Yes Bro, is correct, look
> 
> ![image](https://user-images.githubusercontent.com/64119713/155829824-e2c090bd-3eac-4101-89b4-0e4833c63a5c.png)

Send data in query

**Comment by thiagomagamoc** [comment]
Congratulations on the work!
This works great for me
