### ISSUE TITLE
Crashing while sending a text message

### ISSUE THREAD

**Issue by tinyCoder32** [salman0ansari/whatsapp-api-nodejs#250]
`2022-08-07T10:34:30.615681+00:00 app[web.1]: {"level":50,"time":1659868470615,"pid":22,"hostname":"e3430f78-22c3-429c-b839-81e1281277a5","err":{"type":"TypeError","message":"Cannot set properties of undefined (setting 'creation')","stack":"TypeError: Cannot set properties of undefined (setting 'creation')\n    at WhatsAppInstance.updateDbGroupsParticipants (/app/src/api/class/instance.js:500:54)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async EventEmitter.<anonymous> (/app/src/api/class/instance.js:145:13)"},"msg":"Cannot set properties of undefined (setting 'creation')"}
`

**Comment by salman0ansari** [comment]
How are you sending the message?

**Comment by tinyCoder32** [comment]
A normal text message sent via postman.

**Comment by salman0ansari** [comment]
Does #261 fix this too?
@luispimenta

**Comment by luispimenta** [comment]
Yes

**Comment by tinyCoder32** [comment]
This is happening again: 

<img width="1188" alt="image" src="https://user-images.githubusercontent.com/17817239/189194205-cd5c11d2-cc79-454c-9966-fedc0872823b.png">

Loggin in from WhatsApp Business (beta)
