### ISSUE TITLE
 Message only appears on WhatsApp Web

### ISSUE THREAD

**Issue by MMSILVA1971** [salman0ansari/whatsapp-api-nodejs#256]
I'm testing sending with the URL option, but the message only appears on WhatsApp Web. Is there a characteristic for this type of send?

Best Regards!

**Comment by salman0ansari** [comment]
fixed in the latest commit https://github.com/salman0ansari/whatsapp-api-nodejs/commit/1b577d547bb46598aaf12e6fbfe434a2ff44c30d
