### ISSUE TITLE
error before scan qr code

### ISSUE THREAD

**Issue by Tecnicasoft** [salman0ansari/whatsapp-api-nodejs#259]
"err":{"type":"TypeError","message":"Cannot set properties of undefined (setting 'creation')","stack":"TypeError: Cannot set properties of undefined (setting 'creation')\n    at WhatsAppInstance.updateDbGroupsParticipants (C:\\zap\\src\\api\\class\\instance.js:505:54)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async EventEmitter.<anonymous> (C:\\zap\\src\\api\\class\\instance.js:150:13)"},"msg":"Cannot set properties of undefined (setting 'creation')"}

![Screenshot 2022-08-09 201944](https://user-images.githubusercontent.com/16633547/183778121-0f45d278-0a85-4205-9dc5-5e33e4c0d585.png)

I commented out the code line and it worked
![Screenshot 2022-08-09 204611](https://user-images.githubusercontent.com/16633547/183780639-0ada2607-42d3-4c79-8816-0e70e13d42c8.png)

**Comment by salman0ansari** [comment]
@luispimenta

**Comment by luispimenta** [comment]
@Tecnicasoft Here everything works perfectly, I raised this PR #261 with try catch...
