### ISSUE TITLE
[MD] Link Preview not generating

### ISSUE THREAD

**Issue by manojsitapara** [salman0ansari/whatsapp-api-nodejs#26]
In SendMessage endpoint, if the message parameter contains a link, it is not generating link preview in the older version it was generating automatically. I think there are some changes in Baily v4.0

**Comment by salman0ansari** [comment]
but it Baileys docs says this
`// will detect links & generate a link preview automatically (default true)`
`detectLinks: true`

**Comment by manojsitapara** [comment]
Yes but it is not generating, I think it need to use `externalAdReply`

**Comment by salman0ansari** [comment]
Whatsapp web MD dont have link preview yet
