### ISSUE TITLE
Mongodb not save webhookUrl restoring sessions

### ISSUE THREAD

**Issue by adrianokelvio** [salman0ansari/whatsapp-api-nodejs#260]
when api restarts, webhook restores .env configuration

It would be interesting to save the individual webhook Url for each instance in the database

**Comment by leoteixeira2016** [comment]
You creating the instance with the method
GET 192.168.40.23:3333/instance/init?key=LEO&webhook=True&webhookUrl=http://192.168.40.249/Webhook/
you can pass the parameters for each one

but also with a single webhook you can manage, I'm doing it this way

**Comment by adrianokelvio** [comment]
Question and each instance have its Webhook

**Comment by aspiretony** [comment]
is there any way to pass the session through the main webhook so you know who it was sent from than one webhook for each session
