### ISSUE TITLE
MongoDB Authentication

### ISSUE THREAD

**Issue by giordy84** [salman0ansari/whatsapp-api-nodejs#268]
Good morning,
how is it possible to set MONGODB's username and password for authentication in the enviroment file?

Installing mongodb without a password is not secure.

I have tried with:
MONGODB_USERNAME
MONGODB_PASSWORD

but it does not work

thanks

**Comment by salman0ansari** [comment]
> Good morning, how is it possible to set MONGODB's username and password for authentication in the enviroment file?
> 
> Installing mongodb without a password is not secure.
> 
> I have tried with: MONGODB_USERNAME MONGODB_PASSWORD
> 
> but it does not work
> 
> thanks

you can use username password like this
mongodb://`ADMIN`:`PASSWORD`@localhost:27017/db
