### ISSUE TITLE
[MD] getWhatsAppId() condition need to change

### ISSUE THREAD

**Issue by manojsitapara** [salman0ansari/whatsapp-api-nodejs#27]
In getWhatsAppId(), I think it is not necessary that group id contain "-" always because when I create a new group today for testing, it has this id without "-".  

> 120658842795023778@g.us

in such case the following method will not work
```
 getWhatsAppId(id) {
        return id?.includes('-') ? `${id}@g.us` : `${id}@s.whatsapp.net`
    }
```

instead we can replace it with the following code

```
 getWhatsAppId(id) {
        return id?.includes('@g.us') ? `${id}` : `${id}@s.whatsapp.net`;
    }
```

Correct me, If I am wrong

**Comment by salman0ansari** [comment]
> In getWhatsAppId(), I think it is not necessary that group id contain "-" always because when I create a new group today for testing, it has this id without "-".
> 
> > [120658842795023778@g.us](mailto:120658842795023778@g.us)
> 
> in such case the following method will not work
> 
> ```
>  getWhatsAppId(id) {
>         return id?.includes('-') ? `${id}@g.us` : `${id}@s.whatsapp.net`
>     }
> ```
> 
> instead we can replace it with the following code
> 
> ```
>  getWhatsAppId(id) {
>         return id?.includes('@g.us') ? `${id}` : `${id}@s.whatsapp.net`;
>     }
> ```
> 
> Correct me, If I am wrong

Good catch
