### ISSUE TITLE
stop in Docker

### ISSUE THREAD

**Issue by wisnubaldas** [salman0ansari/whatsapp-api-nodejs#28]
container stops after some time there is an error too many requests
![Jepretan Layar 2022-02-27 pukul 15 11 11](https://user-images.githubusercontent.com/10908214/155874387-4a75c82a-b22a-4050-9b60-30786e0dbd02.png)

**Comment by manojsitapara** [comment]
please scan qr as soon as possible

**Comment by salman0ansari** [comment]
duplicate of (#19)
