### ISSUE TITLE
Error: EPERM: operation not permitted, unlink

### ISSUE THREAD

**Issue by lsteinert** [salman0ansari/whatsapp-api-nodejs#280]
I'm using an API and triggering a message with an image, but it flashes every time it runs, time this error appears, time sends it normally. I've already reinstalled Node.js, I've noticed the downgrade of the NPM version but nothing has worked. Out of 30 sending attempts, only 10 are consummated, the others have this error.

**Comment by salman0ansari** [comment]
run npm as adminstrator

**Comment by lsteinert** [comment]
> run npm/node as adminstrator

is already running as administrator

**Comment by lsteinert** [comment]
this error occurs when the file is of GIF extension, when it is JPEG it does not occur.
