### ISSUE TITLE
Message with buttons does not send

### ISSUE THREAD

**Issue by robinhodemorais** [salman0ansari/whatsapp-api-nodejs#281]
Hello good afternoon, I'm trying to send a message with buttons to a number here in Brazil with the DDD 44 and it doesn't go, the same message to my number which is DDD 21 goes, but I could see that when I received the message from this number 44 it doesn't show the ninth digit in whatsapp web, whatsapp mobile app (android) and in the api, I tried to send with the ninth digit or without, but it doesn't go for nothing and strangely I don't have any error return in the API, which can to be ?

`{
    "error": false,
    "data": {
        "key": {
            "remoteJid": "554499235699@s.whatsapp.net",
            "fromMe": true,
            "id": "BAE55FB246F211CB"
        },
        "message": {
            "templateMessage": {
                "hydratedTemplate": {
                    "hydratedContentText": "title Head",
                    "hydratedFooterText": "title footer",
                    "hydratedButtons": [
                        {
                            "quickReplyButton": {
                                "displayText": "Reply this text (REPLY)"
                            }
                        },
                        {
                            "urlButton": {
                                "displayText": "Click me (URL)",
                                "url": "https://google.com"
                            }
                        },
                        {
                            "callButton": {
                                "displayText": "Click to call (CALL)",
                                "phoneNumber": "5521968414332"
                            }
                        }
                    ]
                }
            }
        },
        "messageTimestamp": "1660679376",
        "status": "PENDING"
    }
}`

**Comment by atrikx** [comment]
its a bug from Baileys library, they fixed it temporally on a new patch

**Comment by sairmali** [comment]
@atrikx how we can fix this ? please give any solutions

**Comment by salman0ansari** [comment]
fixed in latest commit https://github.com/salman0ansari/whatsapp-api-nodejs/commit/1b577d547bb46598aaf12e6fbfe434a2ff44c30d
