### ISSUE TITLE
Send image with PHP code

### ISSUE THREAD

**Issue by lpinheirojunior** [salman0ansari/whatsapp-api-nodejs#282]
I can upload image using postman.com , but using PHP Curl code provided by Postman I can not .
 If anyone can help, this is the code I have.

<?php

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => 'http://my-ip:3333/message/image?id=55919999888&caption=&key=luis',
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'POST',
  CURLOPT_POSTFIELDS => array('file'=> new CURLFILE('img/app-agenda.png'),'id' => '559181516417','caption' => 'texto-oi'),
));

$response = curl_exec($curl);

curl_close($curl);
echo $response;

I've tried a little bit of everything, but I can't send the image.

**Comment by AdrianoF0nseca** [comment]
In my tests here, it also gave an error, so I did the following:

I put the image in the same directory as the php file
<?php

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => 'http://localhost:3333/message/image?key=5511962924430',
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'POST',
  CURLOPT_POSTFIELDS => array('file'=> new CURLFILE('siapes.png'),'id' => '558599694849','caption' => .............

**Comment by lpinheirojunior** [comment]
When sent by postman.com it arrives on the cell phone.

**Comment by lpinheirojunior** [comment]
I think in postman.com it creates a temporary directory

**Comment by AdrianoF0nseca** [comment]
> When sent by postman.com it arrives on the cell phone.

that's right, with me the same thing

**Comment by salman0ansari** [comment]
> I can upload image using postman.com , but using PHP Curl code provided by Postman I can not . If anyone can help, this is the code I have.
> 
> 'http://my-ip:3333/message/image?id=55919999888&caption=&key=luis', CURLOPT_RETURNTRANSFER => true, CURLOPT_ENCODING => '', CURLOPT_MAXREDIRS => 10, CURLOPT_TIMEOUT => 0, CURLOPT_FOLLOWLOCATION => true, CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1, CURLOPT_CUSTOMREQUEST => 'POST', CURLOPT_POSTFIELDS => array('file'=> new CURLFILE('img/app-agenda.png'),'id' => '559181516417','caption' => 'texto-oi'), )); $response = curl_exec($curl); curl_close($curl); echo $response; I've tried a little bit of everything, but I can't send the image.

Give full path of image

**Comment by lpinheirojunior** [comment]
I hosted this PHP code of mine on a website. And I'm getting the image in a site folder. Could you give me an example of how to get this image?
For me it's working but only to send by whatsapp web.

**Comment by MarcioMoura2022** [comment]
I'm also going through the same problem, in postman it works 100% now in PHP it only sends to whatsapp web, it's not enough for mobile .....

**Comment by sairmali** [comment]
@MarcioMoura2022 send me your code

**Comment by MarcioMoura2022** [comment]
@sairmali , Hello, thank you very much for your attention, below is my code:

$caminho_imagem = $_SERVER['DOCUMENT_ROOT'] . $this->Ini->path_imagens . '/img_campanha/' . $var_imagem;

curl_setopt_array($curl, array(
			CURLOPT_URL => [url_api_whatsapp] . 'message/image?key='.$var_key_sender,
			CURLOPT_RETURNTRANSFER => true,
			CURLOPT_ENCODING => '',
			CURLOPT_MAXREDIRS => 10,
			CURLOPT_TIMEOUT => 0,
			CURLOPT_FOLLOWLOCATION => true,
			CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
			CURLOPT_CUSTOMREQUEST => 'POST',
			CURLOPT_POSTFIELDS => array('file'=> new CURLFILE($caminho_imagem),'id' => $var_telefone,'caption' => $var_titulo_mensagem),));

forgive me my english, i'm using the GOOGLE translator.

**Comment by sairmali** [comment]
CURLOPT_POSTFIELDS => array('file'=> new CURLFILE($caminho_imagem,'image/png'),'id' => $var_telefone,'caption' => $var_titulo_mensagem),));

**Comment by MarcioMoura2022** [comment]
@sairmali show I will test it, thank you very much!!!

**Comment by lpinheirojunior** [comment]
@MarcioMoura2022 Marcio, friend, I think you are Brazilian like me. Following your script and @sairmali's guidelines, I made these modifications:
$folder_image = "/sender/";
$name_image = "agenda.png;
$caminho = $_SERVER['DOCUMENT_ROOT'].$folder_image.$name_image;

CURLOPT_POSTFIELDS => array('file'=> new CURLFile($caminho,'image/png'),'id' => '5511123456789','caption' => 'Hello'),
));
It worked perfectly, thanks for the help friend.

**Comment by MarcioMoura2022** [comment]
@lpinheirojunior , Brazuca Detected, sim sou brasileiro, comigo também funcionou 100% era só este detalhe mesmo, impressionante como um detalhe arrebenta a gente, hehehehehe..... estava à duas semanas quebrando a cabeça e nada de funcionar, a imagem só ia para o whatsapp web, para o celular nem com reza braba....

Answer in english:
Brazuca Detected, yes I'm Brazilian, it also worked 100% for me it was just this detail, impressive how a detail blows us away, hehehehehe..... I was racking my brains for two weeks and nothing worked, the image just went to the whatsapp web, for mobile not even with angry prayers....

@sairmali , dear friend, very very tnks, working perfect!!!
