### ISSUE TITLE
How can I use a proxy for a client?

### ISSUE THREAD

**Issue by catthecreator** [salman0ansari/whatsapp-api-nodejs#292]
I have more than 100 clients expected.

If they all work from the same ip, there is a high probability that WhatsApp will ban them for suspicious activity.

Is there a solution to this problem?

**Comment by salman0ansari** [comment]
docker?

**Comment by catthecreator** [comment]
can I get more details?

**Comment by salman0ansari** [comment]
> can I get more details?

no

**Comment by catthecreator** [comment]
why? :(

**Comment by salman0ansari** [comment]
> why? :(

https://stackoverflow.com/questions/47827496/how-to-configure-docker-container-proxy

**Comment by catthecreator** [comment]
Thanks, but that's not exactly what I was asking.
Thus, a separate docker container will have to be made for each user.

This is a bit contrary to the concept of "multi device support".

It would be much more convenient if at the time of initialization of the project (localhost:3333/instance/init)
it would be possible to assign a proxy to the instance.

Is it possible to finalize this solution?
Can you do it? If so, how much will it cost?

**Comment by salman0ansari** [comment]
> Thanks, but that's not exactly what I was asking. Thus, a separate docker container will have to be made for each user.
> 
> This is a bit contrary to the concept of "multi device support".
> 
> It would be much more convenient if at the time of initialization of the project (localhost:3333/instance/init) it would be possible to assign a proxy to the instance.
> 
> Is it possible to finalize this solution? Can you do it? If so, how much will it cost?

I can do it but people will misuse it to spam

**Comment by salman0ansari** [comment]
> People can still use this solution to send spam by running multiple containers.
> 
> But for SaaS platforms, on the contrary, it is problematic to make a container for each client.

msg me on [telegram](https://t.me/salman0ansari)
