### ISSUE TITLE
How to update authentication keys after sending and receiving messages?

### ISSUE THREAD

**Issue by Sulivan1999** [salman0ansari/whatsapp-api-nodejs#30]
Hey!
I did some analysis and noticed that the session authentication keys, which are saved in JSON in the "Instances" folder, are updated when the qr-code is read.

However, the official Baileys documentation says: "When a message is received/sent from Session Authentication, the authentication keys will be included. Whenever this happens you should save as Not doing this will prevent your messages from reaching the recipient and other key differences".

[Saving & Restoring Sessions](https://github.com/adiwajshing/Baileys#saving--restoring-sessions)

I identified that WhatsApp is "stuck" after sending a message with the cell phone offline, and after that I can no longer connect to the API, I believe it is due to this problem with authentication keys.

Can this be implemented in the API or how can I make this modification?

**Comment by salman0ansari** [comment]
I thought `useSingleFileAuthState` function automatically takes care of that

**Comment by Sulivan1999** [comment]
> Eu pensei que `useSingleFileAuthState`a função automaticamente cuida disso

The documentation says yes! But in reality the authentication keys are not being changed. I don't really know how I can improve this, and so I would like to know if it can be implemented/improved in the API, as I'm having some problems with restoring connections and I believe this may be the way to go.

**Comment by salman0ansari** [comment]
> > Eu pensei que `useSingleFileAuthState`a função automaticamente cuida disso
> 
> The documentation says yes! But in reality the authentication keys are not being changed. I don't really know how I can improve this, and so I would like to know if it can be implemented/improved in the API, as I'm having some problems with restoring connections and I believe this may be the way to go.

I am not changing any internal part of Baileys so where does this issue coming from?? Baileys lib itself?
