### ISSUE TITLE
Send Massage not working after Restore Session.

### ISSUE THREAD

**Issue by pagi-ronak** [salman0ansari/whatsapp-api-nodejs#302]
once we restore session then try to send text massage , its stuck on send text API and other sending API , its not responding. 
![Screenshot 2022-08-26 100441](https://user-images.githubusercontent.com/76847536/186822883-8c0a6c17-101f-4abd-a5ea-3193585c897c.png)

==============
![image](https://user-images.githubusercontent.com/76847536/186823835-2b65d929-6da6-4ce1-8dd0-7049008e6e1d.png)

Help if possible , I have been seeing this problem for a long time.

**Comment by salman0ansari** [comment]
> once we restore session then try to send text massage , its stuck on send text API and other sending API , its not responding. ![Screenshot 2022-08-26 100441](https://user-images.githubusercontent.com/76847536/186822883-8c0a6c17-101f-4abd-a5ea-3193585c897c.png)
> 
> ============== ![image](https://user-images.githubusercontent.com/76847536/186823835-2b65d929-6da6-4ce1-8dd0-7049008e6e1d.png)
> 
> Help if possible , I have been seeing this problem for a long time.

Show full logs why server closed

**Comment by pagi-ronak** [comment]
> 1st i restore 
> call send API
> Showing this after 5-10 minutes 

![logs3](https://user-images.githubusercontent.com/76847536/186832220-bca942d4-35e9-462c-998f-b1f597ac2a64.png)

> after 1006 , there is no response continue loading .

> Then i click on cancel request , then showing this

  
![logs4](https://user-images.githubusercontent.com/76847536/186832534-7ece272d-e1e7-4160-9425-b9345a468ad5.png)

**Comment by salman0ansari** [comment]
> > 1st i restore
> > call send API
> > Showing this after 5-10 minutes
> 
> ![logs3](https://user-images.githubusercontent.com/76847536/186832220-bca942d4-35e9-462c-998f-b1f597ac2a64.png)
> 
> > after 1006 , there is no response continue loading .
> 
> > Then i click on cancel request , then showing this
> 
> ![logs4](https://user-images.githubusercontent.com/76847536/186832534-7ece272d-e1e7-4160-9425-b9345a468ad5.png)

Change log level to debug

**Comment by pagi-ronak** [comment]
After Change log level to debug

![image](https://user-images.githubusercontent.com/76847536/186835296-2939b518-fc05-4dcb-a15a-8c881ffb2c4a.png)

**Comment by salman0ansari** [comment]
> After Change log level to debug
> 
> ![image](https://user-images.githubusercontent.com/76847536/186835296-2939b518-fc05-4dcb-a15a-8c881ffb2c4a.png)

can you try logout this instance? and create a new Instance again

**Comment by pagi-ronak** [comment]
Yes , i tried all thing ... LOGOUT - LOGIN , REMOVE - ADD ,  even i tried all possible things in past 2 month. then i raised this issue. if you comfortable then i can show it in anydesk also.

**Comment by salman0ansari** [comment]
we can continue discussion here #251

**Comment by sairmali** [comment]
@pagi-ronak please tell me your problem
