### ISSUE TITLE
Template message not send

### ISSUE THREAD

**Issue by AshSoftTech** [salman0ansari/whatsapp-api-nodejs#303]
when I send template messages to a particular phone number the message does not receive but that message receive in a connected instance how is this possible

**Comment by salman0ansari** [comment]
iOS?

**Comment by reisdiegos85** [comment]
Exactly, sending message with tenplate, not receiving on mobile devices.

**Comment by AshSoftTech** [comment]
android device also

**Comment by augustofcs** [comment]
How send simple buttons?
