### ISSUE TITLE
Tutorial for Webhook 

### ISSUE THREAD

**Issue by reisdiegos85** [salman0ansari/whatsapp-api-nodejs#304]
Does anyone have a tutorial explaining how to create the webhook? I searched and found nothing!

Please

**Comment by salman0ansari** [comment]
there you go
```js
app.post('/webhook' , (req, res) => {
    console.log( 'received webhook', req.body );
    res.send("ok" );
}
```

**Comment by reisdiegos85** [comment]
> ```js
> app.post('/webhook' , (req, res) => {
>     console.log( 'received webhook', req.body );
>     res.send("ok" );
> }
> ```

Where do I put this information? Unfortunately my knowledge is basic

**Comment by salman0ansari** [comment]
this is not a tutorial forum. your knowledge is basic this isn't my problem 
a simple youtube/google search will give you millions of results.
[how to use webhook](https://letmegooglethat.com/?q=what+is+webhook+and+how+to+consume+it)

**Comment by reisdiegos85** [comment]
> 

Thank you anyway!

**Comment by jeankassio** [comment]
> this is not a tutorial forum. your knowledge is basic this isn't my problem a simple youtube/google search will give you millions of results. [how to use webhook](https://letmegooglethat.com/?q=what+is+webhook+and+how+to+consume+it)

What a great education answering someone who is looking to use your code, congrats, you're going to be a great programmer that way [irony]
Your project has clear flaws regarding the Webhook documentation, just look at the amount of people complaining about it, you should be more concerned when you post code on Github.

**Comment by salman0ansari** [comment]
> > this is not a tutorial forum. your knowledge is basic this isn't my problem a simple youtube/google search will give you millions of results. [how to use webhook](https://letmegooglethat.com/?q=what+is+webhook+and+how+to+consume+it)
> 
> What a great education answering someone who is looking to use your code, congrats, you're going to be a great programmer that way [irony] Your project has clear flaws regarding the Webhook documentation, just look at the amount of people complaining about it, you should be more concerned when you post code on Github.

Thanks for valuable comment unfortunately this project isn't beginner friendly if you think something is missing from documentation or code happily open a PR (thats how open source works) dont complain.

**Comment by jeankassio** [comment]
The better documented a project is, the fewer issues it will have.
Now I'll do the same as all the other programmers who are here on this project and I'll waste my time because this doesn't have a well-done documentation.

**Comment by salman0ansari** [comment]
thanks for valuable comments.
