### ISSUE TITLE
[BUG] onWhatsApp

### ISSUE THREAD

**Issue by Zarinia** [salman0ansari/whatsapp-api-nodejs#305]
```javascript
async verifyId(id) {
		if (id.includes('@g.us')) {
			return true;
		}
		
		const [result] = await this.instance.sock?.onWhatsApp(id);
		if (result?.exists) {
			return true;
		} else {
			logger({
				msg: `Receiver not exists`,
				error: {},
				data: this.key
			}).warning();
			return false;
		}
	}
 ```

The number I tried was not registered in WhatsApp, but this function returns true

**Comment by salman0ansari** [comment]
and what can i do about it?

**Comment by Zarinia** [comment]
When there is no number, a false value should be returned, but the true value is still returned. This is a bug from the main library. Can you suggest a solution?

**Comment by salman0ansari** [comment]
> When there is no number, a false value should be returned, but the true value is still returned. This is a bug from the main library. Can you suggest a solution?

Well i am not a maintainer of Baileys i can't do anything sorry

**Comment by Zarinia** [comment]
Thank you very much, I hope the problem will be solved in the future
