### ISSUE TITLE
Its possible send simple buttons? Not template?

### ISSUE THREAD

**Issue by augustofcs** [salman0ansari/whatsapp-api-nodejs#308]
Is it possible to send simple buttons message? those that are one under the other, and that have a title in the message? Because the template buttons are giving problem on iOS.

**Comment by salman0ansari** [comment]
wdym by simple buttons? Can you any image of it?

**Comment by Raf1401** [comment]
Repply button...

**Comment by Raf1401** [comment]
Are the button functions working normally for whoever is using it? Does it work for both Android and iOS?

**Comment by augustofcs** [comment]
> wdym by simple buttons? Can you post any image of it?

reply buttons

**Comment by augustofcs** [comment]
Legacy buttons (reply buttons) has tittle: 
![image](https://user-images.githubusercontent.com/70924846/188498477-d6051f4a-8ce5-40a4-b0c2-d69fb79b97c8.png)

Template buttons, using only reply functions, dont have tittle option:
![image](https://user-images.githubusercontent.com/70924846/188498515-e71ee364-67e0-4e76-bf20-8adc307a43db.png)

**Comment by Raf1401** [comment]
> 

But both the template button and the legacy button are not functional here. Neither Android nor iOS. Only whatsapp web. Does it work for you?

**Comment by augustofcs** [comment]
> > 
> 
> But both the template button and the legacy button are not functional here. Neither Android nor iOS. Only whatsapp web. Does it work for you?

legacy button is working android and web.

**Comment by worksahiljain** [comment]
Hi Did you get any solution for it? Even I am struggling with sending Simple reply buttons on ios.

**Comment by KevinEduardo** [comment]
I also wanna know

**Comment by dev-pipeor** [comment]
Hi, I have problem sending replyButton. Other buttons work normally, just replyButton not.

![Screenshot 2022-11-28 at 2 33 12 PM](https://user-images.githubusercontent.com/103116770/204343453-bc78ee17-9b7b-4ea6-88c0-528bd5238fc9.png)
