### ISSUE TITLE
audio decrypter php question

### ISSUE THREAD

**Issue by jeancsferreira** [salman0ansari/whatsapp-api-nodejs#310]
sorry for the inconvenience but i already searched git for solutions to decrypt audio and got stuck in reverse sequence...

Has anyone managed to convert .enc to .ogg?

Json:{"type":"message","body":{"key":{"remoteJid":"553298400000@s.whatsapp.net","fromMe":false,"id":"3A10410B554F2D293F75"},"messageTimestamp":1661966271,"pushName":"Jean Ferreira","message": {"audioMessage":{"url":"https://mmg.whatsapp.net/d/f/AmQQSatFoKLWH5L8O2oF5XPlTVY8ZNxTlOYFkUr0LNbS.enc", "mimetype":"audio/ogg; codecs=opus", "fileSha256":"E5T04I0ec7UCWww8uQn0ZehXpgznhzp8Q2SnLM4PBHo=", "fileLength":"16793","segundos":8,"ptt":true,"mediaKey": "utawnakTLBF5kWHkJSbUAHVRlob4wdAaCKNWy2v4Ncc=","fileEncSha256": "hzFY51Y4c4Q8BZKiuxaNdQZ1qjHbs0xJnNu8C3zQ8qY=", "directPath":"/v/t62.7117-24/13711756_604669164524710_3698698617273595116_n.ogg? ccb=11-4&oh=01_AVzEb0hU2GPnb_r4rJ2myv0ayfKdbXEoFZOOnBgHtzNGFw&oe=63369B7A", "mediaKeyTimestamp":"1661966260","streamingSidecar":"bG+kbmvLiyp51A==","waveform":"AAAAAAAAAAAAABCwgEAgAAAAAABwwLDQoLDAgHBwUHCAwLBwMBAQAAAAAAAQkKDg8MCAoIDQwLCQUCAQ=="},"messageContext

arquivo.php
<?
$file                      = file_get_contents('https://mmg.whatsapp.net/v/t62.7117-24/13711756_604669164524710_3698698617273595116_n.enc? ccb=11-4&oh=01_AVzEb0hU2GPnb_r4rJ2myv0ayfKdbXEoFZOOnBgHtzNGFw&oe=63369B7A');

$encryption_key = "f2dee754702479f319093e22258be0972437d789fa1925e20ea679ba88fcab04"; 
$iv                        = "utawnakTLBF5kWHkJSbUAHVRlob4wdAaCKNWy2v4Ncc=";
$encrypted         = openssl_encrypt($file, 'AES-256-CBC', $encryption_key, 0, $iv);
$decrypted         = openssl_decrypt($encrypted, 'AES-256-CBC', $encryption_key, 0, $iv);
$error                  = openssl_error_string();

$arquivo              = "audio.ogg";	  
$fp                       = fopen($arquivo, "r");  
fwrite($fp, $decrypted); 
fclose($fp);

**Comment by JoaoNetoDev** [comment]
![Screenshot_20220831-182310-681](https://user-images.githubusercontent.com/68018643/187787597-6c4d632a-1c8b-4cf8-8b9e-c9f20afccb91.png)
Change for true

**Comment by JoaoNetoDev** [comment]
> ![Screenshot_20220831-182310-681](https://user-images.githubusercontent.com/68018643/187787597-6c4d632a-1c8b-4cf8-8b9e-c9f20afccb91.png) Change for true

will arrive in another parameter the file in base64

**Comment by jeancsferreira** [comment]
Thanks, I'll try and send feedback
