### ISSUE TITLE
MediaButton and Button not sent message

### ISSUE THREAD

**Issue by sairmali** [salman0ansari/whatsapp-api-nodejs#316]
MediaButton and Button not sent message when i sent message throw this api so, they are show showing message sent but it is not delivered

anyone give me any solution ..

**Comment by sairmali** [comment]
@salman0ansari please give me any link if you have any solution

**Comment by sairmali** [comment]
@salman0ansari any update on this ?

**Comment by divieirasilva** [comment]
having this problem too, anyone working on this?

**Comment by sairmali** [comment]
i don't know why everyone is silent on this topic

**Comment by pauloanalista** [comment]
Has anyone tried this solution?
https://github.com/adiwajshing/Baileys/issues/2132

**Comment by sairmali** [comment]
@pauloanalista  Thanks for you given solution ! but how we can implement this ?

**Comment by pauloanalista** [comment]
I'd like to fork, tweak and send PR, but I'm out of time.

**Comment by pauloanalista** [comment]
This problem is not in this api.

The error is from the baileys library

https://github.com/adiwajshing/Baileys/issues/2132

**Comment by sairmali** [comment]
no @pauloanalista  my question is how can i add this feature in this api or library ? what is name of file to add this feature

**Comment by sairmali** [comment]
@pauloanalista ?

**Comment by pauloanalista** [comment]
In the Baileys library, go to the archive
message.js 

![image](https://user-images.githubusercontent.com/6010161/197769696-52008e8f-c0eb-4d9a-817f-da3e9d90c85e.png)

uncomment this line
![image](https://user-images.githubusercontent.com/6010161/197769736-4151f77c-642f-4891-b0bc-b1f36ecc9167.png)

**Comment by sairmali** [comment]
@pauloanalista thanks you so much really !! it is working perfectly

**Comment by sairmali** [comment]
@pauloanalista hello,

i am again facing this issue
