### ISSUE TITLE
Crashing error after initializing

### ISSUE THREAD

**Issue by tinyCoder32** [salman0ansari/whatsapp-api-nodejs#320]
I get this when I initialize an instance that is already active.

`{"level":50,"time":1662837474317,"pid":22,"hostname":"4dec5e4c-b299-4856-bdfc-60d5eb891e07","err":{"type":"TypeError","message":"Cannot read properties of null (reading 'chat')","stack":"TypeError: Cannot read properties of null (reading 'chat')\n    at WhatsAppInstance.getChat (/app/src/api/class/instance.js:1078:32)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async WhatsAppInstance.SendWebhook (/app/src/api/class/instance.js:113:24)\n    at async EventEmitter.<anonymous> (/app/src/api/class/instance.js:506:17)"},"msg":"Cannot read properties of null (reading 'chat')"}`

**Comment by tinyCoder32** [comment]
This keeps happening all the time.

**Comment by sairmali** [comment]
@tinyCoder32 use are using this for bulk messaging ?

**Comment by tinyCoder32** [comment]
No, just sending a verification code from a login page.

**Comment by sairmali** [comment]
your npm and node version ?

**Comment by tinyCoder32** [comment]
Latest, I'm deploying to Heroku.
