### ISSUE TITLE
Shared Hosting

### ISSUE THREAD

**Issue by rizkihardinas** [salman0ansari/whatsapp-api-nodejs#33]
Is tested on shared hosting ?

**Comment by salman0ansari** [comment]
> Is tested on shared hosting ?

No, let me know if work for you.

**Comment by thiagomagamoc** [comment]
> Is tested on shared hosting ?

I try in VPS. Work fine!

**Comment by dasmond1** [comment]
> > Is tested on shared hosting ?
> 
> No, let me know if work for you.

Work For Me. In Indonesia, i use hosting from domainesia.com with nodejs installer feature

**Comment by rizkihardinas** [comment]
> > > Is tested on shared hosting ?
> > 
> > 
> > No, let me know if work for you.
> 
> Work For Me. In Indonesia, i use hosting from domainesia.com with nodejs installer feature

on rumahweb
my code getting error when install bro

**Comment by dasmond1** [comment]
> > > > Is tested on shared hosting ?
> > > 
> > > 
> > > No, let me know if work for you.
> > 
> > 
> > Work For Me. In Indonesia, i use hosting from domainesia.com with nodejs installer feature
> 
> on rumahweb my code getting error when install bro

can you give me a screenshoot ?
may be i can help

**Comment by dasmond1** [comment]
> > > > Is tested on shared hosting ?
> > > 
> > > 
> > > No, let me know if work for you.
> > 
> > 
> > Work For Me. In Indonesia, i use hosting from domainesia.com with nodejs installer feature
> 
> on rumahweb my code getting error when install bro

i will give you a new PR.. with some tweak to work with shared hosting. stay tune and wait for new update

**Comment by vesvello** [comment]
Can I get help with shared hosting too?
