### ISSUE TITLE
Unable to set profile picture of instances

### ISSUE THREAD

**Issue by sahiljain379** [salman0ansari/whatsapp-api-nodejs#339]
Can anyone help me please? 
![IMG-20220929-WA0005](https://user-images.githubusercontent.com/64308364/193121696-bef85fb1-cb3c-415a-bb4b-dd96d11f1375.jpg)

I am trying to change profile picture of all connected instances in one go. But i am getting file not found error.

**Comment by salman0ansari** [comment]
try giving full path

**Comment by sahiljain379** [comment]
tried with full path, still didn't work 
![IMG-20221001-WA0009](https://user-images.githubusercontent.com/64308364/193399515-00417bea-3ac2-47f4-979b-8ed6fa3cea1a.jpg)

**Comment by sahiljain379** [comment]
Tried with full path, still didn't work
![IMG-20221001-WA0010](https://user-images.githubusercontent.com/64308364/193399548-f99896e1-4e87-4fdb-ac72-f2078e1a4bd9.jpg)

**Comment by sahiljain379** [comment]
Tried with full path, still didn't work.

![IMG-20221001-WA0008](https://user-images.githubusercontent.com/64308364/193399567-215d7010-4ba2-43af-b6e6-718d9468883a.jpg)

**Comment by salman0ansari** [comment]
Test this url and tell me if it works or not
https://picsum.photos/200/300

**Comment by sahiljain379** [comment]
tried the url, did not work. 
Am i doing something wrong?

![IMG-20221001-WA0016](https://user-images.githubusercontent.com/64308364/193417402-23cf8e3a-9f35-4d25-8386-7c6b815f1787.jpg)

**Comment by sahiljain379** [comment]
Issue solved. was grabbing numbers with + sign in country code, removed it. now it is working fine.

**Comment by sahiljain379** [comment]
thank you @salman0ansari for the support.
