### ISSUE TITLE
How to keep instances connected?

### ISSUE THREAD

**Issue by sahiljain379** [salman0ansari/whatsapp-api-nodejs#354]
Hi, I have connected 24 instances but only 3-4 instance are running at a time. 

Whenever I try to send messages selecting 'ALL Instances" Half of the messages get failed due to error 'Instance not found'

While Sending message from a single instance, First time message fails only works on second attempt.

**Comment by sahiljain379** [comment]
Anyone here has been able to keep multiple instances connected for days/weeks on end?

**Comment by salman0ansari** [comment]
@sahiljain379 msg me on telegram

**Comment by sahiljain379** [comment]
done. @salman0ansari

**Comment by khushdadhaniya** [comment]
is there anything need to take additional steps to keep instance keep connected?

**Comment by drdaga** [comment]
> Hi, I have connected 24 instances but only 3-4 instance are running at a time.
> 
> Whenever I try to send messages selecting 'ALL Instances" Half of the messages get failed due to error 'Instance not found'
> 
> While Sending message from a single instance, First time message fails only works on second attempt.



> is there anything need to take additional steps to keep instance keep connected?

same question
