### ISSUE TITLE
Webhook Problem

### ISSUE THREAD

**Issue by ernanijose** [salman0ansari/whatsapp-api-nodejs#356]
I am not able to receive any messages on the webhook.

I created webhook locally and also used the website webhook.site, but I don't get any messages.
I put it to receive the messages in post
![Captura de tela 2022-10-07 085347](https://user-images.githubusercontent.com/61758084/194547322-3bd86878-dbdd-43a4-b7e0-db4cf58297e6.png)

**Comment by achdiadsyah** [comment]
did u set your env to TRUE ?
