### ISSUE TITLE
Multiple notifications WebHook

### ISSUE THREAD

**Issue by raf-rodrigues** [salman0ansari/whatsapp-api-nodejs#359]
Hello I believe that the Webhook is sending too many notifications about 500 per minute. _(I was blocked on https://webhook.site/ \o/ )_

I configured by the url parameter,

**webhook=true&webhookUrl=**

When activated, it sends messages of the type

```
{
   "type": "connection",
   "body": {
     "connection": "close"
   }
}

{
   "type": "connection",
   "body": {
     "connection": "open"
   }
}
```
And this is non-stop, when I send a message it appears among the handfuls of news from the api.

Another thing is that when I configure the url of the webhook in the .env it doesn't work it doesn't send a message to the webhook.

Sorry if it's a silly question. I'm new to the project.

**Comment by salman0ansari** [comment]
> Hello I believe that the Webhook is sending too many notifications about 500 per minute. _(I was blocked on https://webhook.site/ \o/ )_
> 
> I configured by the url parameter,
> 
> **webhook=true&webhookUrl=**
> 
> When activated, it sends messages of the type
> 
> ```
> {
>    "type": "connection",
>    "body": {
>      "connection": "close"
>    }
> }
> 
> {
>    "type": "connection",
>    "body": {
>      "connection": "open"
>    }
> }
> ```
> 
> And this is non-stop, when I send a message it appears among the handfuls of news from the api.
> 
> Another thing is that when I configure the url of the webhook in the .env it doesn't work it doesn't send a message to the webhook.
> 
> Sorry if it's a silly question. I'm new to the project.

webhook.site is only for testing 🤦🏻
create your own webhook receiver

**Comment by raf-rodrigues** [comment]
> > Olá acredito que o Webhook está enviando muitas notificações cerca de 500 por minuto. _(Fui bloqueado em https://webhook.site/ \o/ )l
> 
> webhook.site é apenas para teste 🤦🏻 crie seu próprio receptor de webhook

I know I went for a test and when I saw him he had consumed everything in 1 minute.

But are these notifications common?

**Comment by augustofcs** [comment]
> Hello I believe that the Webhook is sending too many notifications about 500 per minute. _(I was blocked on https://webhook.site/ \o/ )_
> 
> I configured by the url parameter,
> 
> **webhook=true&webhookUrl=**
> 
> When activated, it sends messages of the type
> 
> ```
> {
>    "type": "connection",
>    "body": {
>      "connection": "close"
>    }
> }
> 
> {
>    "type": "connection",
>    "body": {
>      "connection": "open"
>    }
> }
> ```
> 
> And this is non-stop, when I send a message it appears among the handfuls of news from the api.
> 
> Another thing is that when I configure the url of the webhook in the .env it doesn't work it doesn't send a message to the webhook.
> 
> Sorry if it's a silly question. I'm new to the project.

The same thing happened to me when I restarted the api, and gave the command restore all instances.

**Comment by sahiljain379** [comment]
Can you help me out #366 please?

**Comment by diemesolutions** [comment]
> if you dont want to receive that then comment out line 122-124 in `src/api/class/instance.js`

//await this.SendWebhook('connection', {
       //    connection: connection,
//})

e tem também na 107 - 109
//await this.SendWebhook('connection', {
        //    connection: connection,
//})
