### ISSUE TITLE
Some functions are missing

### ISSUE THREAD

**Issue by johbs** [salman0ansari/whatsapp-api-nodejs#369]
Checking Baileys library whe found some functions that are missing in whatsapp-api-nodejs bellow:

- To join the group using the invitation code > **sock.groupAcceptInvite("xxx")**
- To get group info by invite code > **sock.groupGetInviteInfo("xxx")**

Do you have any idea when it will be implemented?

**Comment by KevinEduardo** [comment]
Also, would be nice to have a way to check if a message has been successfully sent after sending it. something like "getMessageStatus"

**Comment by E-VALLE** [comment]
Is there any way to get data from the connected device, such as brand/model, pushname, number, platform, battery percentage?

**Comment by salman0ansari** [comment]
> Is there any way to get data from the connected device, such as brand/model, pushname, number, platform, battery percentage?

No
