### ISSUE TITLE
How to identify a key with multiple webhook

### ISSUE THREAD

**Issue by pauloanalista** [salman0ansari/whatsapp-api-nodejs#374]
How to identify a key with multiple webhook

I create my key this way
http://sp.com.br:3333/instance/init?token=TOKEN&key=paulo&webhook=true&webhookUrl=http://sp.com.br/z/ret.php

webhook only returns

{
    "type": "connection",
    "body": {
      "connection": "close"
    }
}

{
    "type": "connection",
    "body": {
      "connection": "open"
    }
}

Can someone help me?

**Comment by arislanhaikal** [comment]
Just simple create instance with key identifier in your webhook, you can add key param
Ex: http://sp.com.br:3333/instance/init?token=TOKEN&key=paulo&webhook=true&webhookUrl=http://sp.com.br/z/ret.php?key=paulo

On your webhook check param key, its coming webhook from specific key. That it
