### ISSUE TITLE
vm2 vulnerability

### ISSUE THREAD

**Issue by jhonyrsy** [salman0ansari/whatsapp-api-nodejs#376]
Hello, how are you? I recently received a related alert from the IT team about the vm2 sandbox vulnerability. Can you tell me if the API uses this library? Thanks

**Comment by salman0ansari** [comment]
> Hello, how are you? I recently received a related alert from the IT team about the vm2 sandbox vulnerability. Can you tell me if the API uses this library? Thanks

No we don't use any library named `VM2`
