### ISSUE TITLE
Error on route group/create

### ISSUE THREAD

**Issue by andreluisfc** [salman0ansari/whatsapp-api-nodejs#377]
I'm unable to create a new group using the /group/create route.

there is my headers:
```
{
  "name": "TEST GROUP",
  "users": ["myid"]
}
```

the response is

```
[
{
"body":
{
"error":
false
},
"headers":
{
"x-powered-by":
"Express",
"content-type":
"application/json; charset=utf-8",
"content-length":
15,
"etag":
"W/"f-vq7iR8edCWsBmYr0817vqlEnUMY"",
"date":
"Wed, 19 Oct 2022 18:29:13 GMT",
"connection":
"close"
},
"statusCode":
201,
"statusMessage":
"Created"
}
]
```

but nothing happens.

btw, the create group route on postman docs is a get and dont have params.

https://documenter.getpostman.com/view/12514774/UVsPQkBq#e4b18341-73ac-4a56-b9c8-d1e472e7db77

**Comment by salman0ansari** [comment]
> 

Set log level to debug than post error

**Comment by salman0ansari** [comment]
no info provided
