### ISSUE TITLE
Postman or Insomnia Documentation

### ISSUE THREAD

**Issue by dasmond1** [salman0ansari/whatsapp-api-nodejs#39]
is anyone here interested to get some api doc from postman or insomnia ?
if you interested, i'll make a full of documentation from this repo.
Please replay if anyone interested :)

**Comment by salman0ansari** [comment]
If you have finished docs you can make a PR if you want to.

**Comment by dasmond1** [comment]
> If you have finished docs you can make a PR if you want to.

i will. thanks for supporting

**Comment by salman0ansari** [comment]
> > If you have finished docs you can make a PR if you want to.
> 
> i will. thanks for supporting

I have half finished postman docs you can complete it if you need it msg me on telegram @salman0ansari
