### ISSUE TITLE
The WEBHOOK does not return the received images

### ISSUE THREAD

**Issue by billantony** [salman0ansari/whatsapp-api-nodejs#399]
hello, when receiving an image the webhook does not return the content... it only returns the jpegThumbnail

{"error":false,"data":{"key":{"remoteJid":"01389428392@s.whatsapp.net","fromMe":true,"id":"BAE5F233EA3C450C"},"message":{"imageMessage":{"url":"https://mmg.whatsapp.net/d/f/As2FWstgL73E-CA8jCB7fb1pp5of-p3FDH9L0n6M2xIa.enc","mimetype":"image/png","caption":"","fileSha256":"eYpMedUm2HBnuLew/CCHMrFVZimUsM3uAkSTPGBRf4k=","fileLength":"694144","mediaKey":"7h3es2Fo8Wz3a2SQRQo14lHMSXOan8SI30oH/UnFo1I=","fileEncSha256":"4JYhMMoHrqPr80PngUVHSIIv/9C2QecYbWTTWw3RDf8=","directPath":"/v/t62.7118-24/19976497_1266528357249348_5290552874828746713_n.enc?ccb=11-4&oh=01_AVwPzm3AZHWCOYiK1_OUC7JTQ0WCF2eiZ-CImFc0FKItDQ&oe=6306FF35","mediaKeyTimestamp":"1658936226","jpegThumbnail":"/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAgACADASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAABQYAAwQC/8QAKxAAAgEEAAQFAwUAAAAAAAAAAQIDAAQREgUGEyEiMUFRYRQyYnGBgpGh/8QAFgEBAQEAAAAAAAAAAAAAAAAAAwQC/8QAGxEAAgMBAQEAAAAAAAAAAAAAAQIAAxETIVH/2gAMAwEAAhEDEQA/ABlvZXVy+sFvI5+F7D96PWfKMrqGu7lY/wAYxsf78qJz8RuEklUMuEYgDp+la7Ca6nId2iMWSDgYPl2qtrHzzyGAInXvDRbudDlCfCWPcisNvE0lx0pFwM4ytOvELaNkdG1fqsNRjGvvQyw4F0rpizNgE6knIIqHu/2W8VPuRqIBqj6pASFGQPXIwaW7HmYLYiC52WVV1WUDYEfI966h4xYIdnkOWOWCxnBI8q3YtinAIVQrI1jCtyjyZVEXdD4S/bFW243kdGyGx+hobLzPYEY6c0n8AM/7UPMUTAzInhC/aZFDVjg+7kU3Armz/9k="}},"messageTimestamp":"1658936226","status":"PENDING"}}

**Comment by salman0ansari** [comment]
change this to `true`
https://github.com/salman0ansari/whatsapp-api-nodejs/blob/e2beb6c5dec30bd2bd0b028637257d29688eb887/.env.example#L38

**Comment by billantony** [comment]
is enabled **WEBHOOK_BASE64=true**
