### ISSUE TITLE
Close after scan QR

### ISSUE THREAD

**Issue by furqon** [salman0ansari/whatsapp-api-nodejs#4]
Hi @salman0ansari thank you for the code, I got error after scan the QR code.

`0.Base.js:126
            encKey: this.authInfo.encKey.toString('base64'),
TypeError: Cannot read property 'toString' of undefined`

What I do currently comment out 

> // client.on('qr',async ()  => {
> //         const authInfo = await client.base64EncodedAuthInfo()
> //         fs.writeFileSync('./auth_info.json', JSON.stringify(authInfo, null, '\t'))
> // })

and it works. Do you know what causing this?

**Comment by salman0ansari** [comment]
> Hi @salman0ansari thank you for the code, I got error after scan the QR code.
> 
> `0.Base.js:126 encKey: this.authInfo.encKey.toString('base64'), TypeError: Cannot read property 'toString' of undefined`
> 
> What I do currently comment out
> 
> > // client.on('qr',async ()  => {
> > //         const authInfo = await client.base64EncodedAuthInfo()
> > //         fs.writeFileSync('./auth_info.json', JSON.stringify(authInfo, null, '\t'))
> > // })
> 
> and it works. Do you know what causing this?

Uncomment those line and delete auth_info.json file and run script again I'll fix this later today

**Comment by salman0ansari** [comment]
client.on('open') should work

**Comment by furqon** [comment]
ok, it works.
thank you
