### ISSUE TITLE
[updateProfilePicture] AxiosError: Request failed with status code 403

### ISSUE THREAD

**Issue by rlmoura** [salman0ansari/whatsapp-api-nodejs#406]
Guys, I'm trying to update the group image, but I'm getting this error.

`{
  "error": true,
  "message": "Unable to update profile picture"
}`

Log: AxiosError: Request failed with status code 403

Image test: https://trello.com/1/cards/6155e8391644ed0fbbddf934/attachments/6155e9af8128f13ec3e0bf11/download/Capa_01.jpg

endpoint: /misc/updateProfilePicture

Could anyone help me to solve it?

**Comment by salman0ansari** [comment]
Use `Direct URL`

**Comment by rlmoura** [comment]
> Use `Direct URL`

Sorry, I do not understand.
