### ISSUE TITLE
[updateProfilePicture] Error: No image processing library available

### ISSUE THREAD

**Issue by rlmoura** [salman0ansari/whatsapp-api-nodejs#407]
Does anyone know why this error happens when trying to change the group photo?

Error: No image processing library available

I'm running on docker according to the installation instructions.

**Comment by salman0ansari** [comment]
install jimp or sharp

**Comment by rlmoura** [comment]
> install jimp or sharp

Do I install it inside docker? How do I do this?

Do you have a referral link?

Thanks

**Comment by rlmoura** [comment]
Can someone guide me step by step for this installation?

I have run the library installation but it still doesn't work.

**Comment by rlmoura** [comment]
Yarn add jimp in folder project
