### ISSUE TITLE
doubt sending messages

### ISSUE THREAD

**Issue by abelgenial** [salman0ansari/whatsapp-api-nodejs#408]
hello, how do I skip a line in the middle of the text that will be sent using Send Text Message
thank

**Comment by salman0ansari** [comment]
what do you mean?

**Comment by salman0ansari** [comment]
sorry i dont get it

**Comment by abelgenial** [comment]
wanted to know how to break the line in the message,
example:
hello abel,
all good ?

"in the example above the message would be sent in two lines and not in a single line hello abel, how are you?"

**Comment by abelgenial** [comment]
in another api that I was testing I did like this in the message that would be sent

"hello abel,\nhow are you?"

the string "\n" meant an "enter" to break the line

thanks

**Comment by raphaelmprimo** [comment]
Same question here: how to send a multiline message?

**Comment by renatokeys** [comment]
This isnt an issue, read https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

**Comment by salman0ansari** [comment]
use EOL character
![image](https://user-images.githubusercontent.com/30106022/203499813-ebfc07d7-e8c3-4499-8208-4b4931b209ca.png)
![image](https://user-images.githubusercontent.com/30106022/203500302-663f5838-33eb-4586-a79d-8bc7eccfb144.png)
