### ISSUE TITLE
Deploy on vercel error on mongoClient is not defined

### ISSUE THREAD

**Issue by afifhusnul** [salman0ansari/whatsapp-api-nodejs#409]
I have tried to deploy with Vercel and got this error.

{
    "error": true,
    "code": 500,
    "message": "ReferenceError: mongoClient is not defined"
}

I believe this error come from server js.
global.mongoClient = await connectToCluster(config.mongoose.url)

How to solve this issue?

**Comment by salman0ansari** [comment]
Vercel is only for static websites 🤦🏻

**Comment by afifhusnul** [comment]
Would you please give idea for workaround to do this?

**Comment by salman0ansari** [comment]
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/deployment#example_installing_locallibrary_on_railway

**Comment by afifhusnul** [comment]
Thank you, will try it in Vercel.
