### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by sairmali** [salman0ansari/whatsapp-api-nodejs#410]
{
    "error": true,
    "code": 500,
    "message": "1006"
}

**Comment by sairmali** [comment]
![image](https://user-images.githubusercontent.com/54973008/201509576-398af6fe-aec8-4dce-bbc6-602b7f054306.png)

taking too much time and not responding

**Comment by sairmali** [comment]
different type of errors

{
    "error": true,
    "code": 500,
    "message": "Error: Connection Closed"
}

{
    "error": true,
    "code": 500,
    "message": "1006"
}

**Comment by sairmali** [comment]
but instance fetched 

{
    "error": false,
    "message": "Instance fetched successfully",
    "instance_data": {
        "instance_key": "30c38d63-0e62-42cd-b103-a108c13015db",
        "phone_connected": true,
        "webhookUrl": "https://webhook.site/d0122a66",
        "user": {
            "id": "91xxxxxxxxx15:85@s.whatsapp.net",
            "name": "alen"
        }
    }
}

**Comment by sairmali** [comment]
@salman0ansari ?

**Comment by sairmali** [comment]
@salman0ansari this problem not only button same problem with all type of messages

**Comment by arislanhaikal** [comment]
@sairmali any update? i have some problem
```
{
"error": true,
"code": 500,
"message": "Error: Connection Closed"
}
```
But phone connected

**Comment by maiquelfrantz** [comment]
I'm having the same problem, any updates?

**Comment by maiquelfrantz** [comment]
@salman0ansari You marked it as a duplicate, but I couldn't find any other item like it, can you point it out?
