### ISSUE TITLE
Endpoint /message/button not working

### ISSUE THREAD

**Issue by kevineduardo** [salman0ansari/whatsapp-api-nodejs#411]
![image](https://user-images.githubusercontent.com/5313724/201548326-e9a6a9de-e467-4ecd-ab82-e90283056c27.png)
This endpoint is not working.

When you try to send it returns the following output:
`{
	"error": true,
	"code": 500,
	"message": "TypeError: Cannot read properties of undefined (reading 'match')"
}`

**Comment by KevinEduardo** [comment]
All the other endpoints works perfectly. I'm using iOS latest version. WhatsApp also on the latest version.

**Comment by madebyais** [comment]
Confirmed, i tested last night, doesn't work for both whatsapp android and ios using latest version, however it works on whatsapp business app

**Comment by higormachado3** [comment]
Is the problem with the buttons fixed in this new update?

**Comment by italodea** [comment]
> Confirmed, i tested last night, doesn't work for both whatsapp android and ios using latest version, however it works on whatsapp business app

Try again with latest commit

**Comment by jvbrandao** [comment]
I had the same problem but only with IOS the message said it was sent but on IOS it arrived empty
