### ISSUE TITLE
getStatus method is not working

### ISSUE THREAD

**Issue by huzaifansari54** [salman0ansari/whatsapp-api-nodejs#412]
when i call getstause method it show me this json response {error:false} it not show data  when i use console.log('data: $data') it show me data: Undefine when i call getstataus from server please help me i want user statatus

**Comment by salman0ansari** [comment]
maybe they don't share their status with you?

**Comment by salman0ansari** [comment]
something wrong on your side as of now 
the endpoint is working fine
![image](https://user-images.githubusercontent.com/30106022/203499583-5fa1426b-417d-4eb5-b014-dc294a97cad0.png)
