### ISSUE TITLE
Error kills server after reading qr code.

### ISSUE THREAD

**Issue by Sulivan1999** [salman0ansari/whatsapp-api-nodejs#42]
Hello, I'm getting this error right after reading the qr-code, the server stops after the error. Can you help me?

`{"level":30,"time":1647628378460,"pid":500079,"hostname":"vmi625985.contaboserver.net","pid":500079,                                                                    "hostname":"vmi625985.contaboserver.net","class":"baileys","histNotification":{"fileSha256":"fPGw0o4                                                                    U6nDbCiyeLkOpmLkgvmMe/2nZ6F+7B3uUSRk=","fileLength":"64115","mediaKey":"YCSpqn+Zo+V4mS1kKreaJfZhblXX                                                                    Nw+CBYIdbqBXPiA=","fileEncSha256":"OX9rLhvKJQYkXOksk1zqHjN9h3zFGxw4GJ322XzNuz0=","directPath":"/v/t6                                                                    2.31111-24/11751996_287822846763677_5514845287318593325_n.enc?ccb=11-4&oh=01_AVw52QFL9MxOpYn5hN6wThY                                                                    OqQv4FZo1PL0UVKGUAlATTQ&oe=6259BB33","syncType":"INITIAL_STATUS_V3"},"id":"B67406A3DADE68777528E1A52                                                                    DD409AA","msg":"got history notification"}
{"level":50,"time":1647628378538,"pid":500079,"hostname":"vmi625985.contaboserver.net","err":{"type"                                                                    :"Error","message":"Connection Closed","stack":"Error: Connection Closed\n    at sendRawMessage (/ho                                                                    me/cp9379ba026/web/public/md_baileys/teste/novo/baileys_api_md/node_modules/@adiwajshing/baileys/lib                                                                    /Socket/socket.js:63:19)\n    at sendNode (/home/cp9379ba026/web/public/md_baileys/teste/novo/bailey                                                                    s_api_md/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:71:16)\n    at processMessage (/home                                                                    /cp9379ba026/web/public/md_baileys/teste/novo/baileys_api_md/node_modules/@adiwajshing/baileys/lib/S                                                                    ocket/messages-recv.js:123:27)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections                                                                     (node:internal/process/task_queues:96:5)\n    at async EventEmitter.<anonymous> (/home/cp9379ba026/                                                                    web/public/md_baileys/teste/novo/baileys_api_md/node_modules/@adiwajshing/baileys/lib/Socket/message                                                                    s-recv.js:452:17)","data":null,"isBoom":true,"isServer":false,"output":{"statusCode":428,"payload":{                                                                    "statusCode":428,"error":"Precondition Required","message":"Connection Closed"},"headers":{}}},"msg"                                                                    :"Connection Closed"}
{"level":30,"time":1647628378541,"pid":500079,"hostname":"vmi625985.contaboserver.net","pid":500079,                                                                    "hostname":"vmi625985.contaboserver.net","class":"baileys","msg":"connected to WA Web"}
{"level":30,"time":1647628378639,"pid":500079,"hostname":"vmi625985.contaboserver.net","pid":500079,                                                                    "hostname":"vmi625985.contaboserver.net","class":"baileys","msg":"handshake complete"}
{"level":30,"time":1647628378639,"pid":500079,"hostname":"vmi625985.contaboserver.net","pid":500079,                                                                    "hostname":"vmi625985.contaboserver.net","class":"baileys","msg":"logging in..."}
{"level":30,"time":1647628378644,"pid":500079,"hostname":"vmi625985.contaboserver.net","msg":"Server                                                                     closed"}`

**Comment by dasmond1** [comment]
what branch are you using ? main or MultiDevice ?

**Comment by Sulivan1999** [comment]
> qual ramo você está usando? principal ou MultiDevice?

I'm using multidevice

**Comment by salman0ansari** [comment]
can you answer this questions
- what node version are you using?
- is this a server or pc and which OS?
- are you facing this error everytime you scan code?

**Comment by Sulivan1999** [comment]
- API Version: 3.0.0
- Baileys Version: ^4.0.0
- I'm using an Ubuntu 20.04 (64-bit) server
-  Yes every time you scan the error is pointed out

**Comment by salman0ansari** [comment]
I have never seen this error in this project 
you are first one to report this

**Comment by salman0ansari** [comment]
can you try
- deleting auth file
- leaving multi device and rejoin it

**Comment by salman0ansari** [comment]
pls update with
