### ISSUE TITLE
How can I add a participant to a group?

### ISSUE THREAD

**Issue by billantony** [salman0ansari/whatsapp-api-nodejs#424]
$curl = curl_init();

curl_setopt_array($curl, [
  CURLOPT_URL => "http://localhost/group/inviteuser?key=1b-4beb-aa08-128bd25738e4",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
  CURLOPT_POSTFIELDS => "id=120363027023656740&users=12345678909",
  CURLOPT_HTTPHEADER => [
    "Authorization: bearer 123456",
    "Content-Type: application/x-www-form-urlencoded"
  ],
]);

$response = curl_exec($curl);
$err = curl_error($curl);

curl_close($curl);

if ($err) {
  echo "cURL Error #:" . $err;
} else {
  echo $response;
}

{
	"error": false,
	"data": {
		"error": true,
		"message": "Unable to add participant, you must be an admin in this group"
	}
}

**Comment by salman0ansari** [comment]
> $curl = curl_init();
> 
> curl_setopt_array($curl, [ CURLOPT_URL => "http://localhost/group/inviteuser?key=1b-4beb-aa08-128bd25738e4", CURLOPT_RETURNTRANSFER => true, CURLOPT_ENCODING => "", CURLOPT_MAXREDIRS => 10, CURLOPT_TIMEOUT => 30, CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1, CURLOPT_CUSTOMREQUEST => "POST", CURLOPT_POSTFIELDS => "id=120363027023656740&users=12345678909", CURLOPT_HTTPHEADER => [ "Authorization: bearer 123456", "Content-Type: application/x-www-form-urlencoded" ], ]);
> 
> $response = curl_exec($curl); $err = curl_error($curl);
> 
> curl_close($curl);
> 
> if ($err) { echo "cURL Error #:" . $err; } else { echo $response; }
> 
> { "error": false, "data": { "error": true, "message": "Unable to add participant, you must be an admin in this group" } }

read error msg

**Comment by billantony** [comment]
I have tried different shipping methods and they all return the same
<img width="129" alt="image" src="https://user-images.githubusercontent.com/30207442/204102866-75bbaffc-c77b-4893-a7bc-2c9144e925fa.png">

**Comment by salman0ansari** [comment]
read error message it clearly says you are not admin of group
