### ISSUE TITLE
error when running npm install.

### ISSUE THREAD

**Issue by robinhodemorais** [salman0ansari/whatsapp-api-nodejs#45]
error when running npm install.

Note: I use Windows 

`λ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: whatsapp-api-nodejs@3.0.0
npm ERR! Found: sharp@0.30.2
npm ERR! node_modules/sharp
npm ERR!   sharp@"^0.30.1" from the root project   
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer sharp@"^0.29.3" from @adiwajshing/baileys@4.0.1
npm ERR! node_modules/@adiwajshing/baileys
npm ERR!   @adiwajshing/baileys@"^4.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Robinho\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Robinho\AppData\Local\npm-cache\_logs\2022-03-19T23_13_43_591Z-debug-0.log
`

**Comment by akbardwi** [comment]
you can deleted `sharp` on `package.json` and try to install again, this is working for me

**Comment by salman0ansari** [comment]
`npm install --legacy-peer-deps`

**Comment by salman0ansari** [comment]
or just use `yarn install`

**Comment by robinhodemorais** [comment]
thanks, it worked.
