### ISSUE TITLE
CREATE INSTANCES WITH TOKEN CORRECT - PROBLEM

### ISSUE THREAD

**Issue by abelgenial** [salman0ansari/whatsapp-api-nodejs#450]
Sorry, but I can create an instance with the wrong token, even with PROTECT_ROUTES=true or PROTECT_ROUTES=false

I think that the api really does not verify the token

thanks

**Comment by italodea** [comment]
Really?I tried it here and i can't create with wrong token.

I tried too without token and i receive a message with
`{
    "error": true,
    "message": "no bearer token header was present"
}`

Please provide more details of how you did this like sharing postman configs.

**Comment by abelgenial** [comment]
hello italodea

# ==================================
# SECURITY CONFIGURATION
# ==================================
TOKEN=TOKEN123
PROTECT_ROUTES=true

postman:

get init instance
{{baseUrl}}/instance/init?token=xTOKEN789&key=SIRIA

RETURN:

{
    "error": false,
    "message": "Initializing successfully",
    "key": "SIRIA",
    "webhook": {
        "enabled": false,
        "webhookUrl": null
    },
    "qrcode": {
        "url": "http://localhost:3333/instance/qr?key=SIRIA"
    },
    "browser": {
        "platform": "Whatsapp MD",
        "browser": "Chrome",
        "version": "4.0.0"
    }
}

**Comment by abelgenial** [comment]
I can create an instance without a token, see:

{{baseUrl}}/instance/init?key=SIRIA1

{
    "error": false,
    "message": "Initializing successfully",
    "key": "SIRIA1",
    "webhook": {
        "enabled": false,
        "webhookUrl": null
    },
    "qrcode": {
        "url": "http://localhost:3333/instance/qr?key=SIRIA1"
    },
    "browser": {
        "platform": "Whatsapp MD",
        "browser": "Chrome",
        "version": "4.0.0"
    }
}

**Comment by abelgenial** [comment]
To find out, my .env file where I adjust the settings was not being saved correctly.
Thank you for your message as it made me go deeper into what was going on here

**Comment by abelgenial** [comment]
italodea , 
agora que salvei o .env correto, e atualizei o docker, tudo o que vou fazer no postman com a API ele retorna que o token nao esta presente


{{baseUrl}}/instance/list?token=9646

{
    "error": true,
    "message": "no bearer token header was present"
}

agora fiquei sem entender mesmo.

**Comment by abelgenial** [comment]
descobri, tive que acrescentar no header
"authorization"

:)
