### ISSUE TITLE
Can't send message

### ISSUE THREAD

**Issue by renanjoppert1** [salman0ansari/whatsapp-api-nodejs#452]
I've tried to send a message, but the response return 

![image](https://user-images.githubusercontent.com/6248454/207688322-ede658ec-32e5-47e8-95a5-6baaae1db983.png)

![image](https://user-images.githubusercontent.com/6248454/207688360-27dcf01f-f860-45e5-bcb0-892148b949d1.png)

**Comment by salman0ansari** [comment]
use form-data
