### ISSUE TITLE
put status how to use?

### ISSUE THREAD

**Issue by leandrodesign** [salman0ansari/whatsapp-api-nodejs#455]
It's not working or I don't know how to use it. 🇧🇷

**Comment by salman0ansari** [comment]
https://github.com/salman0ansari/whatsapp-api-nodejs/blob/f31a4294455a82c8a4a238c370b3c5b1def7a46d/src/api/routes/message.route.js#L20

https://github.com/salman0ansari/whatsapp-api-nodejs/blob/f31a4294455a82c8a4a238c370b3c5b1def7a46d/src/api/controllers/message.controller.js#L93
