### ISSUE TITLE
Disconnects after QR Code authentication

### ISSUE THREAD

**Issue by eduardofiorini** [salman0ansari/whatsapp-api-nodejs#46]
Hello Salman,
I did the test using a whatsapp MD Normal and whatsapp MD Business both after reading the QRCode and authenticating the connection with whatsapp is closed and disappears from the list of connected devices.

Log:
https://prnt.sc/9vf-xfzkAux2

**Comment by salman0ansari** [comment]
Is it your first time connecting to a Multi Device session?

**Comment by salman0ansari** [comment]
this problem only occurs in Business account 
can you try connecting from different ISP
and connect your to Account web.whatsapp first then connect another session to this API.

**Comment by eduardofiorini** [comment]
The bug is in version v4.0.0 of baileys, I updated the version to v4.0.1 now it works again.

**Comment by bhavesh53** [comment]
@salman0ansari  can you use latest github:adiwajshing/baileys version  ?? if issue with stability can create other branch as now frequently updates from WA so its better to use latest one

**Comment by salman0ansari** [comment]
> @salman0ansari can you use latest github:adiwajshing/baileys version ?? if issue with stability can create other branch as now frequently updates from WA so its better to use latest one

Ok ok.
