### ISSUE TITLE
Phone is not connected after linking device

### ISSUE THREAD

**Issue by vaccarieli** [salman0ansari/whatsapp-api-nodejs#48]
Hi @salman0ansari I am getting this response when I try to send a message, `{"error":true,"message":"phone isn\'t connected"}'`

I already linked it to my WS, does the server saves the session by itself? after linking IF so and i have multiple devices linked to the server how can I select which one is the one that i am going to be sending messages with? anyways this is the url I am using:

with country code
`http://192.168.1.189:3333/message/text?key=790235bd-dc68-4fbe-9605-a9acd674af5c&id=+50760157876&message=Hello World`

without country code
`http://192.168.1.189:3333/message/text?key=790235bd-dc68-4fbe-9605-a9acd674af5c&id=60157876&message=Hello World`

Tetste out the instance and shows no user = {}

`{"error":false,"message":"Instance fetched successfully","instance_data":{"instance_key":"8755e41f-01b3-4910-a45c-d7e39af49a98","user":{}}}`

**Comment by salman0ansari** [comment]
you sure you connected whatsapp linked to this key?

**Comment by vaccarieli** [comment]
@salman0ansari  you are right I did not have it linked to the specific key but now i did. not the issuse is that the command for message is not working.

`curl --location --request POST "http://192.168.1.189:3333/message/text?key=1aa93dac-cbd5-403a-a256-21b10c018ce7&id=50763641778&message=HelloWorld"
{"error":true,"code":500,"message":"TypeError: Cannot read properties of undefined (reading 'includes')"}`

**Comment by salman0ansari** [comment]
That's not how you send a text, read postman docs.
https://github.com/salman0ansari/whatsapp-api-nodejs#postman-docs
