### ISSUE TITLE
Is it possible to send the company contact in this format?

### ISSUE THREAD

**Issue by leandrodesign** [salman0ansari/whatsapp-api-nodejs#482]
Is it possible to send the company contact in this format?

![1](https://user-images.githubusercontent.com/59706165/210817688-625aa887-350f-49ec-a16e-451594797791.png)
![2](https://user-images.githubusercontent.com/59706165/210817731-86354ce1-bad1-4d02-b886-f2bef8bf083c.png)

**Comment by salman0ansari** [comment]
if Baileys support this type of message, Yes.
