### ISSUE TITLE
WEBHOOK_ALLOWED_EVENTS='groups' not emmiting events.

### ISSUE THREAD

**Issue by vaccarieli** [salman0ansari/whatsapp-api-nodejs#496]
Hi, this is my webhook config:

```
#WEBHOOK CONFIGURATION
WEBHOOK_ENABLED=true
WEBHOOK_URL=http://localhost:8000/webhook
WEBHOOK_BASE64=true
WEBHOOK_ALLOWED_EVENTS='messages, groups, group_participants'
```

{"level":40,"time":"2023-01-17T23:33:52.057Z","pid":58065,"hostname":"stanzione","stack":"Error: mutex start\n    at /home/vaccarieli/whatsapp-api-nodejs/node_modules/@adiwajshing/baileys/lib/Utils/make-mutex.js:15:31\n    at Object.mutex (/home/vaccarieli/whatsapp-api-nodejs/node_modules/@adiwajshing/baileys/lib/Utils/make-mutex.js:35:15)\n    at handleReceipt (/home/vaccarieli/whatsapp-api-nodejs/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:361:29)\n    at execTask (/home/vaccarieli/whatsapp-api-nodejs/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:554:20)\n    at processNodeWithBuffer (/home/vaccarieli/whatsapp-api-nodejs/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:551:15)\n    at WebSocket.<anonymous> (/home/vaccarieli/whatsapp-api-nodejs/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:566:9)\n    at WebSocket.emit (node:events:513:28)\n    at /home/vaccarieli/whatsapp-api-nodejs/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:222:35\n    at Object.decodeFrame (/home/vaccarieli/whatsapp-api-nodejs/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)\n    at WebSocket.onMessageRecieved (/home/vaccarieli/whatsapp-api-nodejs/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:198:15)","waitOver":true,"msg":"possible mutex deadlock"}

The only events are working are regular messages, but I am not able to receive any messages from groups, or any related events, I have also tried to create my personal group for testing purposes and is not working either.

**Comment by vaccarieli** [comment]
Anybody ?

**Comment by DeiverJC** [comment]
I'm having the same error, did you manage to fix it?

**Comment by vaccarieli** [comment]
@DeiverJC I am currently checking the error, I mean all I have found so far is that the keys for the messages sent on a group are not being decrypted due to the keys, but Idk which keys, this is the log I get 

```{"messages":[{"key":{"remoteJid":"120363047630248137@g.us","fromMe":true,"id":"3F2CAEFDD841E246F1","participant":"*********@s.whatsapp.net"},"messageTimestamp":1674773949,"pushName":"Elio Gonzalez","broadcast":false,"status":2,"verifiedBizName":"Elio Gonzalez","messageStubType":2,"messageStubParameters":["A pipeline stage specification object must contain exactly one field."]},{"key":{"remoteJid":"120363047630248137@g.us","fromMe":true,"id":"B874EE76878A114E35","participant":"*********@s.whatsapp.net"},"messageTimestamp":1674773949,"pushName":"Elio Gonzalez","broadcast":false,"status":2,"messageStubType":2,"messageStubParameters":["No keys for: 355182139"]}],"type":"notify"}```
