### ISSUE TITLE
reactMessage is not reacting to the message

### ISSUE THREAD

**Issue by leandrodesign** [salman0ansari/whatsapp-api-nodejs#498]
reactMessage is not reacting to the message

**Comment by salman0ansari** [comment]
you're sending invalid body

**Comment by leandrodesign** [comment]
and how would it be? can you help me?

**Comment by salman0ansari** [comment]
```javascript
{ 
	id: "999999"  
	emoji: "😀"
	key: {
    	remoteJid: '999999@s.whastapp.com',
    	id: 'KSIASASIMASIAS', 
	}
} 
```

**Comment by leandrodesign** [comment]
![cccsds](https://user-images.githubusercontent.com/59706165/213709558-ca79de94-5615-450c-bc58-dcd3a8115e66.png)
unsuccessful

**Comment by leandrodesign** [comment]
![cccsds](https://user-images.githubusercontent.com/59706165/213710881-3776d554-4514-4553-801c-6f7cd57e79c4.png)
unsuccessful

**Comment by leandrodesign** [comment]
thank you, it helped a lot, congratulations on the project.
