### ISSUE TITLE
setStatus is not working

### ISSUE THREAD

**Issue by leandrodesign** [salman0ansari/whatsapp-api-nodejs#499]
only the delay is working, it is not showing "composing", "paused", ...

async sendTextMessage(to, message) {
		await this.verifyId(this.getWhatsAppId(to));
		await this.instance.sock?.presenceSubscribe(to);
		await delay(500);
		await this.setStatus('composing', to);
		await delay(1000);
		await this.setStatus('paused', to);
		const data = await this.instance.sock?.sendMessage(
            this.getWhatsAppId(to),
            { text: message }
        );
        return data;
    }

**Comment by hlf-dev-zm** [comment]
One more field is missing here, an **id** field. Where you have to provide the whatsapp id to whom you want to show your presence. The request would be as follows:

{
  status: "composing",
  id: "1234567890@s.whatsapp.net"
}

**Comment by leandrodesign** [comment]
{
    "error": true,
    "message": "status parameter must be one of unavailable, available, composing, recording, paused"
}

**Comment by salman0ansari** [comment]
> { "error": true, "message": "status parameter must be one of unavailable, available, composing, recording, paused" }

read error message slowly

**Comment by leandrodesign** [comment]
> "

![Sem título](https://user-images.githubusercontent.com/59706165/218080759-6b1feaa1-b863-42ae-bf05-7be370e3c8ae.png)

**Comment by salman0ansari** [comment]
try different body types i think raw will work

**Comment by brunodomarketing** [comment]
does it work there?
