### ISSUE TITLE
The WhatsApp API disconnects after a few days (usually 2 or 3)

### ISSUE THREAD

**Issue by marcosmarf27** [salman0ansari/whatsapp-api-nodejs#527]
The WhatsApp API disconnects after a few days (usually 2 or 3), which makes my service unavailable and stops sending messages. To fix this, I have to manually log in, scan the QR code, and connect my phone. How can I solve this problem?"

**Comment by wammachado** [comment]
Também identifiquei esse problema, a intancia é desconectada apos 3 dias

**Comment by flexsoluciones** [comment]
I have the same problem

**Comment by ailton-tim** [comment]
Hello, in my case the API disconnected after only a day, I hosted the API at Heroku paid plan to avoid this problem, some time ago the connection was strong for more than a month, with no problems.
Do you have some tips about the possible problem and how to solve it?
