### ISSUE TITLE
Media Filename Problem

### ISSUE THREAD

**Issue by vaccarieli** [salman0ansari/whatsapp-api-nodejs#53]
File name is not on the file that is being sent. `'fileName': 'file'`

````python
    files= {
    'file': ('fileName.PDF', open(document, 'rb'), 'application/pdf')
    }
````
![155335771-03b8b1bd-4192-4f25-95ab-ede32c1ea541](https://user-images.githubusercontent.com/41475411/159612122-7d71e73e-3380-4383-9604-0776b9191508.png)

**Comment by sairmali** [comment]
please explain this problem ?

**Comment by vaccarieli** [comment]
The problem is that the file is sent with the name 'file' instead of the name given when sent.

**Comment by salman0ansari** [comment]
thanks for reporting will look into it
