### ISSUE TITLE
"message": "ReferenceError: mongoClient is not defined"

### ISSUE THREAD

**Issue by stonestecnologia** [salman0ansari/whatsapp-api-nodejs#536]
Hello everything is fine ?
I ran the application and it shows this error: "message": "ReferenceError: mongoClient is not defined"

**Comment by hlf-dev-zm** [comment]
This error comes when it can not connect to mongodb. Check if mongodb url is given correctly in .env file. Or check for any other connectivity issues.

**Comment by stonestecnologia** [comment]
Ok, but is there any place in the app where I can configure the user and password to access mongoDB?

**Comment by salman0ansari** [comment]
> Ok, but is there any place in the app where I can configure the user and password to access mongoDB?

https://www.mongodb.com/docs/manual/reference/connection-string/

**Comment by stonestecnologia** [comment]
I say inside your code, or a configuration file

**Comment by stonestecnologia** [comment]
my result:

`PS C:\Desenv\Projetos\Whatsapp> yarn start
yarn run v1.22.19
$ node src/server.js
{"level":30,"time":1675913923019,"pid":4884,"hostname":"D22W11","msg":"Listening on port 3333"}
{"level":30,"time":1675913923024,"pid":4884,"hostname":"D22W11","msg":"STATE: Connecting to MongoDB"}
NREFUSED ::1:27017\n    at Connection.openUri (C:\\Desenv\\Projetos\\Whatsapp\\node_modules\\mongoose\\lib\\connection.js:824:32)\n    at C:\\Desenv\\Projetos\\Whatsapp\\node_modules\\mongoose\\lib\\indeNREFUSED ::1:27017\n    at Connection.openUri (C:\\Desenv\\Projetos\\Whatsapp\\node_modules\\mongoose\\lib\\connection.js:824:32)\n    at C:\\Desenv\\Projetos\\Whatsapp\\node_modules\\mongoose\\lib\\index.js:412:10\n    at C:\\Desenv\\Projetos\\Whatsapp\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:41:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Desenv\\Projetos\\Whatsapp\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:40:10)\n    at Mongoose._promiseOrCallback (C:\\Desenv\\Projetos\\Whatsapp\\node_modules\\mongoose\\lib\\index.js:1265:10)\n    at Mongoose.connect (C:\\Desenv\\Projetos\\Whatsapp\\node_modules\\mongoose\\lib\\index.js:411:20)\n    at Object.<anonymous> (C:\\Desenv\\Projetos\\Whatsapp\\src\\server.js:15:14)\n    at Module._compile (node:inNNREFUSED ::1:27017\n    at Connection.openUri (C:\\Desenv\\Projetos\\Whatsapp\\node_modules\\mongoose\\lib\\connection.js:824:32)\n    at C:\\Desenv\\Projetos\\Whatsapp\\node_modules\\mongoose\\lib\\index.js:412:10\n    at C:\\Desenv\\Projetos\\Whatsapp\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:41:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (C:\\Desenv\\Projetos\\Whatsapp\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:40:10)\n    at Mongoose._promiseOrCallback (C:\\Desenv\\Projetos\\Whatsapp\\node_modules\\mongoose\\lib\\index.js:1265:10)\n    at Mongoose.connect (C:\\Desenv\\Projetos\\Whatsapp\\node_modules\\mongoose\\lib\\index.js:411:20)\n    at Object.<anonymous> (C:\\Desenv\\Projetos\\Whatsapp\\src\\server.js:15:14)\n    at Module._compile (node:internal/modules/cjs/loader:1159:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)","reason":{"type":"Unknown","servers":{},"stale":false,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"setName":null,"maxElectionId":null,"maxSetVersion":null,"commonWireVersion":0,"logicalSessionTimeoutMinutes":null}},"msg":"connect ECONNREFUSED ::1:27017"}
{"level":30,"time":1675959213013,"pid":11784,"hostname":"D22W11","msg":"Server closed"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by stonestecnologia** [comment]
# ==================================
# DATABASE CONFIGURATION
# ==================================
MONGODB_ENABLED=true
MONGODB_URL=mongodb://localhost:27017

MongoDB is configured to not use username and password. It's just tests
