### ISSUE TITLE
docker-compose up -d 

### ISSUE THREAD

**Issue by NetoSantosDevBR** [salman0ansari/whatsapp-api-nodejs#537]
![image](https://user-images.githubusercontent.com/114528040/217628516-abed970b-25ae-4339-a64b-fd08bf81c3e4.png)

**Comment by murilohg** [comment]
Hi, I found something here that solved my problem.
https://github.com/yarnpkg/yarn/issues/2976

**Comment by pauloanalista** [comment]
I already uploaded the PR and it was accepted, just download the new version of the project
