### ISSUE TITLE
how can we send link message

### ISSUE THREAD

**Issue by sairmali** [salman0ansari/whatsapp-api-nodejs#54]
![image](https://user-images.githubusercontent.com/54973008/159625512-e4019c15-959c-486f-84dd-99910a9af3a4.png)

**Comment by sairmali** [comment]
like call us ?

**Comment by salman0ansari** [comment]
`localhost:3333/message/button`
```js
var axios = require('axios');
var data = JSON.stringify({
  "id": "",
  "btndata": {
    "text": "title Head",
    "buttons": [
      {
        "type": "replyButton",
        "title": "Reply this text (REPLY)"
      },
      {
        "type": "urlButton",
        "title": "Click me (URL)",
        "payload": "https://google.com"
      },
      {
        "type": "callButton",
        "title": "Click to call (CALL)",
        "payload": "918788889688"
      }
    ],
    "footerText": "title footer"
  }
});

var config = {
  method: 'post',
  url: 'localhost:3333/message/button?key=123',
  headers: { 
    'Content-Type': 'application/json'
  },
  data : data
};

axios(config)
.then(function (response) {
  console.log(JSON.stringify(response.data));
})
.catch(function (error) {
  console.log(error);
});
```


![Screenshot_20220323-112716027 (1)](https://user-images.githubusercontent.com/30106022/159633431-85b838e9-c96d-4735-bb9b-e245fdbcea6a.jpg)

**Comment by salman0ansari** [comment]
read button docs here
https://documenter.getpostman.com/view/12514774/UVsPQkBq#de205b70-f123-4278-8b44-f8341a3f9f13

**Comment by sairmali** [comment]
your new library not scanning phone

**Comment by sairmali** [comment]
showing message could not connect . i have try my different phone but problem is same

**Comment by salman0ansari** [comment]
what is the error?

**Comment by sairmali** [comment]
my phone not scanning

**Comment by sairmali** [comment]
i was using your old library but today i have download your new code when i was run this so i can't scan phone

**Comment by salman0ansari** [comment]
what error comes in console?

**Comment by sairmali** [comment]
http://SERVERIP:3344/instance/qrbase64?key=7422ec75-328e-4fc8-ba4e-ed2378787ioo

when i open this so i can scan phone no error showing in console sir,,,

**Comment by salman0ansari** [comment]
you have to scan code as soon as possible after you create an instance.

**Comment by salman0ansari** [comment]
and make sure to join Whatsapp Multi Device Beta

**Comment by sairmali** [comment]
thanks it is working
