### ISSUE TITLE
"ReferenceError: mongoClient is not defined"

### ISSUE THREAD

**Issue by NoNAT-Telecom** [salman0ansari/whatsapp-api-nodejs#540]
Estou com esse erro quanto tento abrir uma instancia

{
    "error": true,
    "code": 500,
    "message": "ReferenceError: mongoClient is not defined"
}

A API está instalada em AlmaLinux 8, um WEB Server remoto.

**Comment by NoNAT-Telecom** [comment]
Procurando acabei achando que o mongodb não está iniciando devido a um problema de compatibilidade de processador.

"
WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
"

Como eu poderia colocar uma versão mais antiga no processo de instalação do mongo?

**Comment by salman0ansari** [comment]
i am rewriting project #486 
mongo will be completely removed.

**Comment by NoNAT-Telecom** [comment]
Consegui resolver o problema mudando a versão da imagem do Mongo.

No arquivo "docker-compose.yml" mudar de "mongo:latest" para "mongo:4.4.6"
