### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'includes')

### ISSUE THREAD

**Issue by stonestecnologia** [salman0ansari/whatsapp-api-nodejs#542]
Hi !
`{
	"error": true,
	"code": 500,
	"message": "TypeError: Cannot read properties of undefined (reading 'includes')"
}`
whats ? rsrsrs

**Comment by salman0ansari** [comment]
you're use wrong body type.

**Comment by stonestecnologia** [comment]
Thanks for answering me.

I'm trying to send a message through insomnia, 
"Send Text Message" the "id" and "message" are collected by the "Form" 
and in the "QueryString" only the "Key" is going, in this format: 
"http://localhost :3333/message/text?key=89d6", 

what could I be doing wrong?
