### ISSUE TITLE
Problems sending video messages

### ISSUE THREAD

**Issue by ricardopassoni** [salman0ansari/whatsapp-api-nodejs#549]
When I send a video message through the API (SendVideoMessage), the file apparently goes to the destination whatsapp. It appears sent on WhatsApp Web, but nothing appears on the mobile device. The recipient also does not receive the video on his cell phone.

**Comment by salman0ansari** [comment]
provide more information
video extension, size?
this problem occur to all recipient?

**Comment by ricardopassoni** [comment]
This issue occurs when I send any video to any recipient. I noticed that when I use the command for PHP, according to the documentation, the mimetype is: "application/octet-stream". When used by postman, the mimetype is "video/mp4". I will send prints.

**Comment by ricardopassoni** [comment]
![php](https://user-images.githubusercontent.com/125379147/218820586-440bf77f-10b7-4018-a704-de6a2eea439e.png)
![postman](https://user-images.githubusercontent.com/125379147/218820624-6f82d7a3-8caf-4f1b-8a6f-3aaecb834541.png)

**Comment by salman0ansari** [comment]
> This issue occurs when I send any video to any recipient. I noticed that when I use the command for PHP, according to the documentation, the mimetype is: "application/octet-stream". When used by postman, the mimetype is "video/mp4". I will send prints.

video sends when using mimetype video/mp4?

**Comment by ricardopassoni** [comment]
I haven't found a way to force the video/mp4 mimetype via code. Do we have that possibility?

**Comment by ricardopassoni** [comment]
I'm using the code snippet from the documentation:

**Comment by ricardopassoni** [comment]
<?php

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => 'localhost:3333/message/video?key=123',
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'POST',
  CURLOPT_POSTFIELDS => array('file'=> new CURLFILE('/path/to/file'),'id' => '','caption' => ''),
));

$response = curl_exec($curl);

curl_close($curl);
echo $response;

**Comment by salman0ansari** [comment]
how's this problem related to API?
Looks like a problem with PHP

**Comment by ricardopassoni** [comment]
I don't know where the problem is, honestly. It didn't work with any language I tested with the documentation (following exactly what was in the documentation). But I'll bring news if I have. Tks.

**Comment by salman0ansari** [comment]
i just tested it and worked in first try :/

**Comment by ricardopassoni** [comment]
I don't know if I'm doing something wrong. I just copied the code and ran it. I'm going to review my PHP settings. It could be a server problem. Thank you very much!

**Comment by ricardopassoni** [comment]
I found the solution and will share. Just add the type of file to be sent in the new CURFILE command, as shown in print.
![solution](https://user-images.githubusercontent.com/125379147/219152928-d73b8ded-9795-46c0-8139-ca09a2446b8f.png)
