### ISSUE TITLE
The WhatsApp API disconnects after only a day.

### ISSUE THREAD

**Issue by ailton-tim** [salman0ansari/whatsapp-api-nodejs#559]
The API disconnected after only a day, I hosted the API at Heroku to avoid this problem, some time ago the connection was strong for more than a month, with no problems.
Do you have some tips about the possible problem and how to solve it?

**Comment by kurniarocki** [comment]
Don't use Heroku, as it will sleep if there are no incoming requests.

**Comment by ailton-tim** [comment]
> Don't use Heroku, as it will sleep if there are no incoming requests.

Hi @kurniarocki , it happened in the pass at free tier. Now a days Heroku don't have this plan anymore.
In my plan, the project don't sleep.

**Comment by ailton-tim** [comment]
According to the issue history, this problem will be solved as soon as commit # 486 was published.
