### ISSUE TITLE
QRCode can't be scan from WhatsApp non beta

### ISSUE THREAD

**Issue by akbardwi** [salman0ansari/whatsapp-api-nodejs#57]
Why i can't scan QR Code from WA non beta?

**Comment by manojsitapara** [comment]
This repo support only MD

**Comment by akbardwi** [comment]
ohh okay, i think this repo support both

**Comment by salman0ansari** [comment]
> ohh okay, i think this repo support both

It doesn't

**Comment by falahdoclo12** [comment]
what is whatsapp md?

**Comment by dasmond1** [comment]
> what is whatsapp md?

Whatsapp Multi Device or **Beta Version**
