### ISSUE TITLE
Mensagem envia mas não chega

### ISSUE THREAD

**Issue by windson3433** [salman0ansari/whatsapp-api-nodejs#571]
A mensagem envia na API, aparece no whatsapp com 1 certo de enviado, mas não aparece os 2 certos de recebido.
Como resolver?

**Comment by ailton-tim** [comment]
Hi @windson3433 one thing is sent the message, other is received. To receive the mobile phone must be connected to WhatsApp API. Could you check?

**Comment by 100n0m3** [comment]
verificar sempre o numero antes de enviar, o 9 a mais faz diferença usa o endpoint onwhatsapp pra pegar o numero correto
