### ISSUE TITLE
webhook not working

### ISSUE THREAD

**Issue by ricardocduarte** [salman0ansari/whatsapp-api-nodejs#572]
"webhook": {
        "enabled": "true",
        "webhookUrl": null
    },

even if the webhook is enabled in the settings, it is not working

my config
WEBHOOK_ENABLED=true
WEBHOOK_URL=https://webhook.site/67f657fc-9a53-48f9-bcae-26e0890f89e9
WEBHOOK_BASE64=false
WEBHOOK_ALLOWED_EVENTS=

**Comment by salman0ansari** [comment]
will be fixed in #486.

**Comment by elviscosentino** [comment]
@ricardocduarte 
Put the word "messages" here:

WEBHOOK_ALLOWED_EVENTS=messages
