### ISSUE TITLE
"invalid key supplied" after restore

### ISSUE THREAD

**Issue by HenriqueBarucco** [salman0ansari/whatsapp-api-nodejs#578]
After I close the application and start again, even with the restore ssesion enable, it says this "invalid key supplied", it solve when I manually create the instance again, do you have some idea?

**Comment by ailton-tim** [comment]
Hi @HenriqueBarucco this problem will be solved as soon as commit # 486 was finished.

**Comment by wammachado** [comment]
I have the same problem! :(

**Comment by vinibgoulart** [comment]
same, reopen this issue?
