### ISSUE TITLE
Read Webhook URL from environment variable

### ISSUE THREAD

**Issue by manojsitapara** [salman0ansari/whatsapp-api-nodejs#58]
Can we read webhook url from env file instead of config file, it helps user to specify the webhook at runtime.

**Comment by salman0ansari** [comment]
what? elaborate more pls

**Comment by salman0ansari** [comment]
what?

**Comment by dasmond1** [comment]
yes u can by using 
For Webhook use = **process.ENV.WEBHOOK_URL** 
For Port use = **process.ENV.PORT**
etc.

and then create your env file on a root folder, then restart your npm or yarn

**Comment by manojsitapara** [comment]
yes I know in previous repo, it was reading from env variable, but in current repo we read from config value.

**Comment by salman0ansari** [comment]
> yes u can by using For Webhook use = **process.ENV.WEBHOOK_URL** For Port use = **process.ENV.PORT** etc.
> 
> and then create your env file on a root folder, then restart your npm or yarn

I didn't wanted to add another dependency that's why i hard coded those values

**Comment by dasmond1** [comment]
> In current repo it is hard coded value, it is better if we change code to read value from env as per @dasmond1 above comment

yep according to repo's owners.. he didn't wanted to add another dependency that's why he hard coded those values.

so you can fork this repo, and change those value, add push to your private branch

**Comment by salman0ansari** [comment]
#73
