### ISSUE TITLE
I am no longer able to interpret the JSON

### ISSUE THREAD

**Issue by caiopedroso94** [salman0ansari/whatsapp-api-nodejs#585]
I was using the API for a month, and everything was normal. I was receiving the data through the following JSON:
 
{'type': 'message', 'body': {'key': {'remoteJid': '5511945487575@s.whatsapp.net', 'fromMe': False, 'id': 'F2A50999DE8D0A11B5BC94172C5DCF2C'}, 'messageTimestamp': 1678805123, 'pushName': 'Caio Pedroso', 'message': {'conversation': 'Pedsegunda', 'messageContextInfo': {'deviceListMetadata': {'senderKeyHash': 'oOEYa9keFIJPYw==', 'senderTimestamp': '1678741652', 'recipientKeyHash': 'ueTyTuXvBNsTfg==', 'recipientTimestamp': '1678800297'}, 'deviceListMetadataVersion': 2}}, 'text': {'messages': [{'key': {'remoteJid': '5511945487575@s.whatsapp.net', 'fromMe': False, 'id': 'F2A50999DE8D0A11B5BC94172C5DCF2C'}, 'messageTimestamp': 1678805123, 'pushName': 'Caio Pedroso', 'message': {'conversation': 'Pedsegunda', 'messageContextInfo': {'deviceListMetadata': {'senderKeyHash': 'oOEYa9keFIJPYw==', 'senderTimestamp': '1678741652', 'recipientKeyHash': 'ueTyTuXvBNsTfg==', 'recipientTimestamp': '1678800297'}, 'deviceListMetadataVersion': 2}}}], 'type': 'notify'}, 'msgContent': ''}, 'instanceKey': 'firma'}

However, now I am receiving the data in the following format:

{'type': 'message', 'body': {'key': {'remoteJid': '5519996805651@s.whatsapp.net', 'fromMe': True, 'id': '4EC518CE36B26BB171B5AC020FA9DB92'}, 'messageTimestamp': 1679080186, 'pushName': 'Caio Pedroso', 'status': 2, 'message': 
{'extendedTextMessage': {'text': 'Oi', 'previewType': 'NONE', 'contextInfo': {'expiration': 0, 'ephemeralSettingTimestamp': '1679079348', 'disappearingMode': {'initiator': 'CHANGED_IN_CHAT'}}, 'inviteLinkGroupTypeV2': 'DEFAULT'}}, 'msgContent': ''}, 'instanceKey': 'caio'}

I am unable to import the data I need to execute the command. Can someone help me?"

**Comment by salman0ansari** [comment]
you don't know how to read JSON object?
