### ISSUE TITLE
Cannot read property 'includes' of undefined" 

### ISSUE THREAD

**Issue by sairmali** [salman0ansari/whatsapp-api-nodejs#59]
http://localhost:3344/message/image?key=4b4c3f84-0509-4220-bgfhghghghxxxxx

it is working with post man . when i am useing php then showing this error

{
	"error": true,
	"code": 500,
	"message": "TypeError: Cannot read property 'includes' of undefined"
}

node v14.19.0
npm 6.14.16

**Comment by salman0ansari** [comment]
you are not sending form data

**Comment by sairmali** [comment]
<?php

$curl = curl_init();
$headers = array("Content-Type:multipart/form-data");
curl_setopt_array($curl, array(
  CURLOPT_URL => 'http://<server ip>:3344/message/image?key=4b4c3f84-0509-4220-bcedsfdsfdsfdsfds',
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_HTTPHEADER => $headers,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'POST',
  CURLOPT_POSTFIELDS => array('file'=> new CURLFILE('https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg'),'id' => "918218314259",'caption' => "fghfhgfhg"),
));

$response = curl_exec($curl);

curl_close($curl);
echo "<pre>";
print_r(json_decode($response,true));

**Comment by sairmali** [comment]
```
<?php

$curl = curl_init();
$headers = array("Content-Type:multipart/form-data");
curl_setopt_array($curl, array(
  CURLOPT_URL => `'http://5454646:3344/message/image?key=4b4c3f84-0509-422143501e02',`
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_HTTPHEADER => $headers,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'POST',
  CURLOPT_POSTFIELDS => array('file'=> new CURLFILE('https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg'),'id' => "918218314259",'caption' => "fghfhgfhg"),
));

$response = curl_exec($curl);

curl_close($curl);
echo "<pre>";
print_r(json_decode($response,true));

```

**Comment by salman0ansari** [comment]
Not related to project ask someone who knows PHP

**Comment by akbardwi** [comment]
i will getting same issue in mediaurl endpoint

**Comment by jazz7381** [comment]
> 
try change from:
```
$headers = array("Content-Type:multipart/form-data");
```

to:
```
$headers = array("application/x-www-form-urlencoded");
```
