### ISSUE TITLE
create products (catalogue)

### ISSUE THREAD

**Issue by leandrodesign** [salman0ansari/whatsapp-api-nodejs#599]
what am I doing wrong? Has anyone created a product yet?
![1](https://user-images.githubusercontent.com/59706165/228287799-5657f142-1b1c-4c10-a428-65ac84327f2a.png)

![2](https://user-images.githubusercontent.com/59706165/228287379-5fb00b36-62b5-4d92-8431-0ca71f27b089.png)

**Comment by salman0ansari** [comment]
check console
