### ISSUE TITLE
whatsapp-md

### ISSUE THREAD

**Issue by Diden05** [salman0ansari/whatsapp-api-nodejs#6]
Will there be a modification for WhatsApp-MD?  (https://github.com/adiwajshing/Baileys/tree/multi-device)

**Comment by salman0ansari** [comment]
> Will there be a modification for WhatsApp-MD? (https://github.com/adiwajshing/Baileys/tree/multi-device)

Yes, I will implement MD when it will be Stable.

**Comment by Diden05** [comment]
It seems to me that the library is quite stable, although of course it's up to you to decide.

**Comment by salman0ansari** [comment]
Baileys/MD is not stable yet, this is probably because WhatsApp/MD is also still in beta. I'll not start working on it until a stable version is released.

**Comment by manojsitapara** [comment]
@salman0ansari adiwajshing/baileys has merge multi device and web version into one, can we implement MD now?

**Comment by salman0ansari** [comment]
already started working! will push some progress soon.
https://github.com/salman0ansari/whatsapp-api-nodejs/tree/MultiDevice

**Comment by franciscodias89** [comment]
Hi! Very good!
When will this MD version be ready? What's your prediction?

**Comment by salman0ansari** [comment]
1 month **maybe** 😶‍🌫️

**Comment by mateuscdor** [comment]
@salman0ansari 
Multi-device API - Swagger 3.0

Already have developers running baileys - multi-device - api
https://whatsapi-md-demo.herokuapp.com/v3/docs/

**Comment by salman0ansari** [comment]
> @salman0ansari Multi-device API - Swagger 3.0
> 
> Already have developers running baileys - multi-device - api https://whatsapi-md-demo.herokuapp.com/v3/docs/

and?

**Comment by mateuscdor** [comment]
> > @salman0ansari Multi-device API - Swagger 3.0
> > Already have developers running baileys - multi-device - api https://whatsapi-md-demo.herokuapp.com/v3/docs/
> 
> and?

serve as a basis for developing your application in md.

**Comment by salman0ansari** [comment]
> > @salman0ansari Multi-device API - Swagger 3.0
> > Already have developers running baileys - multi-device - api https://whatsapi-md-demo.herokuapp.com/v3/docs/
> 
> did you know the repo?

This project is from @Manjit2003 you can buy  Source code from him if you're interested.

**Comment by salman0ansari** [comment]
> 
Nice, thank you

**Comment by shajujahra2** [comment]
> > > @salman0ansari Multi-device API - Swagger 3.0
> > > Already have developers running baileys - multi-device - api https://whatsapi-md-demo.herokuapp.com/v3/docs/
> > 
> > 
> > did you know the repo?
> 
> This project is from @Manjit2003 you can buy Source code from him if you're interested.

bro i bought from him, can anyone help me to deploy, i have some doubts.

**Comment by salman0ansari** [comment]
> > Thank you for mention @salman0ansari
> 
> I bought from him, not responding after paid

`I missed the part where that's why my problem`
Dont spam here

**Comment by lieZum** [comment]
can we merge multi device branch into main ??

**Comment by lieZum** [comment]
except group endpoints everything is added

**Comment by salman0ansari** [comment]
MD branch is merged now so closing this issue.
