### ISSUE TITLE
i have tried to fork and deploy to heroku

### ISSUE THREAD

**Issue by XMONSTERUK** [salman0ansari/whatsapp-api-nodejs#607]
-----> Building on the Heroku-22 stack
-----> Determining which buildpack to use for this app
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       USE_YARN_CACHE=true
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
       
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       engines.yarn (package.json):  unspecified (use default)
       
       Resolving node version 18.x...
       Downloading and installing node 18.15.0...
       Using default npm version: 9.5.0
       Resolving yarn version 1.22.x...
       Downloading and installing yarn (1.22.19)
       Installed yarn 1.22.19
       
-----> Installing dependencies
       Installing node modules (yarn.lock)
       yarn install v1.22.19
       [1/4] Resolving packages...
       error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
       info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
-----> Build failed
 !     Outdated Yarn lockfile
       Your application contains a Yarn lockfile (yarn.lock) which does not
       match the dependencies in package.json. This can happen if you use npm
       to install or update a dependency instead of Yarn.
       Please run the following command in your application directory and check
       in the new yarn.lock file:
       $ yarn install
       $ git add yarn.lock
       $ git commit -m "Updated Yarn lockfile"
       $ git push heroku main
    
       https://help.heroku.com/TXYS53YJ
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

**Comment by salman0ansari** [comment]
Try changing yarn to npm

**Comment by XMONSTERUK** [comment]
how to do that

**Comment by salman0ansari** [comment]
change yarn install to npm install.

**Comment by salman0ansari** [comment]
Solution is in your error
Please run the following command in your application directory and check
$ yarn install
$ git add yarn.lock
$ git commit -m "Updated Yarn lockfile"
$ git push heroku main

**Comment by XMONSTERUK** [comment]
it's mean i have to download your project and install it to my system and run those 4 commands in my terminal

**Comment by salman0ansari** [comment]
Heroku doesn't give shell access?

**Comment by XMONSTERUK** [comment]
i can't run those commands in heroku im deploying your Repository 
the only way i can do it if i install your Repository in my system and run the commands then commit to github as my Repository and every time you update i need to this all over again i have been searching and the only way
so if you can run it and commit to github i can just fork and deploy
