### ISSUE TITLE
Security issue when deploy on Server

### ISSUE THREAD

**Issue by biplob86429** [salman0ansari/whatsapp-api-nodejs#608]
Sir, If we deploy this code to a Online Server.
If we Run this URL - localhost:3333/instance/init it create a instance key and by the instance key we can generate QR.

But question is - If another person know my URL they also can create instance to my server.

Please tell me :
how we can protect it by a Fixed Token as extra parameater ?

**Comment by salman0ansari** [comment]
README.
https://github.com/salman0ansari/whatsapp-api-nodejs/blob/main/README.md#configuration
