### ISSUE TITLE
Button Not working

### ISSUE THREAD

**Issue by biplob86429** [salman0ansari/whatsapp-api-nodejs#611]
Button not working in WhatsApp Business app. Button showing on Web but not showing on Mobile in WhatsApp Business App. 
Please check.

**Comment by Hemanth-Godavarthi** [comment]
No Update in a channels

**Comment by salman0ansari** [comment]
> No Update in a channels

https://github.com/WhiskeySockets/Baileys/issues/56#issuecomment-1542947921
