### ISSUE TITLE
I connect to the API and I no longer receive notifications on my smartphone.

### ISSUE THREAD

**Issue by murilohg** [salman0ansari/whatsapp-api-nodejs#619]
Hello guys;

I installed it and am using it to send files from the ERP system.

I noticed that when I'm connected to the API my smartphone (IOS) stops receiving notifications. To find out if I have messages I need to open the Whatsapp app. After opening, the messages load.

I thought it was my IOS or my problem, but I tested it on another device (ANDROID) and the same thing happened.
I connect to the API and I no longer receive notifications on my smartphone.

Could anyone help?

**Comment by Saifallak** [comment]
This is normal behavior of using WA Web.
