### ISSUE TITLE
Handling Incoming Whatsapp Calls Programmatically

### ISSUE THREAD

**Issue by badereddineqodia** [salman0ansari/whatsapp-api-nodejs#633]
I am interested in handling incoming voice calls on WhatsApp programmatically.

1. Receive incoming WhatsApp calls
2. Answer the call
3. Receive streaming data and send data back simultaneously in a bidirectional connection
4. End the call

**Comment by salman0ansari** [comment]
This can be done but not implemented yet, you can raise an issue here.
https://github.com/WhiskeySockets/Baileys/issues

**Comment by badereddineqodia** [comment]
But how can it be implemented even though WhatsApp Web doesn't yet have support for handling voice calls or video?

**Comment by salman0ansari** [comment]
> But how can it be implemented even though WhatsApp Web doesn't yet have support for handling voice calls or video?

Through mobile API.
https://github.com/WhiskeySockets/Baileys/pull/2
