### ISSUE TITLE
server crash problem after fatching unknown instance and dead instance

### ISSUE THREAD

**Issue by sairmali** [salman0ansari/whatsapp-api-nodejs#64]
![Screenshot_20220402-152842_Mobile SSH](https://user-images.githubusercontent.com/54973008/161379016-58c9ba35-e6e6-4b6e-8728-d7336d7232ae.jpg)
![Screenshot_20220402-152850_Mobile SSH](https://user-images.githubusercontent.com/54973008/161379020-79aa2547-340a-4600-9e04-213b57ab3d53.jpg)
![Screenshot_20220402-152857_Mobile SSH](https://user-images.githubusercontent.com/54973008/161379023-78f11bbc-ad4c-4e20-a9f5-1f938a3acf87.jpg)

**Comment by salman0ansari** [comment]
on which endpoint this error occurs?

**Comment by sairmali** [comment]
![image](https://user-images.githubusercontent.com/54973008/161418044-106a41fe-879c-4382-9222-0eb329a89934.png)

**Comment by sairmali** [comment]
they are automatically die after restore 5 to 4 minutes

**Comment by sairmali** [comment]
?

**Comment by salman0ansari** [comment]
> ?

i will push fix today

**Comment by sairmali** [comment]
please sir humble request to you       special thanks for you!!!!!!!!!! ☺☺

**Comment by salman0ansari** [comment]
what do you mean by dead/unknown instance ?

**Comment by sairmali** [comment]
yes, when i restore all session , if any number is disconnected and unknown instance after 2 to 5 minutes they are crashed. i don't know . sometime when i remove session folder all instance files they working fine , after 2 to  3 days they gives same problem

**Comment by sairmali** [comment]
1. dead instance mean phone disconnect
2. unknown mean random string i pass existing instances

**Comment by sairmali** [comment]
sir you are completed?

**Comment by sairmali** [comment]
this problem now not resolve

**Comment by salman0ansari** [comment]
pull changes

**Comment by sairmali** [comment]
i have already done
