### ISSUE TITLE
Minimu Spec

### ISSUE THREAD

**Issue by falahdoclo12** [salman0ansari/whatsapp-api-nodejs#65]
i want to use 10 bot whatsapp 
What spec recomend

**Comment by salman0ansari** [comment]
8GB 
4core

**Comment by dasmond1** [comment]
> i want to use 10 bot whatsapp 
> 
> What spec recomend

I use shared hosting with nodejs support and work very well. Now running 12 instance and only take 1 gig of ram

For installation support contact me

**Comment by salman0ansari** [comment]
didn't knew Baileys is so damn optimised.

**Comment by salman0ansari** [comment]
damn Baileys is so optimised ❤️

**Comment by falahdoclo12** [comment]
im use 4 instance on my vps but my vps alyways crash or get response invalid key supplied aftre restore

**Comment by dasmond1** [comment]
> im use 4 instance on my vps but my vps alyways crash or get response invalid key supplied aftre restore

try cronjob or crontab to do a curl "https://YOUR_SERVER_IP/instance/restore" every 2 or 3 minute once

**Comment by salman0ansari** [comment]
> im use 4 instance on my vps but my vps alyways crash or get response invalid key supplied aftre restore

can you share more info?
share error log or screenshot of error
