### ISSUE TITLE
error yarn install

### ISSUE THREAD

**Issue by fabiosantosrj** [salman0ansari/whatsapp-api-nodejs#659]
Hey guys,

I cloned Git today and when I ran the command "yarn install", it generated an error in the middle of the process:

```
Trace:
Error: EPERM: Operation not allowed, unbind 'C:\Users\xxxxxx\AppData\Local\Yarn\Cache\v6\npm-rxjs-7.8.1-6f6f3d99ea8044291efd92e7c7fcf562c4057543-integrity\node_modules\rxjs\.yarn-tarball.tgz'
```

My OS is Windows 10.
However, through NPM it worked correctly.
Can anyone tell me why Yarn didn't work?

**Comment by salman0ansari** [comment]
I think you don't have modify access.

**Comment by salman0ansari** [comment]
try solution mentioned here
https://stackoverflow.com/questions/34600932/npm-eperm-operation-not-permitted-on-windows
