### ISSUE TITLE
how much number i can add ?

### ISSUE THREAD

**Issue by sairmali** [salman0ansari/whatsapp-api-nodejs#66]

**Comment by salman0ansari** [comment]
in WhatsApp?

**Comment by salman0ansari** [comment]
add number? Wdym

**Comment by sairmali** [comment]
i mean how much number i can add and scan on this ?

**Comment by salman0ansari** [comment]
> i mean how much number i can add and scan on this ?

don't go above 10-15 you might get banned, @dasmond1 running 10+ instances.

**Comment by sairmali** [comment]
i want to add and scan 1K numbers. what is solution please tell me ?

**Comment by salman0ansari** [comment]
you cant use this many sessions in one server
you have to use huge cluster of servers to solve this issue.

**Comment by sairmali** [comment]
you mean like docker images ?

**Comment by dasmond1** [comment]
> you mean like docker images ?

yes you can. But...
For better and more safer..

i highly recommend you to use 1 vps with 10 instace (Max) and get another VPS with diffrent IP to use more 10 instance..
even you VPS is with the best spec.. my recomendation is 1 VPS = 10 Instance

**Comment by salman0ansari** [comment]
> > I want to add and scan 1K numbers. what is solution please tell me ?
> 
> hey just for curiosity, where are u getting 1k more numbers from???

virtual numbers maybe
