### ISSUE TITLE
Using DigitalOcean Ubuntu Server: API Active and Functional Only with Single User

### ISSUE THREAD

**Issue by dinizwebmaster** [salman0ansari/whatsapp-api-nodejs#664]
I'm using this API in a multi-user application that I've developed, where I would like each user to be able to utilize the integration. However, when more than one user connects, the entire API becomes unstable, restarts multiple times, and freezes.

Is there any configuration that might be done incorrectly, or do I need a separate API for each session?

I'm using an Ubuntu server from DigitalOcean, and currently, with only one user (instance), the API is active and working.

**Comment by salman0ansari** [comment]
message me on telegram 
https://telegram.dog/salman0ansari
