### ISSUE TITLE
Error Yarn Install

### ISSUE THREAD

**Issue by eduardohr-muniz** [salman0ansari/whatsapp-api-nodejs#665]
![image](https://github.com/salman0ansari/whatsapp-api-nodejs/assets/90477293/03ab67a7-7871-4f5e-8e4f-4b84c7f1a22e)

**Comment by salman0ansari** [comment]
are you on latest commit?

**Comment by eduardohr-muniz** [comment]
I just got it from scratch, deleted the previous folder and did git clone + url again and it's the same error, I entered the project, gave git pull and even so the error persists

**Comment by salman0ansari** [comment]
can you try
yarn add @whiskeysockets/baileys

**Comment by eduardohr-muniz** [comment]
I wanted to do it, I got the same error
I put it in gpt to see the error, it answered me this:
This error occurs when Git is unable to find a match for the specific commit with the identifier "13810ec7ea3700ec0e1b676869a2522993827de5" within the references (refs) history of the repository. Git checks various references, such as branches and tags, to locate the desired commit.

In the case of the mentioned error, Git searched for the commit in multiple references (refs), including branches and tags, but couldn't find a match.

This can happen if the commit no longer exists in the repository or if the commit identifier is incorrect. Please ensure that you are using the correct commit identifier and check if the commit is still present in the remote repository.

**Comment by eduardohr-muniz** [comment]
the error is on my machine it must be some dependency, I put it on another machine it worked, sorry for the inconvenience

**Comment by salman0ansari** [comment]
You can close the issue if it's solved.
