### ISSUE TITLE
Error when running docker-compose : node:internal/modules/cjs/loader:1093

### ISSUE THREAD

**Issue by maiquelfrantz** [salman0ansari/whatsapp-api-nodejs#666]
I have the following error when running docker-compose

yarn run v1.22.19
$ node src/server.js
node:internal/modules/cjs/loader:1093
  throw err;
  ^

Error: Cannot find module '@adiwajshing/keyed-db'
Require stack:
- /home/node/app/node_modules/@whiskeysockets/baileys/lib/Store/make-in-memory-store.js
- /home/node/app/node_modules/@whiskeysockets/baileys/lib/Store/index.js
- /home/node/app/node_modules/@whiskeysockets/baileys/lib/index.js
- /home/node/app/src/api/class/instance.js
- /home/node/app/src/api/controllers/instance.controller.js

**Comment by achdiadsyah** [comment]
is this issue was solved ?

**Comment by salman0ansari** [comment]
just run 🤦
` yarn add @adiwajshing/keyed-db`

**Comment by achdiadsyah** [comment]
updated to new PR from me #670
