### ISSUE TITLE
How can I view the files, such as an image that I receive by webhook, the URL that it returns has the extension .enc

### ISSUE THREAD

**Issue by billantony** [salman0ansari/whatsapp-api-nodejs#67]

**Comment by salman0ansari** [comment]
Before sending webhook we have to download message content and then send base64 data in response.
thanks for reporting i will fix this issue tomorrow.

**Comment by billantony** [comment]
How can I download the multimedia content of the webhook?

**Comment by fitwan** [comment]
Update please
