### ISSUE TITLE
WhatsApp session not able to connect

### ISSUE THREAD

**Issue by billantony** [salman0ansari/whatsapp-api-nodejs#679]
Hi,

For a few of the numbers, WhatsApp is not getting connected after scanning the QR code.

We have checked the logs and it seems keys values are not getting synched

**Comment by OmarSiolkoski** [comment]
I'm facing the same problem

**Comment by thitomazi** [comment]
Exactly the same problem with me and because of that, I've registered an issue too, because after trying scannig, the connection does not finish, and the key appears as a connected instance, but does not work. After that, it is not able to delete and qrcode in the same key it is not generated to try a new connection.

**Comment by syachrodi** [comment]
is there any solution guys?

**Comment by Natarajar87** [comment]
is there any solution guys?

**Comment by thitomazi** [comment]
Hello everyone! I've had the same problem and solutioned deleting the API folder and uninstalling the docker desktop. After this, it is necessary install all the API again with docker. The only problem is lose all connections, but it's just recreate them and everything works fine.

**Comment by billantony** [comment]
It was solved by changing the version of Baileys, it worked for me
![image](https://github.com/salman0ansari/whatsapp-api-nodejs/assets/30207442/f7cbf7fa-419f-428f-b847-3287fa1ea90d)

{
    "version": [2, 2323, 4]
}

**Comment by teuassuri2** [comment]
> Foi resolvido mudando a versão do Baileys, funcionou para mim ![imagem](https://user-images.githubusercontent.com/30207442/244884217-f7cbf7fa-419f-428f-b847-3287fa1ea90d.png)
> 
> { "versão": [2, 2323, 4] }

Resolvido pra mim

**Comment by felipermfalcao** [comment]
I changed the baileys version to [2, 2323, 4] and I keep getting error. The message is as follows: Please check your internet connection. See if you are connected to the internet. Something like.
