### ISSUE TITLE
Error: Cannot find module '@whiskeysockets/baileys'

### ISSUE THREAD

**Issue by jatinsne** [salman0ansari/whatsapp-api-nodejs#683]
from the last commit! yarn throwing error

**Comment by julianolandim** [comment]
It happened to me, checkout to the previous commit. At least for me, it worked :)

**Comment by jatinsne** [comment]
Then qr is not generating!

**Comment by julianolandim** [comment]
I also have this problem, I can generate the QR code but for that I have to create a new instance, however when I try to scan the code on my phone it returns me an error. I spoke to the API creator and he told me that this API is not to be used in production and offered me another one that is paid.

**Comment by marcospaulo-4** [comment]
If you're using Baileys 4.4 like I was, you can update to the same version mentioned here, it worked fine for me (https://github.com/WhiskeySockets/Baileys/commit/534b1ea778152fa77bee47da291e1f3f5c153091)

**Comment by salman0ansari** [comment]
Delete node_modules then pull repo and install packages.
