### ISSUE TITLE
MongoDB error

### ISSUE THREAD

**Issue by exallhost** [salman0ansari/whatsapp-api-nodejs#687]
Hello!

I am facing errors in mongodb which results in restarting the api.

This is the error:
![Captura de Tela 2023-06-12 às 16 27 35](https://github.com/salman0ansari/whatsapp-api-nodejs/assets/48133685/78afc60e-88d2-4f18-8106-6427c83cc513)

`{"level":50,"time":1686597493170,"pid":27,"hostname":"5650394f7566","err":{"type":"MongoServerError","message":"ns not found","stack":"MongoServerError: ns not found\n    at Connect
ion.onMessage (/home/node/app/node_modules/mongodb/lib/cmap/connection.js:230:30)\n    at MessageStream.<anonymous> (/home/node/app/node_modules/mongodb/lib/cmap/connection.js:61:60
)\n    at MessageStream.emit (node:events:513:28)\n    at processIncomingData (/home/node/app/node_modules/mongodb/lib/cmap/message_stream.js:125:16)\n    at MessageStream._write (/
home/node/app/node_modules/mongodb/lib/cmap/message_stream.js:33:9)\n    at writeOrBuffer (node:internal/streams/writable:392:12)\n    at _write (node:internal/streams/writable:333:
10)\n    at Writable.write (node:internal/streams/writable:337:10)\n    at Socket.ondata (node:internal/streams/readable:766:22)\n    at Socket.emit (node:events:513:28)","ok":0,"co
de":26,"codeName":"NamespaceNotFound"},"msg":"ns not found"}
{"level":30,"time":1686597552809,"pid":27,"hostname":"5650394f7566","msg":"SIGTERM received"}
yarn run v1.22.19
$ node src/server.js
{"level":30,"time":1686597555143,"pid":28,"hostname":"5650394f7566","msg":"Listening to port 3333"}
{"level":30,"time":1686597555149,"pid":28,"hostname":"5650394f7566","msg":"STATE: Connecting to MongoDB"}
{"level":30,"time":1686597555209,"pid":28,"hostname":"5650394f7566","msg":"Connected to MongoDB"}
{"level":30,"time":1686597555213,"pid":28,"hostname":"5650394f7566","msg":"STATE: Successfully connected to MongoDB"}
{"level":30,"time":1686597555213,"pid":28,"hostname":"5650394f7566","msg":"Restoring Sessions"}
`

After that it restarts thanks to a monitoring that I do and all sessions are restored, but I would like this instability not to happen.

**Comment by salman0ansari** [comment]
msg me on telegram i have solution
telegram.dog/salman0ansari
