### ISSUE TITLE
no account exists if whatsapp number have eleven digits including the country code

### ISSUE THREAD

**Issue by ekoilkom** [salman0ansari/whatsapp-api-nodejs#689]
I have error when i have number with only have  eleven character like this 6280158**** , This user has a whatsapp number, I checked with the group feature to find out. the number is registered as a grub member. But every time I send a message, the account doesn't exist. All numbers with a total of eleven digits including the country code experience the same problem

{
    "error": true,
    "code": 500,
    "message": "Error: no account exists"
}

**Comment by salman0ansari** [comment]
report this here [WhiskeySockets/Baileys](https://github.com/WhiskeySockets/Baileys/issues/)
