### ISSUE TITLE
empty buttons in iphone

### ISSUE THREAD

**Issue by cduarte** [salman0ansari/whatsapp-api-nodejs#69]
Hi

I tested the examples of send message with buttons that have in Postman Docs
"Send Button(Template) Message" and "Send Button With Media" 
But I received in the iphone with more buttons than specify in the json and that buttons is empty
![WhatsApp Image 2022-04-08 at 02 28 20](https://user-images.githubusercontent.com/810062/162346629-5139b274-6319-40d3-abdc-eeb0deaa8796.jpeg)
![WhatsApp Image 2022-04-08 at 02 28 19](https://user-images.githubusercontent.com/810062/162346631-87748a85-8a61-4bd7-963a-44e22b16df75.jpeg)

**Comment by salman0ansari** [comment]
what happens when you click those blank button?

**Comment by salman0ansari** [comment]
what happens when you click blank button?

**Comment by cduarte** [comment]
> what happens when you click blank button?

reply with a white message

**Comment by cduarte** [comment]
> what happens when you click blank button?

reply with a empty message


![WhatsApp Image 2022-04-09 at 13 05 54](https://user-images.githubusercontent.com/810062/162573497-53c4a81a-403b-448a-80f1-1204ba9ed472.jpeg)

**Comment by salman0ansari** [comment]
I can't help i don't have an iphone
maybe try tweaking buttons payload will fix this

**Comment by cduarte** [comment]
I did more tests
In whatsapp web is ok always.

The problem is on iphone:
- when send only buttons type "replyButton" can send one or more and every time is OK!
- when send only one button urlButton/callButton is Ok.

- PROBLEM:  when send more than one button and have one of this is type urlButton/callButton - bug (show empty buttons)

For each button type urlButton/callButton is show one empty button

**Comment by cduarte** [comment]
The problem is not in this project

The problem is in the Baileys
