### ISSUE TITLE
How to put a custom webhook url per created instance?

### ISSUE THREAD

**Issue by billantony** [salman0ansari/whatsapp-api-nodejs#71]

**Comment by salman0ansari** [comment]
Not supported yet

**Comment by salman0ansari** [comment]
> We Have to implrement data store first, so we can store your URL.

will do it soon

**Comment by devalexanderdaza** [comment]
> > We Have to implrement data store first, so we can store your URL.
> 
> will do it soon

I work in this feature today and send a PR.

**Comment by dasmond1** [comment]
I think this issue must be close, thanks @devalexanderdaza and @salman0ansari for your hard work

**Comment by renerlemes** [comment]
@devalexanderdaza when I use the endpoint to restore all instances, the webbook not working correct?
