### ISSUE TITLE
Auto Logout after scan QR Code

### ISSUE THREAD

**Issue by baagas0** [salman0ansari/whatsapp-api-nodejs#72]
this my issue, i scan barcode from my phone and show whatsapp web list in whatsapp apk but suddenly whatsapp is log out automatically. i dont catch any error in my terminal

**Comment by baagas0** [comment]
> Im using newest version

**Comment by baagas0** [comment]
![Screenshot_791](https://user-images.githubusercontent.com/61439302/163317799-df013f9b-c4bc-4bbd-b1ad-e1ae814cc1b3.png)


I Found this logs

**Comment by baagas0** [comment]
Someone please help me

**Comment by salman0ansari** [comment]
you using a new number?

**Comment by devalexanderdaza** [comment]
For solve this BUG, only connect your project with the mongodb, setting connection URL in config file.

Tell us your results please.

**Comment by baagas0** [comment]
> answer this questions
> 
>     * you using a new number?
> 
>     * are you using whatsapp Business?
> 
>     * is this your first time connecting to Multi Device Connection?

Thanks brother, solve by this questions

**Comment by manojsitapara** [comment]
> For solve this BUG, only connect your project with the mongodb, setting connection URL in config file.
> 
> Tell us your results please.

MongoDB is not implemented to save connection state in database, isn't it?
