### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by LuisArteModelo** [salman0ansari/whatsapp-api-nodejs#725]
I'm integrating this project with another one I've already developed, but when trying to connect via JS Axios I get the error:
Access to XMLHttpRequest at 'xxx' from origin 'xxx' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by salman0ansari** [comment]
You can add cors middleware

yarn add cors 
import cors
app.use(cors)
