### ISSUE TITLE
Generate custom instance with custom key and custom webhook

### ISSUE THREAD

**Issue by cleberlecheta** [salman0ansari/whatsapp-api-nodejs#726]
Hello there,

    I notice this situation: i initiate the session with the url below, informing a custom webhook url.

http://localhost:3333/instance/init?token=RANDOM_STRING_HERE&key=fbcf3908-ace6-406a-80a3-5ed81d9b5af6&webhook=true&webhookUrl=http://localhost:8036/whats/instance/hook/fbcf3908-ace6-406a-80a3-5ed81d9b5af6

    Everything works just fine, the issue is when i stop the server and start again, them I use the endpoint {{baseUrl}}/instance/list to check and the customUrl was override with the default webhook url. 

    I have made a 2 minutes video with this explanation. https://youtu.be/kjBvrXJwkV4

Could you assist in this matter?

Thank You in advance,

Cleber

**Comment by cleberlecheta** [comment]
I tried to comment the WEBHOOK_URL parameter and also tried to leave it with blank value, but it doesn't interfere in this matter.

**Comment by joaroque** [comment]
Same error

**Comment by salman0ansari** [comment]
We have to store webhook URL to DB or some file to restore it after restarting server.

**Comment by diogotoriani** [comment]
Exactly, this is the situation...

custom webhook works great until restart.
.. when restart it goes back to default defined in .env

**Comment by jjhoow** [comment]
I don't understand much about nodejs but I managed to make it work by changing the start of instance.js in the src/api/class folder
[instance.txt](https://github.com/salman0ansari/whatsapp-api-nodejs/files/12591676/instance.txt)

**Comment by jjhoow** [comment]
I don't understand much about nodejs but I managed to make it work by changing the start of instance.js in the src/api/class folder
[instance.txt](https://github.com/salman0ansari/whatsapp-api-nodejs/files/12591682/instance.txt)

**Comment by jonathandantaschagas** [comment]
Someone already resolve this issue?

**Comment by jonathandantaschagas** [comment]
> I don't understand much about nodejs but I managed to make it work by changing the start of instance.js in the src/api/class folder [instance.txt](https://github.com/salman0ansari/whatsapp-api-nodejs/files/12591682/instance.txt)

Fala, jjhow! Qual alteração você fez que resolveu o problema ?

**Comment by GHO5TMEDO** [comment]
Has anyone resolved this? @jjhoow, can you please let us know what you changed exactly, as I can't find any difference between the attached file and the original one?

@jonathandantaschagas have you found a fix yet?

Thanks.

**Comment by jjhoow** [comment]
> I don't understand much about nodejs but I managed to make it work by changing the start of instance.js in the src/api/class folder [instance.txt](https://github.com/salman0ansari/whatsapp-api-nodejs/files/12591682/instance.txt)

This code worked for me when I needed it, basically it takes advantage of the db/collection used by the api to store the session and webhook, when we restart the server it recovers automatically. I tested it for about 2 days and as far as I remember everything is fine...

**Comment by cleberlecheta** [comment]
> We have to store webhook URL to DB or some file to restore it after restarting server.

How can I do that? Could you provide a bit more details about it?

Thanks in advance.

**Comment by salman0ansari** [comment]
the project is not maintained anymore.

**Comment by cleberlecheta** [comment]
Thanks @jjhoow your solution does work as expected.
