### ISSUE TITLE
Restore one instance

### ISSUE THREAD

**Issue by LuisArteModelo** [salman0ansari/whatsapp-api-nodejs#728]
How can restore only one instance?

**Comment by sairmali** [comment]
+1

**Comment by LuisArteModelo** [comment]
I'm create a function ahead inside a "src\api\class\session.js" file, create a route in "src\api\routes\instance.route.js"

async restoreSessionByKey(key) {
        let restoredSessions = new Array()
        try {
            const db = mongoClient.db('whatsapp-api')
            const query = {}
            db.collection(key)
                .find(query)
                .toArray(async (err, result) => {
                    if (err) throw err
                    const webhook = !config.webhookEnabled
                        ? undefined
                        : config.webhookEnabled
                    const webhookUrl = !config.webhookUrl
                        ? undefined
                        : config.webhookUrl
                    const instance = new WhatsAppInstance(
                        key,
                        webhook,
                        webhookUrl
                    )
                    await instance.init()
                    WhatsAppInstances[key] = instance
                })
            restoredSessions.push(key)
        } catch (e) {
            logger.error('Error restoring session')
            logger.error(e)
        }
        return restoredSessions
    }

**Comment by LuisArteModelo** [comment]
I'm create a function ahead inside a "src\api\class\session.js" file, create a route in "src\api\routes\instance.route.js"

`async restoreSessionByKey(key) {
        let restoredSessions = new Array()
        try {
            const db = mongoClient.db('whatsapp-api')
            const query = {}
            db.collection(key)
                .find(query)
                .toArray(async (err, result) => {
                    if (err) throw err
                    const webhook = !config.webhookEnabled
                        ? undefined
                        : config.webhookEnabled
                    const webhookUrl = !config.webhookUrl
                        ? undefined
                        : config.webhookUrl
                    const instance = new WhatsAppInstance(
                        key,
                        webhook,
                        webhookUrl
                    )
                    await instance.init()
                    WhatsAppInstances[key] = instance
                })
            restoredSessions.push(key)
        } catch (e) {
            logger.error('Error restoring session')
            logger.error(e)
        }
        return restoredSessions
    }`

**Comment by LuisArteModelo** [comment]
Yes

**Comment by sairmali** [comment]
async restoreSessionByKey(key) {

        let restoredSessions = new Array()
        try {
            const db = mongoClient.db('whatsapp-api')
            const query = {}
            db.collection(key).find(query).toArray(async (err, result) => {
                if (err) throw err 
                const webhook = !config.webhookEnabled ? undefined : config.webhookEnabled
                const webhookUrl = !config.webhookUrl ? undefined : config.webhookUrl
                const instance = new WhatsAppInstance(key, webhook, webhookUrl)
                await instance.init()
                WhatsAppInstances[key] = instance
            })
            restoredSessions.push(key)
        }
        catch (e) {
            logger.error('Error restoring session')
            logger.error(e)
        }
        return restoredSessions

    }

**Comment by sairmali** [comment]
Error: Route.get() requires a callback function but got a [object Undefined]
    at Route.<computed> [as get] (\whatsapp-api-nodejs-main\node_modules\express\lib\router\route.js:211:15)
    at Object.<anonymous> (\whatsapp-api-nodejs-main\src\api\routes\instance.route.js:12:38)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (\whatsapp-api-nodejs-main\src\api\routes\index.js:3:24)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)

**Comment by sairmali** [comment]
router.route('/restoreSessionByKey').get(controller.restoreSessionByKey)

**Comment by achdiadsyah** [comment]
may be on typescript version this feature will be done to
