### ISSUE TITLE
MongoDB error

### ISSUE THREAD

**Issue by Jobians** [salman0ansari/whatsapp-api-nodejs#735]
myuser@vps:~/whatsapp-api-nodejs/src$ node server
{"level":30,"time":1689336751511,"pid":66336,"hostname":"vps","msg":"Listening on port 3333"}                               {"level":30,"time":1689336751546,"pid":66336,"hostname":"vps","msg":"STATE: Connecting to MongoDB"}                         {"level":50,"time":1689336781591,"pid":66336,"hostname":"vps","msg":"STATE: Connection to MongoDB failed!"}

**Comment by sairmali** [comment]
MONGODB_URL=mongodb+srv://<username>:<password>@cluster0.sikjaph.mongodb.net/<dbname>

add in your env file

**Comment by Jobians** [comment]
Thanks, it works now the problem is that I didn't set MONGODB_ENABLED to true
