### ISSUE TITLE
API don't send audioMessage

### ISSUE THREAD

**Issue by LuisArteModelo** [salman0ansari/whatsapp-api-nodejs#744]
I'm tryed many ways and audio formats (ogg, webm, mp3, mp4, acc, opus....) but don't send message.. 

The strangest thing is that in my account the audio sent appears, but the recipient does not receive it

**Comment by sairmali** [comment]
send me your code ?

**Comment by salman0ansari** [comment]
show request body.

**Comment by LuisArteModelo** [comment]
Sorry for the delay in returning, I was travelling.. it worked today, I believe it was an instability.
