### ISSUE TITLE
capture incoming messages

### ISSUE THREAD

**Issue by robinhodemorais** [salman0ansari/whatsapp-api-nodejs#76]
hello, I'm starting to test and I'm not able to receive the returns on the webhook, through the website https://webhook.site/ I got my url I configured it in .env and even in config.js, but I don't have a return there, when testing message sending everything is ok, but I need to capture the received messages to set up an AI, how do I do it?

**Comment by salman0ansari** [comment]
setup an ai lol if you want to create bot simply use Baileys lib.
