### ISSUE TITLE
Not Sending Image

### ISSUE THREAD

**Issue by Steevoh120** [salman0ansari/whatsapp-api-nodejs#766]
I cannot be able to send image files i.e post to `/message/image` results in error `TypeError: Cannot read properties of undefined (reading \u0027mimetype\u0027)\u0022}\n"
}`

My payload is
 `{
    "id": "**************",
    "caption": "Test Image Send",
    "file": "https://cdn.motor1.com/images/mgl/Mk3qg6/s3/2017-tesla-roadster-deck-model-petersen-automotive-museum.jpg"
}`

**Comment by salman0ansari** [comment]
use mediaurl endoint.

**Comment by Steevoh120** [comment]
> https://cdn.motor1.com/images/mgl/Mk3qg6/s3/2017-tesla-roadster-deck-model-petersen-automotive-museum.jpg

`/mediaurl` results in `Error: Invalid media type`. (Using the same payload)

**Comment by salman0ansari** [comment]
check postman docs.

**Comment by salman0ansari** [comment]
you aren't reading it carefully my friend.
You are missing something in body 👍🏻
read it carefully
