### ISSUE TITLE
PDF file get empty value for base64

### ISSUE THREAD

**Issue by xinkyo** [salman0ansari/whatsapp-api-nodejs#768]
I set WEBHOOK_BASE64=true
when device sent the PDF file, 
in the webhook get the base64 content is empty:
msgContent' => ''

for image and video i tested,  they are ok.

**Comment by salman0ansari** [comment]
add documentMessage here
https://github.com/salman0ansari/whatsapp-api-nodejs/blob/dc87691ec5a91263c1538fd576fac7333ee9e035/src/api/class/instance.js#L275
