### ISSUE TITLE
Message Status

### ISSUE THREAD

**Issue by Zarinia** [salman0ansari/whatsapp-api-nodejs#77]
Hi, and thanks for your pretty code
I have a question:
how can I check message status with it's id?

**Comment by Zarinia** [comment]
Or How to get "message_ack"

**Comment by salman0ansari** [comment]
not implemented

**Comment by Zarinia** [comment]
Oh, can you implement it:

**Comment by dasmond1** [comment]
> Oh, can you implement it:

Give Stars and watch this repo, i will do some new endpoint for chat and etc. But first we must create a data store first before doing any endpoint

**Comment by salman0ansari** [comment]
> > Oh, can you implement it:
> 
> Give Stars and watch this repo, i will do some new endpoint for chat and etc. But first we must create a data store first before doing any endpoint

Will do it Inshahallah after Ramadan.

**Comment by Zarinia** [comment]
Thanks alot

**Comment by salman0ansari** [comment]
i don't think we can check message status by its id
