### ISSUE TITLE
Callback to received message

### ISSUE THREAD

**Issue by LuisArteModelo** [salman0ansari/whatsapp-api-nodejs#772]
From what I understand there is no confirmation of reading the message sent by the recipient.. Is there a way to get this confirmation of reading?

**Comment by salman0ansari** [comment]
webhook.

**Comment by LuisArteModelo** [comment]
I understand, but what would be the necessary configuration to enable this return via webhook? because in the configuration I left WEBHOOK_ALLOWED_EVENTS=all
