### ISSUE TITLE
Message comes in format MEDIA url is enc

### ISSUE THREAD

**Issue by manhict** [salman0ansari/whatsapp-api-nodejs#776]
[https://i.ibb.co/zHKg0HM/Screenshot-2023-08-24-164321.png](https://i.ibb.co/zHKg0HM/Screenshot-2023-08-24-164321.png)

example: https://mmg.whatsapp.net/v/t62.7161-24/30258920_256380290611713_3602218111183988624_n.enc?ccb=11-4&oh=01_AdSm_da2XbJ2hnvSQlzE2BnUlfJRF3sJcmdNma6rSxtFVg&oe=650E8F45&mms3=true

message comes in format MEDIA url is enc, for example is 1 picture i need to convert to png with picture, and mp4 with video into 1 working url

**Comment by salman0ansari** [comment]
set WEBHOOK_BASE64=true

**Comment by ondiekisteven** [comment]
Thanks for this. Maybe you can include a comment on .env to indicate what WEBHOOK_BASE64=true does. It could be helpful. 
Thanks
