### ISSUE TITLE
Incoming Message

### ISSUE THREAD

**Issue by Zarinia** [salman0ansari/whatsapp-api-nodejs#78]
Hi, How can capture incoming messages?
new message with socket, etc
thanks

**Comment by dasmond1** [comment]
> Hi, How can capture incoming messages? new message with socket, etc thanks

socket not supported for now. webhook only. i'm still working to figure this out how to implement with socket

**Comment by Zarinia** [comment]
thanks, when do you implement it?

**Comment by salman0ansari** [comment]
not going to implement socket
