### ISSUE TITLE
Error when running "npm install"

### ISSUE THREAD

**Issue by kristen404** [salman0ansari/whatsapp-api-nodejs#79]
Just cloned the repo, went to its directory, ran `npm install`, and i got this error

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @adiwajshing/baileys@4.1.0
npm ERR! Found: sharp@0.30.3
npm ERR! node_modules/sharp
npm ERR!   sharp@"^0.30.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional sharp@"^0.29.3" from @adiwajshing/baileys@4.1.0
npm ERR! node_modules/@adiwajshing/baileys
npm ERR!   @adiwajshing/baileys@"^4.1.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: sharp@0.29.3
npm ERR! node_modules/sharp
npm ERR!   peerOptional sharp@"^0.29.3" from @adiwajshing/baileys@4.1.0
npm ERR!   node_modules/@adiwajshing/baileys
npm ERR!     @adiwajshing/baileys@"^4.1.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\dev\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dev\AppData\Local\npm-cache\_logs\2022-04-25T12_00_48_155Z-debug-0.log
```

**Comment by robinhodemorais** [comment]
install npm install --global yarn

after

yarn install

or

npm install --legacy-peer-deps

**Comment by kristen404** [comment]
> install npm install --global yarn
> 
> after
> 
> yarn install
> 
> or
> 
> npm install --legacy-peer-deps

Working after `npm install --legacy-peer-deps`, thanks.

**Comment by kristen404** [comment]
Reopening this, after some testing I discovered that this can be fixed by updating the `sharp` package, after i ran `npm install --save sharp@0.30.4` (actual latest version) this is definitively fixed.

**Comment by kristen404** [comment]
> > Reopening this, after some testing I discovered that this can be fixed by updating the `sharp` package, after i ran `npm install --save sharp@0.30.4` (actual latest version) this is definitively fixed.
> 
> good job brother.

do you think that `package.json` should be edited with this?

**Comment by sairmali** [comment]
npm install --force
