### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error on Init API

### ISSUE THREAD

**Issue by manojsitapara** [salman0ansari/whatsapp-api-nodejs#8]
When I invoke init api, getting following error message on console screen

> (node:5880) UnhandledPromiseRejectionWarning: Error
    at new RequestError (C:\Users\whatsapp-api-nodejs-main\node_modules\pusher\lib\errors.js:13:16)
    at C:\Users\whatsapp-api-nodejs-main\node_modules\pusher\lib\requests.js:61:17
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5880) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5880) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by salman0ansari** [comment]
Make sure your environmental variables are correct.

**Comment by salman0ansari** [comment]
How you're invoking init endpoint?

**Comment by manojsitapara** [comment]
I am sorry, Environment variable was not correct, after correcting it, works fine without any error on console screen.
