### ISSUE TITLE
QRcode

### ISSUE THREAD

**Issue by Zarinia** [salman0ansari/whatsapp-api-nodejs#80]
Hi again and thanks for your great work
when /init the app and then running /qr nothing returns and in qrbase64 that is the same and the response is empty 
what should I do and where is my mistake?
thanks

**Comment by salman0ansari** [comment]
maybe you're not passing key

**Comment by Zarinia** [comment]
I use postman and set key but I don't know what is my mistake
recheck your code and it's run very well but my code doesn't
Thanks,
please let me chack again

**Comment by Zarinia** [comment]
when connect and run qr again return null data same as in picture
<img width="1484" alt="Screen Shot 2022-04-27 at 21 42 18" src="https://user-images.githubusercontent.com/28263/165594410-9eb34df8-52cb-4e6a-8935-043dd70e7a05.png">

**Comment by Zarinia** [comment]
this test is on your code not me

**Comment by salman0ansari** [comment]
you have to call /qr endpoint ASAP you init an instance.

**Comment by Zarinia** [comment]
I call after about 3 seconds, sometimes right but sometimes not

**Comment by Zarinia** [comment]
It may be cached in postman or browser
