### ISSUE TITLE
how to run on windows

### ISSUE THREAD

**Issue by pauloanalista** [salman0ansari/whatsapp-api-nodejs#81]
Does anyone have a step by step to run on windows without errors?

**Comment by salman0ansari** [comment]
same steps as linux
- Download Node
- Clone Project
- Install Packages
- Set Env Variables
- Start Server

**Comment by pauloanalista** [comment]
I followed this step by step

Download Node
Clone Project  (git clone)
Install Packages (npm i)
Set Env Variables (ok)
Start Server (npm run dev)

Result
several errors

then i did it
npm install --legacy-peer-deps
npm install --save sharp@0.30.4

![image](https://user-images.githubusercontent.com/6010161/165747784-be408348-6e1c-4e15-ab43-f0e3e214edb9.png)

**Comment by salman0ansari** [comment]
run `npm run start` or `yarn start`

**Comment by pauloanalista** [comment]
![image](https://user-images.githubusercontent.com/6010161/165813543-3838d27c-d9dd-4d47-b69f-30b3f13406e3.png)
