### ISSUE TITLE
webhook 

### ISSUE THREAD

**Issue by clusterdevm** [salman0ansari/whatsapp-api-nodejs#821]
As an instance I initialize an instance, I inform what the webhook will be, when doing a pm2 reload all it does not load the webhook defined for the instance. How to solve it?

**Comment by GHO5TMEDO** [comment]
I'm having the exact same issue, all webhook URLs are removed on reload/restart of the server!

**Comment by GHO5TMEDO** [comment]
I have fixed it by saving webhook URL to a JSON file and retrieving it in sessions.js in the restoreSession function.

**Comment by cleberlecheta** [comment]
This also bugs me out!

**Comment by cleberlecheta** [comment]
> sessions.js

Hi @GHO5TMEDO can you attached your changed files, so that we can apply the same solution? That would be very helpful these times.. 

Thank you in advance.

**Comment by GHO5TMEDO** [comment]
> > sessions.js
> 
> Hi @GHO5TMEDO can you attached your changed files, so that we can apply the same solution? That would be very helpful these times..
> 
> Thank you in advance.

Please message me on Telegram @ Mohibrahim22 and I will send you the link to chatgpt conversation with detailed steps xD
