### ISSUE TITLE
how to can I resolve

### ISSUE THREAD

**Issue by Rapidak** [salman0ansari/whatsapp-api-nodejs#826]
![image](https://github.com/salman0ansari/whatsapp-api-nodejs/assets/109798387/5a7ab34e-37cc-41aa-bcd1-3ae5e1bad5ba)
![image](https://github.com/salman0ansari/whatsapp-api-nodejs/assets/109798387/36b23d79-628e-43f1-835b-2794ec366c15)

**Comment by erickcred** [comment]
Hello! good morning all good ?

I had this same problem, but it is just an eslint warning, in this case for these mongodb processes, we can just disable eslint inspect

![image](https://github.com/salman0ansari/whatsapp-api-nodejs/assets/52205662/3e31f980-bb22-4e8e-95db-e1cb10d4860a)
