### ISSUE TITLE
Again i am facing this error ("Error: Timed Out")

### ISSUE THREAD

**Issue by sairmali** [salman0ansari/whatsapp-api-nodejs#83]
i have noticed one thing if my WhatsApp number is blocked when i am sending message so showing this error and server stop at this time 
Please sole this problem...

{"error":true,"code":500,"message":"Error: Timed Out"}

**Comment by Zarinia** [comment]
Yeah, I have the same problem too
Sometimes got an error 500 timed out

**Comment by sairmali** [comment]
@Zarinia what condition you are facing this problem?

**Comment by salman0ansari** [comment]
thanks for reporting

**Comment by Zarinia** [comment]
@sairmali 
I'm not sure it has to come again so I can send it to you

**Comment by sairmali** [comment]
@Zarinia i am definitely sure on this error

**Comment by sairmali** [comment]
@salman0ansari thanks for you lots please try to fix this

**Comment by sairmali** [comment]
@salman0ansari please fix this issue as soon as possible 
Thanks!!!!
