### ISSUE TITLE
How to enable storage in Mongodb database?

### ISSUE THREAD

**Issue by Sulivan1999** [salman0ansari/whatsapp-api-nodejs#88]
Hey! I would like to understand about storage in Mongodb database. I configured the connection and even connected to the console, but no information is saved in the bank. Keys continue to be stored in JSON format in the sessions folder. I did several tests of sending and receiving messages and also nothing was saved.

Is this option already working or is it something being implemented?

Note: I tested using a Mongodb Atlas instance

**Comment by dasmond1** [comment]
Mongodb Setting, for now is only for preparation but no model or database schema implemented yet. stay tune for update

**Comment by salman0ansari** [comment]
Data store isn't implemented yet

**Comment by Sulivan1999** [comment]
Not wanting to be picky, but is there any forecast for this implementation?

**Comment by melvas6** [comment]
I too am waiting for this update.

**Comment by Sulivan1999** [comment]
Hello @salman0ansari. I noticed some updates were made about the storage in the database, but in my tests the data keys are still saved in the "data storage" folder will it work storing in both places or can I just switch to the data database?

**Comment by salman0ansari** [comment]
> Hello @salman0ansari. I noticed some updates were made about the storage in the database, but in my tests the data keys are still saved in the "data storage" folder will it work storing in both places or can I just switch to the data database?

Current we are only saving saving events data to DB.
