### ISSUE TITLE
Request: Add API to fetch groups information

### ISSUE THREAD

**Issue by manojsitapara** [salman0ansari/whatsapp-api-nodejs#9]
Can you please add API to fetch all groups meta data?
Like group Id, group name, profile picture, list of members in the group, admin information etc.

**Comment by salman0ansari** [comment]
i am working on that will push code today or tomorrow.

**Comment by manojsitapara** [comment]
any chance to get this feature? sorry for asking again.

**Comment by salman0ansari** [comment]
please wait few days i will fix this issue soon
