### ISSUE TITLE
keep running npm start

### ISSUE THREAD

**Issue by drdaga** [salman0ansari/whatsapp-api-nodejs#90]
Newbie question
How to keep running npm run or npm start in background ??
bcoz after running npm start via ssh the instance is running 
if i exit the ssh the it doest runs ??

**Comment by salman0ansari** [comment]
pm2?

**Comment by salman0ansari** [comment]
Install pm2 globally by running  
`npm install -g pm2`
Then goto project directory
Now run this cmd
`pm2 start src/server.js`

**Comment by drdaga** [comment]
thankx
