### ISSUE TITLE
sending url

### ISSUE THREAD

**Issue by traderpedroso** [salman0ansari/whatsapp-api-nodejs#91]
sending url any of the 3 types return the same error

{"error":true,"code":500,"message":"TypeError: Cannot read properties of undefined (reading 'includes')"}

**Comment by Zarinia** [comment]
Because I think in
```
exports.Mediaurl = async (req, res) => {
    const data = await WhatsAppInstances[req.query.key].sendUrlMediaFile(
        req.body.id,
        req.body.url,
        req.body.type, // Types are [image, video, audio, document]
        req.body.mimetype, // mimeType of mediaFile / Check Common mimetypes in `https://mzl.la/3si3and`
        req.body.caption
    )
    return res.status(201).json({ error: false, data: data })
}
```
req.body.id not set correctly and return undefined

**Comment by Zarinia** [comment]
To fix the problem you should send a request as raw in the body such as the button function in postman
```
like this not send as form data
{
    "receiver": "xx987xx23x67",
    "url": "https://www.easytalk.ir/Portals/0/Images/Logo.png",
    "type": "image",
    "mimetype": ".png",
    "caption": "wowww"
}
```

**Comment by traderpedroso** [comment]
> To fix the problem you should send a request as raw in the body such as the button function in postman
> 
> ```
> like this not send as form data
> {
>     "id": "xx987xx23x67",
>     "url": "https://www.easytalk.ir/Portals/0/Images/Logo.png",
>     "type": "image",
>     "mimetype": ".png",
>     "caption": "wowww"
> }
> ```

thank you for you reply! still getting some error I did in raw curl request

**Comment by Zarinia** [comment]
Oh, Please check with the postman again and send your result
but before it, please debug the code
src/api/class.instance.js file line 227 
function:
```
getWhatsAppId(id) {
        if (id.includes('@g.us') || id.includes('@s.whatsapp.net')) return id;
        return id.includes('-') ? `${id}@g.us` : `${id}@s.whatsapp.net`;
    }
 ```
your problem is in this function when the id is null or undefined 
id.includes return undefined

**Comment by AshSoftTech** [comment]
To Fix this Problem you need to send data in form-urlencoded and also the is below
`like this not send as form data
{
    "id": "xx987xx23x67",
    "url": "https://www.easytalk.ir/Portals/0/Images/Logo.png",
    "type": "image",
    "mimetype": "image/png",
    "caption": "wowww"
}`
in id first 2 digits add your country code.

**Comment by traderpedroso** [comment]
> To Fix this Problem you need to send data in form-urlencoded and also the is below
> `like this not send as form data { "id": "xx987xx23x67", "url": "https://www.easytalk.ir/Portals/0/Images/Logo.png", "type": "image", "mimetype": "image/png", "caption": "wowww" }`
> in id first 2 digits add your country code.

thank you for your response ill try on localhost as im using cloudflare proxy and everything is working well only the file url not working could be some problema related to ssl and I'll take off the jwt and test from source thanks for your help
