### ISSUE TITLE
sending url

### ISSUE THREAD

**Issue by Natarajar87** [salman0ansari/whatsapp-api-nodejs#93]
{"error":true,"code":500,"message":"TypeError: Cannot read properties of undefined (reading 'includes')"}

$key=$_REQUEST['key'];
$serial=$_REQUEST['serial'];
$id=$_REQUEST['phone'];
$url=$_REQUEST['url'];

$curl = curl_init();

curl_setopt_array($curl, array(
    CURLOPT_URL => 'http://localhost:3333/message/mediaurl?key='.$key,
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => '',
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 0,
    CURLOPT_FOLLOWLOCATION => true,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => 'POST',
    CURLOPT_POSTFIELDS => array('id' => $id,'url' => $url,'type' => 'document','mimetype'=>'','caption' => 'My Invoice'),
));

$response = curl_exec($curl);

curl_close($curl);
echo $response;

**Comment by Natarajar87** [comment]
$key=$_REQUEST['key'];
$serial=$_REQUEST['serial'];
$id=$_REQUEST['phone'];
$file=$_REQUEST['url'];


$curl = curl_init();

curl_setopt_array($curl, array(
    CURLOPT_URL => 'http://localhost:3333/message/mediaurl?key='.$key,
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => '',
    CURLOPT_MAXREDIRS => 10,
    CURLOPT_TIMEOUT => 0,
    CURLOPT_FOLLOWLOCATION => true,
    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST => 'POST',
    CURLOPT_POSTFIELDS => array('id' => $id,'url' => $file,'type' => 'document','mimetype'=>'','caption' => 'My Invoice'),
));

$response = curl_exec($curl);

curl_close($curl);
echo $response;

I used this code

But not working 
plz help me

**Comment by salman0ansari** [comment]
Sorry i dont understand PHP 🤢
 any php guy? Help needed

**Comment by Zarinia** [comment]
@Natarajar87 
Hi, please send the header sent after running PHP curl.

**Comment by dasmond1** [comment]
did you want a sample curl code ? with PHP languange ???

**Comment by dasmond1** [comment]
> {"error":true,"code":500,"message":"TypeError: Cannot read properties of undefined (reading 'includes')"}
> 
> $key=$_REQUEST['key']; $serial=$_REQUEST['serial']; $id=$_REQUEST['phone']; $url=$_REQUEST['url'];
> 
> $curl = curl_init();
> 
> curl_setopt_array($curl, array( CURLOPT_URL => 'http://localhost:3333/message/mediaurl?key='.$key, CURLOPT_RETURNTRANSFER => true, CURLOPT_ENCODING => '', CURLOPT_MAXREDIRS => 10, CURLOPT_TIMEOUT => 0, CURLOPT_FOLLOWLOCATION => true, CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1, CURLOPT_CUSTOMREQUEST => 'POST', CURLOPT_POSTFIELDS => array('id' => $id,'url' => $url,'type' => 'document','mimetype'=>'','caption' => 'My Invoice'), ));
> 
> $response = curl_exec($curl);
> 
> curl_close($curl); echo $response;

first of all. your costum request is wrong. instead POST you must be using GET

**Comment by dasmond1** [comment]
Try using postman for sending data or file, and get your code from ther..
if you using form-data to send a body try using x-www-urlencoded, and its work for me
![image](https://user-images.githubusercontent.com/10724051/166893119-5e2ba44d-d2e0-4aaf-aa2a-58b0c1e5f937.png)

**Comment by billantony** [comment]
$curl = curl_init();

curl_setopt_array($curl, [
  CURLOPT_URL => "http://localhost:3333/message/mediaurl?key=$key",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
  CURLOPT_POSTFIELDS => array('id' => $id,'url' => $url,'type' => 'document','mimetype '=>'','caption' => 'Mi factura'),
  CURLOPT_HTTPHEADER => [
    "Content-Type: application/x-www-form-urlencoded"
  ],
]);

$response = curl_exec($curl);
$err = curl_error($curl);

curl_close($curl);

**Comment by Natarajar87** [comment]
> {"error":true,"code":500,"message":"TypeError: Cannot read properties of undefined (reading 'includes')"}
> 
> $key=$_REQUEST['key']; $serial=$_REQUEST['serial']; $id=$_REQUEST['phone']; $url=$_REQUEST['url'];
> 
> $curl = curl_init();
> 
> curl_setopt_array($curl, array( CURLOPT_URL => 'http://localhost:3333/message/mediaurl?key='.$key, CURLOPT_RETURNTRANSFER => true, CURLOPT_ENCODING => '', CURLOPT_MAXREDIRS => 10, CURLOPT_TIMEOUT => 0, CURLOPT_FOLLOWLOCATION => true, CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1, CURLOPT_CUSTOMREQUEST => 'POST', CURLOPT_POSTFIELDS => array('id' => $id,'url' => $url,'type' => 'document','mimetype'=>'','caption' => 'My Invoice'), ));
> 
> $response = curl_exec($curl);
> 
> curl_close($curl); echo $response;
