### ISSUE TITLE
Instance open and online all the time

### ISSUE THREAD

**Issue by hdmidia** [salman0ansari/whatsapp-api-nodejs#94]
Hi, first of all, a thank you... The API is great better than some I've tested.

I have the following problem, the instance opens and fires everything right, but it is online all the time, is there any configuration for closing the instance when not using it?

I'm learning to use Baileys now, I hope to contribute to the community soon.

**Comment by salman0ansari** [comment]
you want to close API server? Or you want hide online presence?

**Comment by hdmidia** [comment]
Hide online presence!
