### ISSUE TITLE
FILE NAME AND CAPTION for document file

### ISSUE THREAD

**Issue by drdaga** [salman0ansari/whatsapp-api-nodejs#96]
![image](https://user-images.githubusercontent.com/45959508/167615420-2de9a09e-5c98-4ddf-97b7-7d8f00e8aabe.png)
![image](https://user-images.githubusercontent.com/45959508/167615670-72aaf5e3-7738-4aac-bcc6-378e4250782b.png)

not able to set file name for document send via url and also not able to send caption 
please check attached images

**Comment by salman0ansari** [comment]
you can't send caption with document message

**Comment by salman0ansari** [comment]
for custom filename add `filename` into formdata
https://documenter.getpostman.com/view/12514774/UVsPQkBq#267fde06-a130-4f42-99f8-a8bb7242fdf1
![image](https://user-images.githubusercontent.com/30106022/167666244-eb451b93-61c9-475e-a873-36121a53ee27.png)

**Comment by drdaga** [comment]
but i am sending file url as using dynamically generated file which i have to send via api
and with file url even i add filename it doesnt sends the filename

**Comment by drdaga** [comment]
![image](https://user-images.githubusercontent.com/45959508/167788543-11163d99-5ae8-4cf6-94f5-4a98003300df.png)

**Comment by drdaga** [comment]
also how to send multiple file url ??

**Comment by salman0ansari** [comment]
media url doesn't support custom file name

**Comment by AshSoftTech** [comment]
`src/api/controllers/message.controller.js` write extra parameters after 55 line req.body.filename then pass filename with api.

**Comment by drdaga** [comment]
> req.body.filename

i tried but it doest passes the filename

**Comment by drdaga** [comment]
donr made few changes now working
