### ISSUE TITLE
giving invalid key error

### ISSUE THREAD

**Issue by drdaga** [salman0ansari/whatsapp-api-nodejs#98]
i have 3 instances even i checked with list instances got the instance key 

till yesterday everything was working

all of sudden i am facing this issue of invalid key for all my instances

**Comment by salman0ansari** [comment]
restart server and hit /instance/restore endpoint

**Comment by salman0ansari** [comment]
solved?

**Comment by salman0ansari** [comment]
I am 100% sure you are using Heroku
