### ISSUE TITLE
Instance Lost after some time

### ISSUE THREAD

**Issue by baagas0** [salman0ansari/whatsapp-api-nodejs#99]
I'm try to init instance and scan for login, its successfully and api running with normally

but after a while of not being used, suddenly the key disappeared from the list
i try to restorring with api /instance/restrore, but i get null array [ ] response
![Screenshot_873](https://user-images.githubusercontent.com/61439302/168412931-4aa4a387-86d9-42bb-a4fa-c2a6b3837e69.png)

and i check in whatsapp application -> linked device its show session in list

![Screenshot_2022-05-14-12-23-32-637_com whatsapp](https://user-images.githubusercontent.com/61439302/168412983-be24b11b-9f33-4888-8e40-e81a7d0eee29.jpg)

someone can help me please??

**Comment by salman0ansari** [comment]
Give me a screenshot of `sessiondata` folder

**Comment by baagas0** [comment]
> Give me a screenshot of `sessiondata` folder

![Screenshot_880](https://user-images.githubusercontent.com/61439302/168530815-a03c093e-9f1a-4d0a-990c-e96e973f4521.png)

**Comment by baagas0** [comment]
This is my .env config
![Screenshot_881](https://user-images.githubusercontent.com/61439302/168532142-7a35127f-d6fb-491c-b429-bfe8a15795d7.png)

**Comment by salman0ansari** [comment]
Google before opening an issue
https://help.heroku.com/K1PPS2WM/why-are-my-file-uploads-missing-deleted-from-the-application

**Comment by salman0ansari** [comment]
irrelevant
